export const currencyLocalizationFallbacks: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Common.Active": "نشط",
    "Common.AuditTrail": "مسار التدقيق",
    "Common.Delete": "حذف",
    "Common.No": "لا",
    "Common.Saving": "جارٍ الحفظ...",
    "Common.Select": "اختر",
    "Common.Status": "الحالة",
    "Common.Yes": "نعم",
    "Page.Title.Currencies": "العملات",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "بيانات العملات مع التنسيق والتفعيل.",
    "Page.Title.CreateCurrency": "إنشاء عملة",
    "Page.Description.CreateAndActivateNewCurrency": "إنشاء وتفعيل عملة جديدة.",
    "Page.Title.EditCurrency": "تعديل العملة",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "تحديث إعداد العملة وسعرها الافتراضي إلى عملة المستأجر الأساسية.",
    "Page.Title.ExchangeRates": "أسعار الصرف",
    "Page.Description.HistoricalAndManualOverrideRates": "أسعار تاريخية وأسعار معدلة يدويًا.",
    "Page.Title.CreateExchangeRate": "إنشاء سعر صرف",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "إنشاء أو تعديل أسعار الصرف حسب التاريخ.",
    "Page.Title.CurrencyConversion": "تحويل العملات",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "التحويل بين العملات باستخدام الأسعار التاريخية المحفوظة.",
    "Page.Title.CurrencyRevaluation": "إعادة تقييم العملة",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "تسجيل إعادة التقييم والفروقات للأرصدة الأجنبية.",
    "Page.Title.TenantCurrencySetup": "إعداد عملات المستأجر",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "تفعيل العملات وتحديد العملة الأساسية للمستأجر.",
    "Currency.Amount": "المبلغ",
    "Currency.Base": "أساسية",
    "Currency.Code": "الكود",
    "Currency.Convert": "تحويل",
    "Currency.Converted": "محول",
    "Currency.CountryRegion": "الدولة/المنطقة",
    "Currency.Currency": "العملة",
    "Currency.CurrencyCode": "كود العملة",
    "Currency.CurrencyName": "اسم العملة",
    "Currency.CurrencyLower": "عملة",
    "Currency.Date": "التاريخ",
    "Currency.DecimalPlaces": "المنازل العشرية",
    "Currency.Decimals": "عشري",
    "Currency.DefaultExchangeRateToBaseCurrency": "سعر الصرف الافتراضي إلى العملة الأساسية",
    "Currency.DefaultExchangeRateWithBase": "سعر الصرف الافتراضي (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "اختياري. أدخل مقدار {0} الذي يساوي وحدة واحدة من هذه العملة. حفظ السعر يفعّل العملة لهذا المستأجر تلقائيًا.",
    "Currency.BaseCurrencyRequiredHelp": "يجب إعداد العملة الأساسية للمستأجر قبل حفظ سعر صرف افتراضي.",
    "Currency.BaseCurrencyFixedRateHelp": "هذه هي العملة الأساسية للمستأجر وتستخدم دائمًا سعر صرف 1.",
    "Currency.ConfigureTenantBaseCurrencyFirst": "قم بإعداد العملة الأساسية للمستأجر أولاً",
    "Currency.DeleteCurrencyQuestion": "حذف العملة؟",
    "Currency.DifferenceAmount": "مبلغ الفرق",
    "Currency.EffectiveDate": "تاريخ السريان",
    "Currency.Enabled": "مفعلة",
    "Currency.ExchangeRateEffectiveDate": "تاريخ سريان سعر الصرف",
    "Currency.ExchangeRateExample": "مثال: 1 {0} في {1}",
    "Currency.Format": "التنسيق",
    "Currency.FormatPattern": "نمط التنسيق",
    "Currency.From": "من",
    "Currency.FromCurrency": "من العملة",
    "Currency.ManualOverride": "تعديل يدوي",
    "Currency.Name": "الاسم",
    "Currency.NewCurrency": "عملة جديدة",
    "Currency.NewRate": "سعر جديد",
    "Currency.NoCountriesFound": "لم يتم العثور على دول",
    "Currency.OriginalAmount": "المبلغ الأصلي",
    "Currency.OverrideReason": "سبب التعديل",
    "Currency.Pair": "الزوج",
    "Currency.Rate": "السعر",
    "Currency.RateDate": "تاريخ السعر",
    "Currency.Reason": "السبب",
    "Currency.RecordRevaluation": "تسجيل إعادة التقييم",
    "Currency.RevaluationDate": "تاريخ إعادة التقييم",
    "Currency.RevaluedAmount": "المبلغ بعد التقييم",
    "Currency.RoundingPrecision": "دقة التقريب",
    "Currency.SaveCurrency": "حفظ العملة",
    "Currency.SaveExchangeRate": "حفظ سعر الصرف",
    "Currency.SearchCountry": "البحث عن دولة",
    "Currency.Source": "المصدر",
    "Currency.SourceDocumentId": "معرف المستند المصدر (GUID)",
    "Currency.SourceDocumentType": "نوع المستند المصدر",
    "Currency.Symbol": "الرمز",
    "Currency.To": "إلى",
    "Currency.ToCurrency": "إلى العملة"
  },
  "hi-IN": {
    "Common.Active": "सक्रिय",
    "Common.AuditTrail": "ऑडिट ट्रेल",
    "Common.Delete": "हटाएं",
    "Common.No": "नहीं",
    "Common.Saving": "सहेजा जा रहा है...",
    "Common.Select": "चुनें",
    "Common.Status": "स्थिति",
    "Common.Yes": "हाँ",
    "Page.Title.Currencies": "मुद्राएं",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "फ़ॉर्मेटिंग और सक्रियण सहित मुद्रा मास्टर।",
    "Page.Title.CreateCurrency": "मुद्रा बनाएं",
    "Page.Description.CreateAndActivateNewCurrency": "नई मुद्रा बनाएं और सक्रिय करें।",
    "Page.Title.EditCurrency": "मुद्रा संपादित करें",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "मुद्रा सेटअप और टेनेंट बेस मुद्रा की डिफ़ॉल्ट दर अपडेट करें।",
    "Page.Title.ExchangeRates": "विनिमय दरें",
    "Page.Description.HistoricalAndManualOverrideRates": "ऐतिहासिक और मैनुअल ओवरराइड दरें।",
    "Page.Title.CreateExchangeRate": "विनिमय दर बनाएं",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "तारीख के अनुसार विनिमय दर बनाएं या ओवरराइड करें।",
    "Page.Title.CurrencyConversion": "मुद्रा रूपांतरण",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "सहेजी गई ऐतिहासिक दरों से मुद्राओं के बीच रूपांतरण करें।",
    "Page.Title.CurrencyRevaluation": "मुद्रा पुनर्मूल्यांकन",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "विदेशी शेषों के लिए पुनर्मूल्यांकन और अंतर दर्ज करें।",
    "Page.Title.TenantCurrencySetup": "टेनेंट मुद्रा सेटअप",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "टेनेंट के लिए मुद्राएं सक्षम करें और बेस मुद्रा निर्धारित करें।",
    "Currency.Amount": "राशि",
    "Currency.Base": "बेस",
    "Currency.Code": "कोड",
    "Currency.Convert": "रूपांतरित करें",
    "Currency.Converted": "रूपांतरित",
    "Currency.CountryRegion": "देश/क्षेत्र",
    "Currency.Currency": "मुद्रा",
    "Currency.CurrencyCode": "मुद्रा कोड",
    "Currency.CurrencyName": "मुद्रा नाम",
    "Currency.CurrencyLower": "मुद्रा",
    "Currency.Date": "तारीख",
    "Currency.DecimalPlaces": "दशमलव स्थान",
    "Currency.Decimals": "दशमलव",
    "Currency.DefaultExchangeRateToBaseCurrency": "बेस मुद्रा के लिए डिफ़ॉल्ट विनिमय दर",
    "Currency.DefaultExchangeRateWithBase": "डिफ़ॉल्ट विनिमय दर (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "वैकल्पिक। दर्ज करें कि इस मुद्रा की एक इकाई कितनी {0} के बराबर है। दर सहेजने से यह मुद्रा इस टेनेंट के लिए स्वतः सक्षम हो जाती है।",
    "Currency.BaseCurrencyRequiredHelp": "डिफ़ॉल्ट विनिमय दर सहेजने से पहले टेनेंट बेस मुद्रा कॉन्फ़िगर होनी चाहिए।",
    "Currency.BaseCurrencyFixedRateHelp": "यह टेनेंट बेस मुद्रा है और हमेशा विनिमय दर 1 उपयोग करती है।",
    "Currency.ConfigureTenantBaseCurrencyFirst": "पहले टेनेंट बेस मुद्रा कॉन्फ़िगर करें",
    "Currency.DeleteCurrencyQuestion": "मुद्रा हटाएं?",
    "Currency.DifferenceAmount": "अंतर राशि",
    "Currency.EffectiveDate": "प्रभावी तारीख",
    "Currency.Enabled": "सक्षम",
    "Currency.ExchangeRateEffectiveDate": "विनिमय दर प्रभावी तारीख",
    "Currency.ExchangeRateExample": "उदाहरण: 1 {0} में {1}",
    "Currency.Format": "फ़ॉर्मेट",
    "Currency.FormatPattern": "फ़ॉर्मेट पैटर्न",
    "Currency.From": "से",
    "Currency.FromCurrency": "मुद्रा से",
    "Currency.ManualOverride": "मैनुअल ओवरराइड",
    "Currency.Name": "नाम",
    "Currency.NewCurrency": "नई मुद्रा",
    "Currency.NewRate": "नई दर",
    "Currency.NoCountriesFound": "कोई देश नहीं मिला",
    "Currency.OriginalAmount": "मूल राशि",
    "Currency.OverrideReason": "ओवरराइड कारण",
    "Currency.Pair": "जोड़ी",
    "Currency.Rate": "दर",
    "Currency.RateDate": "दर तारीख",
    "Currency.Reason": "कारण",
    "Currency.RecordRevaluation": "पुनर्मूल्यांकन दर्ज करें",
    "Currency.RevaluationDate": "पुनर्मूल्यांकन तारीख",
    "Currency.RevaluedAmount": "पुनर्मूल्यांकित राशि",
    "Currency.RoundingPrecision": "राउंडिंग सटीकता",
    "Currency.SaveCurrency": "मुद्रा सहेजें",
    "Currency.SaveExchangeRate": "विनिमय दर सहेजें",
    "Currency.SearchCountry": "देश खोजें",
    "Currency.Source": "स्रोत",
    "Currency.SourceDocumentId": "स्रोत दस्तावेज़ Id (GUID)",
    "Currency.SourceDocumentType": "स्रोत दस्तावेज़ प्रकार",
    "Currency.Symbol": "प्रतीक",
    "Currency.To": "तक",
    "Currency.ToCurrency": "मुद्रा तक"
  },
  "fr-FR": {
    "Common.Active": "Actif",
    "Common.AuditTrail": "Piste d’audit",
    "Common.Delete": "Supprimer",
    "Common.No": "Non",
    "Common.Saving": "Enregistrement...",
    "Common.Select": "Sélectionner",
    "Common.Status": "Statut",
    "Common.Yes": "Oui",
    "Page.Title.Currencies": "Devises",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "Référentiel devises avec formatage et activation.",
    "Page.Title.CreateCurrency": "Créer une devise",
    "Page.Description.CreateAndActivateNewCurrency": "Créer et activer une nouvelle devise.",
    "Page.Title.EditCurrency": "Modifier la devise",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "Mettre à jour la devise et son taux par défaut vers la devise de base du locataire.",
    "Page.Title.ExchangeRates": "Taux de change",
    "Page.Description.HistoricalAndManualOverrideRates": "Taux historiques et corrections manuelles.",
    "Page.Title.CreateExchangeRate": "Créer un taux de change",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "Créer ou remplacer des taux de change par date.",
    "Page.Title.CurrencyConversion": "Conversion de devise",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "Convertir les devises avec les taux historiques enregistrés.",
    "Page.Title.CurrencyRevaluation": "Réévaluation devise",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "Enregistrer la réévaluation et l’écart des soldes étrangers.",
    "Page.Title.TenantCurrencySetup": "Configuration des devises du locataire",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "Activer les devises et définir la devise de base du locataire.",
    "Currency.Amount": "Montant",
    "Currency.Base": "Base",
    "Currency.Code": "Code",
    "Currency.Convert": "Convertir",
    "Currency.Converted": "Converti",
    "Currency.CountryRegion": "Pays/Région",
    "Currency.Currency": "Devise",
    "Currency.CurrencyCode": "Code devise",
    "Currency.CurrencyName": "Nom de devise",
    "Currency.CurrencyLower": "devise",
    "Currency.Date": "Date",
    "Currency.DecimalPlaces": "Décimales",
    "Currency.Decimals": "Décimales",
    "Currency.DefaultExchangeRateToBaseCurrency": "Taux par défaut vers la devise de base",
    "Currency.DefaultExchangeRateWithBase": "Taux par défaut (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "Facultatif. Saisissez combien de {0} correspond à une unité de cette devise. L’enregistrement d’un taux active automatiquement cette devise pour ce locataire.",
    "Currency.BaseCurrencyRequiredHelp": "Une devise de base du locataire doit être configurée avant d’enregistrer un taux par défaut.",
    "Currency.BaseCurrencyFixedRateHelp": "C’est la devise de base du locataire et elle utilise toujours le taux 1.",
    "Currency.ConfigureTenantBaseCurrencyFirst": "Configurez d’abord la devise de base du locataire",
    "Currency.DeleteCurrencyQuestion": "Supprimer la devise ?",
    "Currency.DifferenceAmount": "Montant de l’écart",
    "Currency.EffectiveDate": "Date d’effet",
    "Currency.Enabled": "Activé",
    "Currency.ExchangeRateEffectiveDate": "Date d’effet du taux",
    "Currency.ExchangeRateExample": "Exemple : 1 {0} en {1}",
    "Currency.Format": "Format",
    "Currency.FormatPattern": "Modèle de format",
    "Currency.From": "De",
    "Currency.FromCurrency": "Devise source",
    "Currency.ManualOverride": "Correction manuelle",
    "Currency.Name": "Nom",
    "Currency.NewCurrency": "Nouvelle devise",
    "Currency.NewRate": "Nouveau taux",
    "Currency.NoCountriesFound": "Aucun pays trouvé",
    "Currency.OriginalAmount": "Montant original",
    "Currency.OverrideReason": "Motif de correction",
    "Currency.Pair": "Paire",
    "Currency.Rate": "Taux",
    "Currency.RateDate": "Date du taux",
    "Currency.Reason": "Motif",
    "Currency.RecordRevaluation": "Enregistrer la réévaluation",
    "Currency.RevaluationDate": "Date de réévaluation",
    "Currency.RevaluedAmount": "Montant réévalué",
    "Currency.RoundingPrecision": "Précision d’arrondi",
    "Currency.SaveCurrency": "Enregistrer la devise",
    "Currency.SaveExchangeRate": "Enregistrer le taux",
    "Currency.SearchCountry": "Rechercher un pays",
    "Currency.Source": "Source",
    "Currency.SourceDocumentId": "Id document source (GUID)",
    "Currency.SourceDocumentType": "Type de document source",
    "Currency.Symbol": "Symbole",
    "Currency.To": "Vers",
    "Currency.ToCurrency": "Devise cible"
  },
  "es-ES": {
    "Common.Active": "Activo",
    "Common.AuditTrail": "Pista de auditoría",
    "Common.Delete": "Eliminar",
    "Common.No": "No",
    "Common.Saving": "Guardando...",
    "Common.Select": "Seleccionar",
    "Common.Status": "Estado",
    "Common.Yes": "Sí",
    "Page.Title.Currencies": "Monedas",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "Maestro de monedas con formato y activación.",
    "Page.Title.CreateCurrency": "Crear moneda",
    "Page.Description.CreateAndActivateNewCurrency": "Crear y activar una nueva moneda.",
    "Page.Title.EditCurrency": "Editar moneda",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "Actualizar moneda y su tasa predeterminada a la moneda base del tenant.",
    "Page.Title.ExchangeRates": "Tipos de cambio",
    "Page.Description.HistoricalAndManualOverrideRates": "Tasas históricas y anulaciones manuales.",
    "Page.Title.CreateExchangeRate": "Crear tipo de cambio",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "Crear o sobrescribir tipos de cambio por fecha.",
    "Page.Title.CurrencyConversion": "Conversión de moneda",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "Convertir entre monedas usando tasas históricas guardadas.",
    "Page.Title.CurrencyRevaluation": "Revaluación de moneda",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "Registrar revaluación y variación de saldos extranjeros.",
    "Page.Title.TenantCurrencySetup": "Configuración de monedas del tenant",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "Habilitar monedas y definir la moneda base del tenant.",
    "Currency.Amount": "Importe",
    "Currency.Base": "Base",
    "Currency.Code": "Código",
    "Currency.Convert": "Convertir",
    "Currency.Converted": "Convertido",
    "Currency.CountryRegion": "País/Región",
    "Currency.Currency": "Moneda",
    "Currency.CurrencyCode": "Código de moneda",
    "Currency.CurrencyName": "Nombre de moneda",
    "Currency.CurrencyLower": "moneda",
    "Currency.Date": "Fecha",
    "Currency.DecimalPlaces": "Decimales",
    "Currency.Decimals": "Decimales",
    "Currency.DefaultExchangeRateToBaseCurrency": "Tipo de cambio predeterminado a moneda base",
    "Currency.DefaultExchangeRateWithBase": "Tipo predeterminado (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "Opcional. Indique cuánto {0} equivale a una unidad de esta moneda. Al guardar una tasa, la moneda se habilita automáticamente para este tenant.",
    "Currency.BaseCurrencyRequiredHelp": "Debe configurarse una moneda base del tenant antes de guardar un tipo predeterminado.",
    "Currency.BaseCurrencyFixedRateHelp": "Esta es la moneda base del tenant y siempre usa tipo de cambio 1.",
    "Currency.ConfigureTenantBaseCurrencyFirst": "Configure primero la moneda base del tenant",
    "Currency.DeleteCurrencyQuestion": "¿Eliminar moneda?",
    "Currency.DifferenceAmount": "Importe de diferencia",
    "Currency.EffectiveDate": "Fecha efectiva",
    "Currency.Enabled": "Habilitado",
    "Currency.ExchangeRateEffectiveDate": "Fecha efectiva del tipo",
    "Currency.ExchangeRateExample": "Ejemplo: 1 {0} en {1}",
    "Currency.Format": "Formato",
    "Currency.FormatPattern": "Patrón de formato",
    "Currency.From": "De",
    "Currency.FromCurrency": "Moneda origen",
    "Currency.ManualOverride": "Anulación manual",
    "Currency.Name": "Nombre",
    "Currency.NewCurrency": "Nueva moneda",
    "Currency.NewRate": "Nuevo tipo",
    "Currency.NoCountriesFound": "No se encontraron países",
    "Currency.OriginalAmount": "Importe original",
    "Currency.OverrideReason": "Motivo de anulación",
    "Currency.Pair": "Par",
    "Currency.Rate": "Tipo",
    "Currency.RateDate": "Fecha del tipo",
    "Currency.Reason": "Motivo",
    "Currency.RecordRevaluation": "Registrar revaluación",
    "Currency.RevaluationDate": "Fecha de revaluación",
    "Currency.RevaluedAmount": "Importe revaluado",
    "Currency.RoundingPrecision": "Precisión de redondeo",
    "Currency.SaveCurrency": "Guardar moneda",
    "Currency.SaveExchangeRate": "Guardar tipo de cambio",
    "Currency.SearchCountry": "Buscar país",
    "Currency.Source": "Origen",
    "Currency.SourceDocumentId": "Id documento origen (GUID)",
    "Currency.SourceDocumentType": "Tipo de documento origen",
    "Currency.Symbol": "Símbolo",
    "Currency.To": "A",
    "Currency.ToCurrency": "Moneda destino"
  },
  "zh-CN": {
    "Common.Active": "启用",
    "Common.AuditTrail": "审计跟踪",
    "Common.Delete": "删除",
    "Common.No": "否",
    "Common.Saving": "正在保存...",
    "Common.Select": "选择",
    "Common.Status": "状态",
    "Common.Yes": "是",
    "Page.Title.Currencies": "币种",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "币种主数据，包含格式和启用设置。",
    "Page.Title.CreateCurrency": "创建币种",
    "Page.Description.CreateAndActivateNewCurrency": "创建并启用新币种。",
    "Page.Title.EditCurrency": "编辑币种",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "更新币种设置及其到租户基础币种的默认汇率。",
    "Page.Title.ExchangeRates": "汇率",
    "Page.Description.HistoricalAndManualOverrideRates": "历史汇率和手工覆盖汇率。",
    "Page.Title.CreateExchangeRate": "创建汇率",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "按日期创建或覆盖汇率。",
    "Page.Title.CurrencyConversion": "币种转换",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "使用保存的历史汇率进行币种转换。",
    "Page.Title.CurrencyRevaluation": "币种重估",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "记录外币余额的重估和差异。",
    "Page.Title.TenantCurrencySetup": "租户币种设置",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "启用币种并定义租户基础币种。",
    "Currency.Amount": "金额",
    "Currency.Base": "基础",
    "Currency.Code": "代码",
    "Currency.Convert": "转换",
    "Currency.Converted": "已转换",
    "Currency.CountryRegion": "国家/地区",
    "Currency.Currency": "币种",
    "Currency.CurrencyCode": "币种代码",
    "Currency.CurrencyName": "币种名称",
    "Currency.CurrencyLower": "币种",
    "Currency.Date": "日期",
    "Currency.DecimalPlaces": "小数位",
    "Currency.Decimals": "小数",
    "Currency.DefaultExchangeRateToBaseCurrency": "到基础币种的默认汇率",
    "Currency.DefaultExchangeRateWithBase": "默认汇率 (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "可选。输入该币种一单位等于多少 {0}。保存汇率会自动为此租户启用该币种。",
    "Currency.BaseCurrencyRequiredHelp": "保存默认汇率前必须配置租户基础币种。",
    "Currency.BaseCurrencyFixedRateHelp": "这是租户基础币种，始终使用汇率 1。",
    "Currency.ConfigureTenantBaseCurrencyFirst": "请先配置租户基础币种",
    "Currency.DeleteCurrencyQuestion": "删除币种？",
    "Currency.DifferenceAmount": "差额",
    "Currency.EffectiveDate": "生效日期",
    "Currency.Enabled": "已启用",
    "Currency.ExchangeRateEffectiveDate": "汇率生效日期",
    "Currency.ExchangeRateExample": "示例：1 {0} 对 {1}",
    "Currency.Format": "格式",
    "Currency.FormatPattern": "格式模式",
    "Currency.From": "从",
    "Currency.FromCurrency": "源币种",
    "Currency.ManualOverride": "手工覆盖",
    "Currency.Name": "名称",
    "Currency.NewCurrency": "新币种",
    "Currency.NewRate": "新汇率",
    "Currency.NoCountriesFound": "未找到国家",
    "Currency.OriginalAmount": "原始金额",
    "Currency.OverrideReason": "覆盖原因",
    "Currency.Pair": "货币对",
    "Currency.Rate": "汇率",
    "Currency.RateDate": "汇率日期",
    "Currency.Reason": "原因",
    "Currency.RecordRevaluation": "记录重估",
    "Currency.RevaluationDate": "重估日期",
    "Currency.RevaluedAmount": "重估金额",
    "Currency.RoundingPrecision": "舍入精度",
    "Currency.SaveCurrency": "保存币种",
    "Currency.SaveExchangeRate": "保存汇率",
    "Currency.SearchCountry": "搜索国家",
    "Currency.Source": "来源",
    "Currency.SourceDocumentId": "来源单据 Id (GUID)",
    "Currency.SourceDocumentType": "来源单据类型",
    "Currency.Symbol": "符号",
    "Currency.To": "到",
    "Currency.ToCurrency": "目标币种"
  },
  "tr-TR": {
    "Common.Active": "Aktif",
    "Common.AuditTrail": "Denetim izi",
    "Common.Delete": "Sil",
    "Common.No": "Hayır",
    "Common.Saving": "Kaydediliyor...",
    "Common.Select": "Seç",
    "Common.Status": "Durum",
    "Common.Yes": "Evet",
    "Page.Title.Currencies": "Para birimleri",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "Biçimlendirme ve aktivasyon ile para birimi ana verisi.",
    "Page.Title.CreateCurrency": "Para birimi oluştur",
    "Page.Description.CreateAndActivateNewCurrency": "Yeni para birimi oluştur ve etkinleştir.",
    "Page.Title.EditCurrency": "Para birimini düzenle",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "Para birimi ayarını ve kiracı temel para birimine varsayılan kuru güncelle.",
    "Page.Title.ExchangeRates": "Döviz kurları",
    "Page.Description.HistoricalAndManualOverrideRates": "Geçmiş ve manuel geçersiz kılma kurları.",
    "Page.Title.CreateExchangeRate": "Döviz kuru oluştur",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "Tarihe göre döviz kuru oluştur veya geçersiz kıl.",
    "Page.Title.CurrencyConversion": "Para birimi dönüştürme",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "Kaydedilmiş geçmiş kurlarla para birimleri arasında dönüştür.",
    "Page.Title.CurrencyRevaluation": "Döviz değerleme",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "Yabancı bakiyeler için değerleme ve fark kaydet.",
    "Page.Title.TenantCurrencySetup": "Kiracı para birimi ayarı",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "Kiracı için para birimlerini etkinleştir ve temel para birimini belirle.",
    "Currency.Amount": "Tutar",
    "Currency.Base": "Temel",
    "Currency.Code": "Kod",
    "Currency.Convert": "Dönüştür",
    "Currency.Converted": "Dönüştürüldü",
    "Currency.CountryRegion": "Ülke/Bölge",
    "Currency.Currency": "Para birimi",
    "Currency.CurrencyCode": "Para birimi kodu",
    "Currency.CurrencyName": "Para birimi adı",
    "Currency.CurrencyLower": "para birimi",
    "Currency.Date": "Tarih",
    "Currency.DecimalPlaces": "Ondalık basamak",
    "Currency.Decimals": "Ondalık",
    "Currency.DefaultExchangeRateToBaseCurrency": "Temel para birimine varsayılan kur",
    "Currency.DefaultExchangeRateWithBase": "Varsayılan kur (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "İsteğe bağlı. Bu para biriminin bir biriminin kaç {0} ettiğini girin. Kur kaydedilince para birimi bu kiracı için otomatik etkinleşir.",
    "Currency.BaseCurrencyRequiredHelp": "Varsayılan kur kaydedilmeden önce kiracı temel para birimi yapılandırılmalıdır.",
    "Currency.BaseCurrencyFixedRateHelp": "Bu kiracı temel para birimidir ve her zaman 1 kurunu kullanır.",
    "Currency.ConfigureTenantBaseCurrencyFirst": "Önce kiracı temel para birimini yapılandırın",
    "Currency.DeleteCurrencyQuestion": "Para birimi silinsin mi?",
    "Currency.DifferenceAmount": "Fark tutarı",
    "Currency.EffectiveDate": "Geçerlilik tarihi",
    "Currency.Enabled": "Etkin",
    "Currency.ExchangeRateEffectiveDate": "Kur geçerlilik tarihi",
    "Currency.ExchangeRateExample": "Örnek: 1 {0}, {1} cinsinden",
    "Currency.Format": "Biçim",
    "Currency.FormatPattern": "Biçim deseni",
    "Currency.From": "Kimden",
    "Currency.FromCurrency": "Kaynak para birimi",
    "Currency.ManualOverride": "Manuel geçersiz kılma",
    "Currency.Name": "Ad",
    "Currency.NewCurrency": "Yeni para birimi",
    "Currency.NewRate": "Yeni kur",
    "Currency.NoCountriesFound": "Ülke bulunamadı",
    "Currency.OriginalAmount": "Orijinal tutar",
    "Currency.OverrideReason": "Geçersiz kılma nedeni",
    "Currency.Pair": "Parite",
    "Currency.Rate": "Kur",
    "Currency.RateDate": "Kur tarihi",
    "Currency.Reason": "Neden",
    "Currency.RecordRevaluation": "Değerleme kaydet",
    "Currency.RevaluationDate": "Değerleme tarihi",
    "Currency.RevaluedAmount": "Değerlenmiş tutar",
    "Currency.RoundingPrecision": "Yuvarlama hassasiyeti",
    "Currency.SaveCurrency": "Para birimini kaydet",
    "Currency.SaveExchangeRate": "Döviz kurunu kaydet",
    "Currency.SearchCountry": "Ülke ara",
    "Currency.Source": "Kaynak",
    "Currency.SourceDocumentId": "Kaynak belge Id (GUID)",
    "Currency.SourceDocumentType": "Kaynak belge türü",
    "Currency.Symbol": "Sembol",
    "Currency.To": "Kime",
    "Currency.ToCurrency": "Hedef para birimi"
  },
  "pt-PT": {
    "Common.Active": "Ativo",
    "Common.AuditTrail": "Trilho de auditoria",
    "Common.Delete": "Eliminar",
    "Common.No": "Não",
    "Common.Saving": "A guardar...",
    "Common.Select": "Selecionar",
    "Common.Status": "Estado",
    "Common.Yes": "Sim",
    "Page.Title.Currencies": "Moedas",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "Cadastro de moedas com formatação e ativação.",
    "Page.Title.CreateCurrency": "Criar moeda",
    "Page.Description.CreateAndActivateNewCurrency": "Criar e ativar nova moeda.",
    "Page.Title.EditCurrency": "Editar moeda",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "Atualizar moeda e taxa padrão para a moeda base do tenant.",
    "Page.Title.ExchangeRates": "Taxas de câmbio",
    "Page.Description.HistoricalAndManualOverrideRates": "Taxas históricas e substituições manuais.",
    "Page.Title.CreateExchangeRate": "Criar taxa de câmbio",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "Criar ou substituir taxas de câmbio por data.",
    "Page.Title.CurrencyConversion": "Conversão de moeda",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "Converter moedas usando taxas históricas guardadas.",
    "Page.Title.CurrencyRevaluation": "Reavaliação cambial",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "Registar reavaliação e variação de saldos estrangeiros.",
    "Page.Title.TenantCurrencySetup": "Configuração de moedas do tenant",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "Ativar moedas e definir moeda base do tenant.",
    "Currency.Amount": "Montante",
    "Currency.Base": "Base",
    "Currency.Code": "Código",
    "Currency.Convert": "Converter",
    "Currency.Converted": "Convertido",
    "Currency.CountryRegion": "País/Região",
    "Currency.Currency": "Moeda",
    "Currency.CurrencyCode": "Código da moeda",
    "Currency.CurrencyName": "Nome da moeda",
    "Currency.CurrencyLower": "moeda",
    "Currency.Date": "Data",
    "Currency.DecimalPlaces": "Casas decimais",
    "Currency.Decimals": "Decimais",
    "Currency.DefaultExchangeRateToBaseCurrency": "Taxa padrão para moeda base",
    "Currency.DefaultExchangeRateWithBase": "Taxa padrão (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "Opcional. Indique quanto {0} equivale a uma unidade desta moeda. Ao guardar a taxa, a moeda fica ativa automaticamente para este tenant.",
    "Currency.BaseCurrencyRequiredHelp": "A moeda base do tenant deve estar configurada antes de guardar uma taxa padrão.",
    "Currency.BaseCurrencyFixedRateHelp": "Esta é a moeda base do tenant e usa sempre taxa 1.",
    "Currency.ConfigureTenantBaseCurrencyFirst": "Configure primeiro a moeda base do tenant",
    "Currency.DeleteCurrencyQuestion": "Eliminar moeda?",
    "Currency.DifferenceAmount": "Montante da diferença",
    "Currency.EffectiveDate": "Data efetiva",
    "Currency.Enabled": "Ativo",
    "Currency.ExchangeRateEffectiveDate": "Data efetiva da taxa",
    "Currency.ExchangeRateExample": "Exemplo: 1 {0} em {1}",
    "Currency.Format": "Formato",
    "Currency.FormatPattern": "Padrão de formato",
    "Currency.From": "De",
    "Currency.FromCurrency": "Moeda origem",
    "Currency.ManualOverride": "Substituição manual",
    "Currency.Name": "Nome",
    "Currency.NewCurrency": "Nova moeda",
    "Currency.NewRate": "Nova taxa",
    "Currency.NoCountriesFound": "Nenhum país encontrado",
    "Currency.OriginalAmount": "Montante original",
    "Currency.OverrideReason": "Motivo da substituição",
    "Currency.Pair": "Par",
    "Currency.Rate": "Taxa",
    "Currency.RateDate": "Data da taxa",
    "Currency.Reason": "Motivo",
    "Currency.RecordRevaluation": "Registar reavaliação",
    "Currency.RevaluationDate": "Data de reavaliação",
    "Currency.RevaluedAmount": "Montante reavaliado",
    "Currency.RoundingPrecision": "Precisão de arredondamento",
    "Currency.SaveCurrency": "Guardar moeda",
    "Currency.SaveExchangeRate": "Guardar taxa de câmbio",
    "Currency.SearchCountry": "Pesquisar país",
    "Currency.Source": "Origem",
    "Currency.SourceDocumentId": "Id do documento origem (GUID)",
    "Currency.SourceDocumentType": "Tipo de documento origem",
    "Currency.Symbol": "Símbolo",
    "Currency.To": "Para",
    "Currency.ToCurrency": "Moeda destino"
  },
  "ru-RU": {
    "Common.Active": "Активно",
    "Common.AuditTrail": "Журнал аудита",
    "Common.Delete": "Удалить",
    "Common.No": "Нет",
    "Common.Saving": "Сохранение...",
    "Common.Select": "Выбрать",
    "Common.Status": "Статус",
    "Common.Yes": "Да",
    "Page.Title.Currencies": "Валюты",
    "Page.Description.CurrencyMasterWithFormattingAndActivation": "Справочник валют с форматированием и активацией.",
    "Page.Title.CreateCurrency": "Создать валюту",
    "Page.Description.CreateAndActivateNewCurrency": "Создать и активировать новую валюту.",
    "Page.Title.EditCurrency": "Изменить валюту",
    "Page.Description.UpdateCurrencySetupAndItsDefaultRateToTenantBaseCurrency": "Обновить валюту и курс по умолчанию к базовой валюте арендатора.",
    "Page.Title.ExchangeRates": "Курсы валют",
    "Page.Description.HistoricalAndManualOverrideRates": "Исторические и вручную измененные курсы.",
    "Page.Title.CreateExchangeRate": "Создать курс валюты",
    "Page.Description.CreateOrOverrideExchangeRatesByDate": "Создать или переопределить курсы по дате.",
    "Page.Title.CurrencyConversion": "Конвертация валют",
    "Page.Description.ConvertBetweenCurrenciesUsingSavedHistoricalRates": "Конвертация валют по сохраненным историческим курсам.",
    "Page.Title.CurrencyRevaluation": "Переоценка валюты",
    "Page.Description.RecordRevaluationAndVarianceForForeignBalances": "Записать переоценку и разницу по иностранным остаткам.",
    "Page.Title.TenantCurrencySetup": "Настройка валют арендатора",
    "Page.Description.EnableCurrenciesAndDefineBaseCurrencyForTheTenant": "Включить валюты и определить базовую валюту арендатора.",
    "Currency.Amount": "Сумма",
    "Currency.Base": "Базовая",
    "Currency.Code": "Код",
    "Currency.Convert": "Конвертировать",
    "Currency.Converted": "Сконвертировано",
    "Currency.CountryRegion": "Страна/регион",
    "Currency.Currency": "Валюта",
    "Currency.CurrencyCode": "Код валюты",
    "Currency.CurrencyName": "Название валюты",
    "Currency.CurrencyLower": "валюта",
    "Currency.Date": "Дата",
    "Currency.DecimalPlaces": "Десятичные знаки",
    "Currency.Decimals": "Десятичные",
    "Currency.DefaultExchangeRateToBaseCurrency": "Курс по умолчанию к базовой валюте",
    "Currency.DefaultExchangeRateWithBase": "Курс по умолчанию (1 {0} = ? {1})",
    "Currency.DefaultRateHelp": "Необязательно. Укажите, сколько {0} равно одной единице этой валюты. При сохранении курса валюта автоматически включается для арендатора.",
    "Currency.BaseCurrencyRequiredHelp": "Перед сохранением курса по умолчанию должна быть настроена базовая валюта арендатора.",
    "Currency.BaseCurrencyFixedRateHelp": "Это базовая валюта арендатора, всегда используется курс 1.",
    "Currency.ConfigureTenantBaseCurrencyFirst": "Сначала настройте базовую валюту арендатора",
    "Currency.DeleteCurrencyQuestion": "Удалить валюту?",
    "Currency.DifferenceAmount": "Сумма разницы",
    "Currency.EffectiveDate": "Дата действия",
    "Currency.Enabled": "Включено",
    "Currency.ExchangeRateEffectiveDate": "Дата действия курса",
    "Currency.ExchangeRateExample": "Пример: 1 {0} в {1}",
    "Currency.Format": "Формат",
    "Currency.FormatPattern": "Шаблон формата",
    "Currency.From": "Из",
    "Currency.FromCurrency": "Из валюты",
    "Currency.ManualOverride": "Ручное изменение",
    "Currency.Name": "Название",
    "Currency.NewCurrency": "Новая валюта",
    "Currency.NewRate": "Новый курс",
    "Currency.NoCountriesFound": "Страны не найдены",
    "Currency.OriginalAmount": "Исходная сумма",
    "Currency.OverrideReason": "Причина изменения",
    "Currency.Pair": "Пара",
    "Currency.Rate": "Курс",
    "Currency.RateDate": "Дата курса",
    "Currency.Reason": "Причина",
    "Currency.RecordRevaluation": "Записать переоценку",
    "Currency.RevaluationDate": "Дата переоценки",
    "Currency.RevaluedAmount": "Переоцененная сумма",
    "Currency.RoundingPrecision": "Точность округления",
    "Currency.SaveCurrency": "Сохранить валюту",
    "Currency.SaveExchangeRate": "Сохранить курс",
    "Currency.SearchCountry": "Поиск страны",
    "Currency.Source": "Источник",
    "Currency.SourceDocumentId": "Id исходного документа (GUID)",
    "Currency.SourceDocumentType": "Тип исходного документа",
    "Currency.Symbol": "Символ",
    "Currency.To": "В",
    "Currency.ToCurrency": "В валюту"
  }
};
