export const customerLocalizationFallbacks: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Common.Actions": "الإجراءات",
    "Common.Active": "نشط",
    "Common.Continue": "متابعة",
    "Common.Delete": "حذف",
    "Common.Edit": "تعديل",
    "Common.Remove": "إزالة",
    "Common.Review": "مراجعة",
    "Common.Saving": "جارٍ الحفظ...",
    "Common.Select": "اختر",
    "Common.Status": "الحالة",
    "Page.Title.Customers": "العملاء",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "بيانات العملاء مع ضوابط الائتمان والوصول إلى البوابة.",
    "Page.Title.CreateCustomer": "إنشاء عميل",
    "Page.Description.CreateCustomerProfileAndControls": "إنشاء ملف العميل والضوابط.",
    "Page.Title.EditCustomer": "تعديل العميل",
    "Page.Description.UpdateCustomerMasterData": "تحديث بيانات العميل الرئيسية.",
    "Customer.AddAddress": "إضافة عنوان",
    "Customer.AddContact": "إضافة جهة اتصال",
    "Customer.Address": "العنوان",
    "Customer.AuthorizedSalesmanTransfer": "نقل مندوب المبيعات المصرح",
    "Customer.BillingAddress": "عنوان الفوترة",
    "Customer.By": "بواسطة",
    "Customer.City": "المدينة",
    "Customer.Code": "الكود",
    "Customer.ConfirmCustomerCurrency": "تأكيد عملة العميل",
    "Customer.ContactName": "اسم جهة الاتصال",
    "Customer.ContactPerson": "الشخص المسؤول",
    "Customer.Country": "الدولة",
    "Customer.CreditLimit": "حد الائتمان",
    "Customer.CurrencyCannotChangeConfirm": "لا يمكن تغيير عملة العميل بعد إنشاء العميل. هل تريد المتابعة؟",
    "Customer.CurrencyLockedAfterCreation": "عملة العميل مقفلة بعد الإنشاء.",
    "Customer.CustomerCode": "كود العميل",
    "Customer.CustomerName": "اسم العميل",
    "Customer.CustomerType": "نوع العميل",
    "Customer.Default": "افتراضي",
    "Customer.DefaultCurrency": "العملة الافتراضية",
    "Customer.DeleteCustomer": "حذف العميل",
    "Customer.DeleteCustomerQuestion": "حذف العميل؟",
    "Customer.Designation": "المسمى الوظيفي",
    "Customer.DocumentDisplayNameOptional": "اسم عرض المستند (اختياري)",
    "Customer.EditCustomer": "تعديل العميل",
    "Customer.Email": "البريد الإلكتروني",
    "Customer.EnableTenantCurrencyBeforeSaving": "فعّل عملة في إعداد عملات المستأجر قبل حفظ العميل.",
    "Customer.LedgerHelp": "دفتر أستاذ العميل متاح من تقارير المحاسبة باستخدام فلتر العميل.",
    "Customer.Loading": "جارٍ التحميل...",
    "Customer.LoadingCustomer": "جارٍ تحميل العميل...",
    "Customer.Name": "الاسم",
    "Customer.NewCustomer": "عميل جديد",
    "Customer.NoTenantCurrencyEnabled": "لا توجد عملة مفعلة للمستأجر",
    "Customer.OpenCustomerLedgerReport": "فتح تقرير دفتر أستاذ العميل",
    "Customer.PaymentTerms": "شروط الدفع",
    "Customer.PaymentTermsExample": "مثال: 30 يومًا",
    "Customer.Phone": "الهاتف",
    "Customer.PortalAccessEnabled": "تمكين الوصول إلى البوابة",
    "Customer.Primary": "أساسي",
    "Customer.ReasonForReassignment": "سبب إعادة التعيين",
    "Customer.SalesmanOptional": "مندوب المبيعات (اختياري)",
    "Customer.SalesmanTransferHelp": "تتطلب إعادة التعيين مندوب مبيعات جديدًا وسببًا. يتم حفظ كل نقل في سجل التدقيق.",
    "Customer.SaveCustomer": "حفظ العميل",
    "Customer.ShippingAddress": "عنوان الشحن",
    "Customer.Tab.addresses": "العناوين",
    "Customer.Tab.contacts": "جهات الاتصال",
    "Customer.Tab.credit": "الائتمان",
    "Customer.Tab.documents": "المستندات",
    "Customer.Tab.main": "الرئيسية",
    "Customer.Transfer": "نقل",
    "Customer.Type": "النوع",
    "Customer.Unassigned": "غير معين",
    "Customer.UseSalesmanTransfer": "استخدم إجراء نقل مندوب المبيعات المصرح لتغيير هذا التعيين.",
    "Customer.ViewCustomer": "عرض العميل"
  },
  "hi-IN": {
    "Common.Actions": "कार्रवाई",
    "Common.Active": "सक्रिय",
    "Common.Continue": "जारी रखें",
    "Common.Delete": "हटाएं",
    "Common.Edit": "संपादित करें",
    "Common.Remove": "हटाएं",
    "Common.Review": "समीक्षा",
    "Common.Saving": "सहेजा जा रहा है...",
    "Common.Select": "चुनें",
    "Common.Status": "स्थिति",
    "Page.Title.Customers": "ग्राहक",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "क्रेडिट नियंत्रण और पोर्टल एक्सेस सहित ग्राहक मास्टर।",
    "Page.Title.CreateCustomer": "ग्राहक बनाएं",
    "Page.Description.CreateCustomerProfileAndControls": "ग्राहक प्रोफ़ाइल और नियंत्रण बनाएं।",
    "Page.Title.EditCustomer": "ग्राहक संपादित करें",
    "Page.Description.UpdateCustomerMasterData": "ग्राहक मास्टर डेटा अपडेट करें।",
    "Customer.AddAddress": "पता जोड़ें",
    "Customer.AddContact": "संपर्क जोड़ें",
    "Customer.Address": "पता",
    "Customer.AuthorizedSalesmanTransfer": "अधिकृत सेल्समैन ट्रांसफर",
    "Customer.BillingAddress": "बिलिंग पता",
    "Customer.By": "द्वारा",
    "Customer.City": "शहर",
    "Customer.Code": "कोड",
    "Customer.ConfirmCustomerCurrency": "ग्राहक मुद्रा पुष्टि करें",
    "Customer.ContactName": "संपर्क नाम",
    "Customer.ContactPerson": "संपर्क व्यक्ति",
    "Customer.Country": "देश",
    "Customer.CreditLimit": "क्रेडिट सीमा",
    "Customer.CurrencyCannotChangeConfirm": "ग्राहक बनने के बाद ग्राहक मुद्रा नहीं बदली जा सकती। क्या आप जारी रखना चाहते हैं?",
    "Customer.CurrencyLockedAfterCreation": "निर्माण के बाद ग्राहक मुद्रा लॉक हो जाती है।",
    "Customer.CustomerCode": "ग्राहक कोड",
    "Customer.CustomerName": "ग्राहक नाम",
    "Customer.CustomerType": "ग्राहक प्रकार",
    "Customer.Default": "डिफ़ॉल्ट",
    "Customer.DefaultCurrency": "डिफ़ॉल्ट मुद्रा",
    "Customer.DeleteCustomer": "ग्राहक हटाएं",
    "Customer.DeleteCustomerQuestion": "ग्राहक हटाएं?",
    "Customer.Designation": "पदनाम",
    "Customer.DocumentDisplayNameOptional": "दस्तावेज़ प्रदर्शन नाम (वैकल्पिक)",
    "Customer.EditCustomer": "ग्राहक संपादित करें",
    "Customer.Email": "ईमेल",
    "Customer.EnableTenantCurrencyBeforeSaving": "ग्राहक सहेजने से पहले टेनेंट मुद्रा सेटअप में मुद्रा सक्षम करें।",
    "Customer.LedgerHelp": "ग्राहक फ़िल्टर का उपयोग करके ग्राहक लेजर लेखा रिपोर्ट में उपलब्ध है।",
    "Customer.Loading": "लोड हो रहा है...",
    "Customer.LoadingCustomer": "ग्राहक लोड हो रहा है...",
    "Customer.Name": "नाम",
    "Customer.NewCustomer": "नया ग्राहक",
    "Customer.NoTenantCurrencyEnabled": "कोई टेनेंट मुद्रा सक्षम नहीं",
    "Customer.OpenCustomerLedgerReport": "ग्राहक लेजर रिपोर्ट खोलें",
    "Customer.PaymentTerms": "भुगतान शर्तें",
    "Customer.PaymentTermsExample": "जैसे 30 दिन",
    "Customer.Phone": "फोन",
    "Customer.PortalAccessEnabled": "पोर्टल एक्सेस सक्षम",
    "Customer.Primary": "प्राथमिक",
    "Customer.ReasonForReassignment": "पुनर्नियुक्ति का कारण",
    "Customer.SalesmanOptional": "सेल्समैन (वैकल्पिक)",
    "Customer.SalesmanTransferHelp": "पुनर्नियुक्ति के लिए नया सेल्समैन और कारण चाहिए। हर ट्रांसफर ऑडिट इतिहास में रखा जाता है।",
    "Customer.SaveCustomer": "ग्राहक सहेजें",
    "Customer.ShippingAddress": "शिपिंग पता",
    "Customer.Tab.addresses": "पते",
    "Customer.Tab.contacts": "संपर्क",
    "Customer.Tab.credit": "क्रेडिट",
    "Customer.Tab.documents": "दस्तावेज़",
    "Customer.Tab.main": "मुख्य",
    "Customer.Transfer": "ट्रांसफर",
    "Customer.Type": "प्रकार",
    "Customer.Unassigned": "असाइन नहीं",
    "Customer.UseSalesmanTransfer": "इस असाइनमेंट को बदलने के लिए अधिकृत सेल्समैन ट्रांसफर का उपयोग करें।",
    "Customer.ViewCustomer": "ग्राहक देखें"
  },
  "fr-FR": {
    "Common.Actions": "Actions",
    "Common.Active": "Actif",
    "Common.Continue": "Continuer",
    "Common.Delete": "Supprimer",
    "Common.Edit": "Modifier",
    "Common.Remove": "Retirer",
    "Common.Review": "Vérifier",
    "Common.Saving": "Enregistrement...",
    "Common.Select": "Sélectionner",
    "Common.Status": "Statut",
    "Page.Title.Customers": "Clients",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "Référentiel clients avec contrôle crédit et accès portail.",
    "Page.Title.CreateCustomer": "Créer un client",
    "Page.Description.CreateCustomerProfileAndControls": "Créer le profil client et les contrôles.",
    "Page.Title.EditCustomer": "Modifier le client",
    "Page.Description.UpdateCustomerMasterData": "Mettre à jour les données client.",
    "Customer.AddAddress": "Ajouter une adresse",
    "Customer.AddContact": "Ajouter un contact",
    "Customer.Address": "Adresse",
    "Customer.AuthorizedSalesmanTransfer": "Transfert commercial autorisé",
    "Customer.BillingAddress": "Adresse de facturation",
    "Customer.By": "par",
    "Customer.City": "Ville",
    "Customer.Code": "Code",
    "Customer.ConfirmCustomerCurrency": "Confirmer la devise client",
    "Customer.ContactName": "Nom du contact",
    "Customer.ContactPerson": "Personne de contact",
    "Customer.Country": "Pays",
    "Customer.CreditLimit": "Limite de crédit",
    "Customer.CurrencyCannotChangeConfirm": "La devise client ne peut plus être modifiée après création. Voulez-vous continuer ?",
    "Customer.CurrencyLockedAfterCreation": "La devise client est verrouillée après création.",
    "Customer.CustomerCode": "Code client",
    "Customer.CustomerName": "Nom du client",
    "Customer.CustomerType": "Type de client",
    "Customer.Default": "Défaut",
    "Customer.DefaultCurrency": "Devise par défaut",
    "Customer.DeleteCustomer": "Supprimer le client",
    "Customer.DeleteCustomerQuestion": "Supprimer le client ?",
    "Customer.Designation": "Fonction",
    "Customer.DocumentDisplayNameOptional": "Nom d’affichage du document (facultatif)",
    "Customer.EditCustomer": "Modifier le client",
    "Customer.Email": "E-mail",
    "Customer.EnableTenantCurrencyBeforeSaving": "Activez une devise dans la configuration du locataire avant d’enregistrer le client.",
    "Customer.LedgerHelp": "Le grand livre client est disponible dans les rapports comptables avec le filtre client.",
    "Customer.Loading": "Chargement...",
    "Customer.LoadingCustomer": "Chargement du client...",
    "Customer.Name": "Nom",
    "Customer.NewCustomer": "Nouveau client",
    "Customer.NoTenantCurrencyEnabled": "Aucune devise locataire activée",
    "Customer.OpenCustomerLedgerReport": "Ouvrir le rapport grand livre client",
    "Customer.PaymentTerms": "Conditions de paiement",
    "Customer.PaymentTermsExample": "p. ex. 30 jours",
    "Customer.Phone": "Téléphone",
    "Customer.PortalAccessEnabled": "Accès portail activé",
    "Customer.Primary": "Principal",
    "Customer.ReasonForReassignment": "Motif de réaffectation",
    "Customer.SalesmanOptional": "Commercial (facultatif)",
    "Customer.SalesmanTransferHelp": "La réaffectation nécessite un nouveau commercial et un motif. Chaque transfert est conservé dans l’audit.",
    "Customer.SaveCustomer": "Enregistrer le client",
    "Customer.ShippingAddress": "Adresse de livraison",
    "Customer.Tab.addresses": "Adresses",
    "Customer.Tab.contacts": "Contacts",
    "Customer.Tab.credit": "Crédit",
    "Customer.Tab.documents": "Documents",
    "Customer.Tab.main": "Principal",
    "Customer.Transfer": "Transférer",
    "Customer.Type": "Type",
    "Customer.Unassigned": "Non affecté",
    "Customer.UseSalesmanTransfer": "Utilisez le transfert commercial autorisé pour modifier cette affectation.",
    "Customer.ViewCustomer": "Voir le client"
  },
  "es-ES": {
    "Common.Actions": "Acciones",
    "Common.Active": "Activo",
    "Common.Continue": "Continuar",
    "Common.Delete": "Eliminar",
    "Common.Edit": "Editar",
    "Common.Remove": "Quitar",
    "Common.Review": "Revisar",
    "Common.Saving": "Guardando...",
    "Common.Select": "Seleccionar",
    "Common.Status": "Estado",
    "Page.Title.Customers": "Clientes",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "Maestro de clientes con control de crédito y acceso al portal.",
    "Page.Title.CreateCustomer": "Crear cliente",
    "Page.Description.CreateCustomerProfileAndControls": "Crear perfil y controles del cliente.",
    "Page.Title.EditCustomer": "Editar cliente",
    "Page.Description.UpdateCustomerMasterData": "Actualizar datos maestros del cliente.",
    "Customer.AddAddress": "Agregar dirección",
    "Customer.AddContact": "Agregar contacto",
    "Customer.Address": "Dirección",
    "Customer.AuthorizedSalesmanTransfer": "Transferencia autorizada de vendedor",
    "Customer.BillingAddress": "Dirección de facturación",
    "Customer.By": "por",
    "Customer.City": "Ciudad",
    "Customer.Code": "Código",
    "Customer.ConfirmCustomerCurrency": "Confirmar moneda del cliente",
    "Customer.ContactName": "Nombre de contacto",
    "Customer.ContactPerson": "Persona de contacto",
    "Customer.Country": "País",
    "Customer.CreditLimit": "Límite de crédito",
    "Customer.CurrencyCannotChangeConfirm": "La moneda del cliente no se puede cambiar después de crearlo. ¿Desea continuar?",
    "Customer.CurrencyLockedAfterCreation": "La moneda del cliente queda bloqueada después de la creación.",
    "Customer.CustomerCode": "Código de cliente",
    "Customer.CustomerName": "Nombre del cliente",
    "Customer.CustomerType": "Tipo de cliente",
    "Customer.Default": "Predeterminado",
    "Customer.DefaultCurrency": "Moneda predeterminada",
    "Customer.DeleteCustomer": "Eliminar cliente",
    "Customer.DeleteCustomerQuestion": "¿Eliminar cliente?",
    "Customer.Designation": "Cargo",
    "Customer.DocumentDisplayNameOptional": "Nombre visible del documento (opcional)",
    "Customer.EditCustomer": "Editar cliente",
    "Customer.Email": "Correo",
    "Customer.EnableTenantCurrencyBeforeSaving": "Habilite una moneda en la configuración del tenant antes de guardar el cliente.",
    "Customer.LedgerHelp": "El mayor de cliente está disponible en informes contables con filtro de cliente.",
    "Customer.Loading": "Cargando...",
    "Customer.LoadingCustomer": "Cargando cliente...",
    "Customer.Name": "Nombre",
    "Customer.NewCustomer": "Nuevo cliente",
    "Customer.NoTenantCurrencyEnabled": "No hay moneda del tenant habilitada",
    "Customer.OpenCustomerLedgerReport": "Abrir informe de mayor de cliente",
    "Customer.PaymentTerms": "Condiciones de pago",
    "Customer.PaymentTermsExample": "p. ej. 30 días",
    "Customer.Phone": "Teléfono",
    "Customer.PortalAccessEnabled": "Acceso al portal habilitado",
    "Customer.Primary": "Principal",
    "Customer.ReasonForReassignment": "Motivo de reasignación",
    "Customer.SalesmanOptional": "Vendedor (opcional)",
    "Customer.SalesmanTransferHelp": "La reasignación requiere un nuevo vendedor y un motivo. Cada transferencia queda en auditoría.",
    "Customer.SaveCustomer": "Guardar cliente",
    "Customer.ShippingAddress": "Dirección de envío",
    "Customer.Tab.addresses": "Direcciones",
    "Customer.Tab.contacts": "Contactos",
    "Customer.Tab.credit": "Crédito",
    "Customer.Tab.documents": "Documentos",
    "Customer.Tab.main": "Principal",
    "Customer.Transfer": "Transferir",
    "Customer.Type": "Tipo",
    "Customer.Unassigned": "Sin asignar",
    "Customer.UseSalesmanTransfer": "Use la transferencia autorizada de vendedor para cambiar esta asignación.",
    "Customer.ViewCustomer": "Ver cliente"
  },
  "zh-CN": {
    "Common.Actions": "操作",
    "Common.Active": "启用",
    "Common.Continue": "继续",
    "Common.Delete": "删除",
    "Common.Edit": "编辑",
    "Common.Remove": "移除",
    "Common.Review": "检查",
    "Common.Saving": "正在保存...",
    "Common.Select": "选择",
    "Common.Status": "状态",
    "Page.Title.Customers": "客户",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "客户主数据，包含信用控制和门户访问。",
    "Page.Title.CreateCustomer": "创建客户",
    "Page.Description.CreateCustomerProfileAndControls": "创建客户资料和控制项。",
    "Page.Title.EditCustomer": "编辑客户",
    "Page.Description.UpdateCustomerMasterData": "更新客户主数据。",
    "Customer.AddAddress": "添加地址",
    "Customer.AddContact": "添加联系人",
    "Customer.Address": "地址",
    "Customer.AuthorizedSalesmanTransfer": "授权销售员转移",
    "Customer.BillingAddress": "账单地址",
    "Customer.By": "由",
    "Customer.City": "城市",
    "Customer.Code": "代码",
    "Customer.ConfirmCustomerCurrency": "确认客户币种",
    "Customer.ContactName": "联系人姓名",
    "Customer.ContactPerson": "联系人",
    "Customer.Country": "国家",
    "Customer.CreditLimit": "信用额度",
    "Customer.CurrencyCannotChangeConfirm": "客户创建后不能更改客户币种。是否继续？",
    "Customer.CurrencyLockedAfterCreation": "客户币种创建后锁定。",
    "Customer.CustomerCode": "客户代码",
    "Customer.CustomerName": "客户名称",
    "Customer.CustomerType": "客户类型",
    "Customer.Default": "默认",
    "Customer.DefaultCurrency": "默认币种",
    "Customer.DeleteCustomer": "删除客户",
    "Customer.DeleteCustomerQuestion": "删除客户？",
    "Customer.Designation": "职务",
    "Customer.DocumentDisplayNameOptional": "文档显示名称（可选）",
    "Customer.EditCustomer": "编辑客户",
    "Customer.Email": "电子邮件",
    "Customer.EnableTenantCurrencyBeforeSaving": "保存客户前请在租户币种设置中启用币种。",
    "Customer.LedgerHelp": "客户分类账可通过会计报表中的客户筛选查看。",
    "Customer.Loading": "正在加载...",
    "Customer.LoadingCustomer": "正在加载客户...",
    "Customer.Name": "名称",
    "Customer.NewCustomer": "新客户",
    "Customer.NoTenantCurrencyEnabled": "未启用租户币种",
    "Customer.OpenCustomerLedgerReport": "打开客户分类账报表",
    "Customer.PaymentTerms": "付款条件",
    "Customer.PaymentTermsExample": "例如 30 天",
    "Customer.Phone": "电话",
    "Customer.PortalAccessEnabled": "门户访问已启用",
    "Customer.Primary": "主要",
    "Customer.ReasonForReassignment": "重新分配原因",
    "Customer.SalesmanOptional": "销售员（可选）",
    "Customer.SalesmanTransferHelp": "重新分配需要新的销售员和原因。每次转移都会保留在审计历史中。",
    "Customer.SaveCustomer": "保存客户",
    "Customer.ShippingAddress": "送货地址",
    "Customer.Tab.addresses": "地址",
    "Customer.Tab.contacts": "联系人",
    "Customer.Tab.credit": "信用",
    "Customer.Tab.documents": "文档",
    "Customer.Tab.main": "主要",
    "Customer.Transfer": "转移",
    "Customer.Type": "类型",
    "Customer.Unassigned": "未分配",
    "Customer.UseSalesmanTransfer": "使用授权销售员转移操作更改此分配。",
    "Customer.ViewCustomer": "查看客户"
  },
  "tr-TR": {
    "Common.Actions": "İşlemler",
    "Common.Active": "Aktif",
    "Common.Continue": "Devam et",
    "Common.Delete": "Sil",
    "Common.Edit": "Düzenle",
    "Common.Remove": "Kaldır",
    "Common.Review": "Gözden geçir",
    "Common.Saving": "Kaydediliyor...",
    "Common.Select": "Seç",
    "Common.Status": "Durum",
    "Page.Title.Customers": "Müşteriler",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "Kredi kontrolleri ve portal erişimi ile müşteri ana verisi.",
    "Page.Title.CreateCustomer": "Müşteri oluştur",
    "Page.Description.CreateCustomerProfileAndControls": "Müşteri profili ve kontrolleri oluştur.",
    "Page.Title.EditCustomer": "Müşteri düzenle",
    "Page.Description.UpdateCustomerMasterData": "Müşteri ana verisini güncelle.",
    "Customer.AddAddress": "Adres ekle",
    "Customer.AddContact": "Kişi ekle",
    "Customer.Address": "Adres",
    "Customer.AuthorizedSalesmanTransfer": "Yetkili satışçı transferi",
    "Customer.BillingAddress": "Fatura adresi",
    "Customer.By": "tarafından",
    "Customer.City": "Şehir",
    "Customer.Code": "Kod",
    "Customer.ConfirmCustomerCurrency": "Müşteri para birimini onayla",
    "Customer.ContactName": "Kişi adı",
    "Customer.ContactPerson": "İlgili kişi",
    "Customer.Country": "Ülke",
    "Customer.CreditLimit": "Kredi limiti",
    "Customer.CurrencyCannotChangeConfirm": "Müşteri oluşturulduktan sonra müşteri para birimi değiştirilemez. Devam etmek istiyor musunuz?",
    "Customer.CurrencyLockedAfterCreation": "Müşteri para birimi oluşturulduktan sonra kilitlenir.",
    "Customer.CustomerCode": "Müşteri kodu",
    "Customer.CustomerName": "Müşteri adı",
    "Customer.CustomerType": "Müşteri türü",
    "Customer.Default": "Varsayılan",
    "Customer.DefaultCurrency": "Varsayılan para birimi",
    "Customer.DeleteCustomer": "Müşteri sil",
    "Customer.DeleteCustomerQuestion": "Müşteri silinsin mi?",
    "Customer.Designation": "Unvan",
    "Customer.DocumentDisplayNameOptional": "Belge görünen adı (isteğe bağlı)",
    "Customer.EditCustomer": "Müşteri düzenle",
    "Customer.Email": "E-posta",
    "Customer.EnableTenantCurrencyBeforeSaving": "Müşteriyi kaydetmeden önce kiracı para birimi ayarında bir para birimi etkinleştirin.",
    "Customer.LedgerHelp": "Müşteri ekstresi muhasebe raporlarında müşteri filtresi ile kullanılabilir.",
    "Customer.Loading": "Yükleniyor...",
    "Customer.LoadingCustomer": "Müşteri yükleniyor...",
    "Customer.Name": "Ad",
    "Customer.NewCustomer": "Yeni müşteri",
    "Customer.NoTenantCurrencyEnabled": "Etkin kiracı para birimi yok",
    "Customer.OpenCustomerLedgerReport": "Müşteri ekstresi raporunu aç",
    "Customer.PaymentTerms": "Ödeme şartları",
    "Customer.PaymentTermsExample": "örn. 30 Gün",
    "Customer.Phone": "Telefon",
    "Customer.PortalAccessEnabled": "Portal erişimi etkin",
    "Customer.Primary": "Birincil",
    "Customer.ReasonForReassignment": "Yeniden atama nedeni",
    "Customer.SalesmanOptional": "Satışçı (isteğe bağlı)",
    "Customer.SalesmanTransferHelp": "Yeniden atama için yeni satışçı ve neden gerekir. Her transfer denetim geçmişinde tutulur.",
    "Customer.SaveCustomer": "Müşteri kaydet",
    "Customer.ShippingAddress": "Teslimat adresi",
    "Customer.Tab.addresses": "Adresler",
    "Customer.Tab.contacts": "Kişiler",
    "Customer.Tab.credit": "Kredi",
    "Customer.Tab.documents": "Belgeler",
    "Customer.Tab.main": "Ana",
    "Customer.Transfer": "Transfer et",
    "Customer.Type": "Tür",
    "Customer.Unassigned": "Atanmamış",
    "Customer.UseSalesmanTransfer": "Bu atamayı değiştirmek için yetkili satışçı transferini kullanın.",
    "Customer.ViewCustomer": "Müşteri görüntüle"
  },
  "pt-PT": {
    "Common.Actions": "Ações",
    "Common.Active": "Ativo",
    "Common.Continue": "Continuar",
    "Common.Delete": "Eliminar",
    "Common.Edit": "Editar",
    "Common.Remove": "Remover",
    "Common.Review": "Rever",
    "Common.Saving": "A guardar...",
    "Common.Select": "Selecionar",
    "Common.Status": "Estado",
    "Page.Title.Customers": "Clientes",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "Cadastro de clientes com controlos de crédito e acesso ao portal.",
    "Page.Title.CreateCustomer": "Criar cliente",
    "Page.Description.CreateCustomerProfileAndControls": "Criar perfil e controlos do cliente.",
    "Page.Title.EditCustomer": "Editar cliente",
    "Page.Description.UpdateCustomerMasterData": "Atualizar dados mestre do cliente.",
    "Customer.AddAddress": "Adicionar endereço",
    "Customer.AddContact": "Adicionar contacto",
    "Customer.Address": "Endereço",
    "Customer.AuthorizedSalesmanTransfer": "Transferência autorizada de vendedor",
    "Customer.BillingAddress": "Morada de faturação",
    "Customer.By": "por",
    "Customer.City": "Cidade",
    "Customer.Code": "Código",
    "Customer.ConfirmCustomerCurrency": "Confirmar moeda do cliente",
    "Customer.ContactName": "Nome do contacto",
    "Customer.ContactPerson": "Pessoa de contacto",
    "Customer.Country": "País",
    "Customer.CreditLimit": "Limite de crédito",
    "Customer.CurrencyCannotChangeConfirm": "A moeda do cliente não pode ser alterada após a criação. Deseja continuar?",
    "Customer.CurrencyLockedAfterCreation": "A moeda do cliente fica bloqueada após criação.",
    "Customer.CustomerCode": "Código do cliente",
    "Customer.CustomerName": "Nome do cliente",
    "Customer.CustomerType": "Tipo de cliente",
    "Customer.Default": "Predefinido",
    "Customer.DefaultCurrency": "Moeda padrão",
    "Customer.DeleteCustomer": "Eliminar cliente",
    "Customer.DeleteCustomerQuestion": "Eliminar cliente?",
    "Customer.Designation": "Cargo",
    "Customer.DocumentDisplayNameOptional": "Nome visível do documento (opcional)",
    "Customer.EditCustomer": "Editar cliente",
    "Customer.Email": "Email",
    "Customer.EnableTenantCurrencyBeforeSaving": "Ative uma moeda na configuração do tenant antes de guardar o cliente.",
    "Customer.LedgerHelp": "O razão do cliente está disponível nos relatórios contabilísticos com filtro de cliente.",
    "Customer.Loading": "A carregar...",
    "Customer.LoadingCustomer": "A carregar cliente...",
    "Customer.Name": "Nome",
    "Customer.NewCustomer": "Novo cliente",
    "Customer.NoTenantCurrencyEnabled": "Nenhuma moeda do tenant ativa",
    "Customer.OpenCustomerLedgerReport": "Abrir relatório de razão do cliente",
    "Customer.PaymentTerms": "Condições de pagamento",
    "Customer.PaymentTermsExample": "ex.: 30 dias",
    "Customer.Phone": "Telefone",
    "Customer.PortalAccessEnabled": "Acesso ao portal ativo",
    "Customer.Primary": "Principal",
    "Customer.ReasonForReassignment": "Motivo da reatribuição",
    "Customer.SalesmanOptional": "Vendedor (opcional)",
    "Customer.SalesmanTransferHelp": "A reatribuição requer novo vendedor e motivo. Cada transferência fica no histórico de auditoria.",
    "Customer.SaveCustomer": "Guardar cliente",
    "Customer.ShippingAddress": "Morada de envio",
    "Customer.Tab.addresses": "Endereços",
    "Customer.Tab.contacts": "Contactos",
    "Customer.Tab.credit": "Crédito",
    "Customer.Tab.documents": "Documentos",
    "Customer.Tab.main": "Principal",
    "Customer.Transfer": "Transferir",
    "Customer.Type": "Tipo",
    "Customer.Unassigned": "Não atribuído",
    "Customer.UseSalesmanTransfer": "Use a transferência autorizada de vendedor para alterar esta atribuição.",
    "Customer.ViewCustomer": "Ver cliente"
  },
  "ru-RU": {
    "Common.Actions": "Действия",
    "Common.Active": "Активно",
    "Common.Continue": "Продолжить",
    "Common.Delete": "Удалить",
    "Common.Edit": "Изменить",
    "Common.Remove": "Удалить",
    "Common.Review": "Проверить",
    "Common.Saving": "Сохранение...",
    "Common.Select": "Выбрать",
    "Common.Status": "Статус",
    "Page.Title.Customers": "Клиенты",
    "Page.Description.CustomerMasterWithCreditControlsAndPortalAccess": "Справочник клиентов с кредитным контролем и доступом к порталу.",
    "Page.Title.CreateCustomer": "Создать клиента",
    "Page.Description.CreateCustomerProfileAndControls": "Создать профиль клиента и настройки.",
    "Page.Title.EditCustomer": "Изменить клиента",
    "Page.Description.UpdateCustomerMasterData": "Обновить данные клиента.",
    "Customer.AddAddress": "Добавить адрес",
    "Customer.AddContact": "Добавить контакт",
    "Customer.Address": "Адрес",
    "Customer.AuthorizedSalesmanTransfer": "Авторизованная передача менеджера",
    "Customer.BillingAddress": "Адрес выставления счета",
    "Customer.By": "от",
    "Customer.City": "Город",
    "Customer.Code": "Код",
    "Customer.ConfirmCustomerCurrency": "Подтвердить валюту клиента",
    "Customer.ContactName": "Имя контакта",
    "Customer.ContactPerson": "Контактное лицо",
    "Customer.Country": "Страна",
    "Customer.CreditLimit": "Кредитный лимит",
    "Customer.CurrencyCannotChangeConfirm": "После создания клиента валюту изменить нельзя. Продолжить?",
    "Customer.CurrencyLockedAfterCreation": "Валюта клиента блокируется после создания.",
    "Customer.CustomerCode": "Код клиента",
    "Customer.CustomerName": "Название клиента",
    "Customer.CustomerType": "Тип клиента",
    "Customer.Default": "По умолчанию",
    "Customer.DefaultCurrency": "Валюта по умолчанию",
    "Customer.DeleteCustomer": "Удалить клиента",
    "Customer.DeleteCustomerQuestion": "Удалить клиента?",
    "Customer.Designation": "Должность",
    "Customer.DocumentDisplayNameOptional": "Отображаемое имя документа (необязательно)",
    "Customer.EditCustomer": "Изменить клиента",
    "Customer.Email": "Email",
    "Customer.EnableTenantCurrencyBeforeSaving": "Перед сохранением клиента включите валюту в настройках арендатора.",
    "Customer.LedgerHelp": "Книга клиента доступна в бухгалтерских отчетах с фильтром клиента.",
    "Customer.Loading": "Загрузка...",
    "Customer.LoadingCustomer": "Загрузка клиента...",
    "Customer.Name": "Название",
    "Customer.NewCustomer": "Новый клиент",
    "Customer.NoTenantCurrencyEnabled": "Валюта арендатора не включена",
    "Customer.OpenCustomerLedgerReport": "Открыть отчет книги клиента",
    "Customer.PaymentTerms": "Условия оплаты",
    "Customer.PaymentTermsExample": "например 30 дней",
    "Customer.Phone": "Телефон",
    "Customer.PortalAccessEnabled": "Доступ к порталу включен",
    "Customer.Primary": "Основной",
    "Customer.ReasonForReassignment": "Причина переназначения",
    "Customer.SalesmanOptional": "Менеджер (необязательно)",
    "Customer.SalesmanTransferHelp": "Переназначение требует нового менеджера и причину. Каждая передача сохраняется в аудите.",
    "Customer.SaveCustomer": "Сохранить клиента",
    "Customer.ShippingAddress": "Адрес доставки",
    "Customer.Tab.addresses": "Адреса",
    "Customer.Tab.contacts": "Контакты",
    "Customer.Tab.credit": "Кредит",
    "Customer.Tab.documents": "Документы",
    "Customer.Tab.main": "Основное",
    "Customer.Transfer": "Передать",
    "Customer.Type": "Тип",
    "Customer.Unassigned": "Не назначено",
    "Customer.UseSalesmanTransfer": "Используйте авторизованную передачу менеджера для изменения назначения.",
    "Customer.ViewCustomer": "Просмотреть клиента"
  }
};
