export const loginLanguageFallbacks: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Login.SignInTitle": "تسجيل الدخول إلى Freight ERP",
    "Login.SignInSubtitle": "الوصول إلى مساحة عمل المستأجر وعمليات الفروع والبوابات والضوابط المالية.",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "منصة عمليات الشحن",
    "Login.PlatformSubtitle": "تحكم آمن عبر إعدادات المستأجر والشحنات والمالية والتدقيق.",
    "Login.PlatformTenantScope": "وصول محدد حسب المستأجر والفرع",
    "Login.PlatformPermissionScope": "إجراءات محكومة بالأدوار والصلاحيات",
    "Login.LanguageHelp": "تستخدم رسائل النظام والتسميات والتقارير وملفات PDF والتنسيق اللغة المحددة. الإنجليزية هي اللغة الاحتياطية.",
    "Login.SecurityNote": "محمي بعزل المستأجر ونطاق الفرع وسياسات الصلاحيات.",
    "Login.NeedHelp": "هل تحتاج إلى مساعدة؟",
    "Login.Continue": "المتابعة إلى ERP"
  },
  "hi-IN": {
    "Login.SignInTitle": "Freight ERP में साइन इन करें",
    "Login.SignInSubtitle": "अपने टेनेंट कार्यक्षेत्र, शाखा संचालन, पोर्टल और वित्त नियंत्रण तक पहुंचें.",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "फॉरवर्डिंग ऑपरेशंस प्लेटफॉर्म",
    "Login.PlatformSubtitle": "टेनेंट सेटअप, शिपमेंट, वित्त और ऑडिट पर सुरक्षित नियंत्रण.",
    "Login.PlatformTenantScope": "टेनेंट और शाखा आधारित पहुंच",
    "Login.PlatformPermissionScope": "भूमिका और अनुमति नियंत्रित कार्य",
    "Login.LanguageHelp": "सर्वर संदेश, लेबल, रिपोर्ट, PDF और फॉर्मेटिंग चयनित भाषा का उपयोग करते हैं. अंग्रेज़ी fallback है.",
    "Login.SecurityNote": "टेनेंट आइसोलेशन, शाखा दायरा और अनुमति नीतियों द्वारा सुरक्षित.",
    "Login.NeedHelp": "मदद चाहिए?",
    "Login.Continue": "ERP पर जाएं"
  },
  "fr-FR": {
    "Login.SignInTitle": "Se connecter à Freight ERP",
    "Login.SignInSubtitle": "Accédez à votre espace locataire, aux opérations de branche, aux portails et aux contrôles financiers.",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "Plateforme d'opérations de transit",
    "Login.PlatformSubtitle": "Contrôle sécurisé de la configuration locataire, des expéditions, de la finance et de l'audit.",
    "Login.PlatformTenantScope": "Accès limité au locataire et à la branche",
    "Login.PlatformPermissionScope": "Actions contrôlées par rôles et permissions",
    "Login.LanguageHelp": "Les messages serveur, libellés, rapports, PDF et formats utilisent la langue sélectionnée. L'anglais est la langue de repli.",
    "Login.SecurityNote": "Protégé par l'isolation du locataire, le périmètre de branche et les politiques d'autorisation.",
    "Login.NeedHelp": "Besoin d'aide ?",
    "Login.Continue": "Continuer vers ERP"
  },
  "es-ES": {
    "Login.SignInTitle": "Iniciar sesión en Freight ERP",
    "Login.SignInSubtitle": "Acceda a su espacio de tenant, operaciones de sucursal, portales y controles financieros.",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "Plataforma de operaciones de forwarding",
    "Login.PlatformSubtitle": "Control seguro de configuración de tenant, envíos, finanzas y auditoría.",
    "Login.PlatformTenantScope": "Acceso por tenant y sucursal",
    "Login.PlatformPermissionScope": "Acciones controladas por roles y permisos",
    "Login.LanguageHelp": "Los mensajes del servidor, etiquetas, informes, PDF y formatos usan el idioma seleccionado. El inglés es el respaldo.",
    "Login.SecurityNote": "Protegido por aislamiento de tenant, alcance de sucursal y políticas de permisos.",
    "Login.NeedHelp": "¿Necesita ayuda?",
    "Login.Continue": "Continuar a ERP"
  },
  "zh-CN": {
    "Login.SignInTitle": "登录 Freight ERP",
    "Login.SignInSubtitle": "访问您的租户工作区、分支操作、门户和财务控制。",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "货运代理运营平台",
    "Login.PlatformSubtitle": "安全控制租户设置、发运、财务和审计。",
    "Login.PlatformTenantScope": "按租户和分支限定访问",
    "Login.PlatformPermissionScope": "按角色和权限控制操作",
    "Login.LanguageHelp": "服务器消息、标签、报表、PDF 和格式使用所选语言。英语作为备用语言。",
    "Login.SecurityNote": "受租户隔离、分支范围和权限策略保护。",
    "Login.NeedHelp": "需要帮助？",
    "Login.Continue": "进入 ERP"
  },
  "tr-TR": {
    "Login.SignInTitle": "Freight ERP'ye giriş yap",
    "Login.SignInSubtitle": "Kiracı çalışma alanınıza, şube operasyonlarına, portallara ve finans kontrollerine erişin.",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "Forwarding operasyon platformu",
    "Login.PlatformSubtitle": "Kiracı kurulumu, sevkiyatlar, finans ve denetim üzerinde güvenli kontrol.",
    "Login.PlatformTenantScope": "Kiracı ve şube kapsamlı erişim",
    "Login.PlatformPermissionScope": "Rol ve izin kontrollü işlemler",
    "Login.LanguageHelp": "Sunucu mesajları, etiketler, raporlar, PDF'ler ve biçimlendirme seçilen dili kullanır. İngilizce yedek dildir.",
    "Login.SecurityNote": "Kiracı izolasyonu, şube kapsamı ve izin politikaları ile korunur.",
    "Login.NeedHelp": "Yardıma mı ihtiyacınız var?",
    "Login.Continue": "ERP'ye devam et"
  },
  "pt-PT": {
    "Login.SignInTitle": "Iniciar sessão no Freight ERP",
    "Login.SignInSubtitle": "Aceda ao espaço do tenant, operações da filial, portais e controlos financeiros.",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "Plataforma de operações de forwarding",
    "Login.PlatformSubtitle": "Controlo seguro da configuração do tenant, envios, finanças e auditoria.",
    "Login.PlatformTenantScope": "Acesso por tenant e filial",
    "Login.PlatformPermissionScope": "Ações controladas por funções e permissões",
    "Login.LanguageHelp": "As mensagens do servidor, etiquetas, relatórios, PDF e formatação usam o idioma selecionado. O inglês é o fallback.",
    "Login.SecurityNote": "Protegido por isolamento do tenant, âmbito da filial e políticas de permissões.",
    "Login.NeedHelp": "Precisa de ajuda?",
    "Login.Continue": "Continuar para ERP"
  },
  "ru-RU": {
    "Login.SignInTitle": "Войти в Freight ERP",
    "Login.SignInSubtitle": "Доступ к рабочей области арендатора, операциям филиалов, порталам и финансовому контролю.",
    "Login.PlatformEyebrow": "Freight ERP",
    "Login.PlatformTitle": "Платформа экспедиторских операций",
    "Login.PlatformSubtitle": "Безопасный контроль настроек арендатора, отправок, финансов и аудита.",
    "Login.PlatformTenantScope": "Доступ в рамках арендатора и филиала",
    "Login.PlatformPermissionScope": "Действия под контролем ролей и разрешений",
    "Login.LanguageHelp": "Серверные сообщения, метки, отчеты, PDF и форматирование используют выбранный язык. Английский используется как резервный.",
    "Login.SecurityNote": "Защищено изоляцией арендатора, областью филиала и политиками разрешений.",
    "Login.NeedHelp": "Нужна помощь?",
    "Login.Continue": "Продолжить в ERP"
  }
};
