export const menuLocalizationFallbacks: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Navigation.accounting.Label": "المحاسبة",
    "Navigation.administration.Item.employees.Label": "الموظفون",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "الإشعار السجل",
    "Navigation.administration.Item.notification-templates.Label": "الإشعار Templates",
    "Navigation.administration.Item.permission-matrix.Label": "الصلاحية المصفوفة",
    "Navigation.administration.Item.roles.Label": "الأدوار",
    "Navigation.administration.Item.users.Label": "المستخدمون",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request السجلات",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "البريد الإلكتروني السجلات",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export السجلات",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access السجلات",
    "Navigation.audit-logs.Item.audit-financial.Label": "مالي التدقيق",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login السجل",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print السجلات",
    "Navigation.audit-logs.Item.audit-report-access.Label": "التقرير Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "المستخدم Activity",
    "Navigation.audit-logs.Item.audit.Label": "التدقيق السجل بحث",
    "Navigation.audit-logs.Label": "سجلات التدقيق",
    "Navigation.dashboard.Item.dashboard.Label": "لوحة التحكم",
    "Navigation.dashboard.Label": "لوحة التحكم",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "المستندات",
    "Navigation.finance.Item.commissions.Label": "الوكيل العمولات",
    "Navigation.finance.Item.credit-debit-notes.Label": "دائن / مدين الإشعارات",
    "Navigation.finance.Item.finance.Label": "المالية Workbench",
    "Navigation.finance.Item.invoices.Label": "الفواتير",
    "Navigation.finance.Item.payments.Label": "مدفوعات الموردين",
    "Navigation.finance.Item.receipts.Label": "إيصالات العملاء",
    "Navigation.finance.Item.vendor-bills.Label": "فواتير الموردين",
    "Navigation.finance.Label": "المالية",
    "Navigation.masters.Item.agents.Label": "الوكلاء",
    "Navigation.masters.Item.carriers.Label": "الناقلون",
    "Navigation.masters.Item.customers.Label": "العملاء",
    "Navigation.masters.Item.vendors.Label": "الموردون",
    "Navigation.masters.Label": "البيانات الرئيسية",
    "Navigation.operations.Item.goods-receipt.Label": "استلام البضائع",
    "Navigation.operations.Item.pickup.Label": "الاستلام",
    "Navigation.operations.Label": "العمليات",
    "Navigation.portals.Item.agent-portal.Label": "الوكيل البوابة",
    "Navigation.portals.Item.customer-portal.Label": "العميل البوابة",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "عروض الأسعار",
    "Navigation.rate-quotation.Item.rate-master.Label": "السعر رئيسي",
    "Navigation.rate-quotation.Label": "السعر & عرض السعر",
    "Navigation.reports.Item.reports-balance-sheet.Label": "الميزانية العمومية",
    "Navigation.reports.Item.reports-bank-book.Label": "دفتر البنك",
    "Navigation.reports.Item.reports-cash-book.Label": "دفتر الصندوق",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "ربح/خسارة العملة",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "إعادة تقييم العملة",
    "Navigation.reports.Item.reports-customer-ledger.Label": "دفتر أستاذ العميل",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "مستحقات العملاء",
    "Navigation.reports.Item.reports-general-ledger.Label": "دفتر الأستاذ العام",
    "Navigation.reports.Item.reports-ledger.Label": "تقرير دفتر الأستاذ",
    "Navigation.reports.Item.reports-op-ageing.Label": "تقادم الشحنات",
    "Navigation.reports.Item.reports-op-air.Label": "تقرير الشحن الجوي",
    "Navigation.reports.Item.reports-op-container.Label": "تقرير الحاويات",
    "Navigation.reports.Item.reports-op-courier.Label": "تقرير البريد السريع",
    "Navigation.reports.Item.reports-op-customs.Label": "تقرير الجمارك",
    "Navigation.reports.Item.reports-op-direct.Label": "تقرير الشحنات المباشرة",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "تقرير استلام البضائع",
    "Navigation.reports.Item.reports-op-house.Label": "تقرير الشحنات الفرعية",
    "Navigation.reports.Item.reports-op-master.Label": "تقرير الشحنات الرئيسية",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "تقرير الفواتير المعلقة",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "تقرير المستندات المعلقة",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "تقرير إثبات التسليم المعلق",
    "Navigation.reports.Item.reports-op-pickup.Label": "تقرير الاستلام",
    "Navigation.reports.Item.reports-op-quotation.Label": "تقرير عروض الأسعار",
    "Navigation.reports.Item.reports-op-road.Label": "تقرير الشحن البري",
    "Navigation.reports.Item.reports-op-sea.Label": "تقرير الشحن البحري",
    "Navigation.reports.Item.reports-op-unbilled.Label": "الشحنات غير المفوترة",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "تقرير مخزون المستودع",
    "Navigation.reports.Item.reports-profit-agent.Label": "ربح الوكيل",
    "Navigation.reports.Item.reports-profit-branch.Label": "ربح الفرع",
    "Navigation.reports.Item.reports-profit-customer.Label": "ربح العميل",
    "Navigation.reports.Item.reports-profit-destination.Label": "ربح الوجهة",
    "Navigation.reports.Item.reports-profit-loss.Label": "الأرباح والخسائر",
    "Navigation.reports.Item.reports-profit-route.Label": "ربح المسار",
    "Navigation.reports.Item.reports-profit-salesman.Label": "ربح مندوب المبيعات",
    "Navigation.reports.Item.reports-profit-shipment.Label": "ربح الشحنة",
    "Navigation.reports.Item.reports-soa.Label": "كشف الحساب",
    "Navigation.reports.Item.reports-tax-report.Label": "تقرير الضريبة",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "أرباح وخسائر التداول",
    "Navigation.reports.Item.reports-trial-balance.Label": "ميزان المراجعة",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "دفتر أستاذ المورد",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "مستحقات الموردين",
    "Navigation.reports.Label": "التقارير",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "الفرع الإعدادات",
    "Navigation.settings.Item.currency-setup.Label": "المستأجر العملات",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "المستأجر اللغات",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering الإعدادات",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "المستأجر الإعدادات",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "الإعدادات",
    "Navigation.shipments.Item.customs-jobs.Label": "الوظائف",
    "Navigation.shipments.Item.customs.Label": "الجمارك التخليص",
    "Navigation.shipments.Item.direct-shipments.Label": "الشحنات المباشرة",
    "Navigation.shipments.Item.house-shipments.Label": "الشحنات الفرعية",
    "Navigation.shipments.Item.master-shipments.Label": "الشحنات الرئيسية",
    "Navigation.shipments.Label": "الشحنات",
  },
  "es-ES": {
    "Navigation.accounting.Label": "Contabilidad",
    "Navigation.administration.Item.employees.Label": "Empleados",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "Notificación Historial",
    "Navigation.administration.Item.notification-templates.Label": "Notificación Templates",
    "Navigation.administration.Item.permission-matrix.Label": "Permiso Matriz",
    "Navigation.administration.Item.roles.Label": "Roles",
    "Navigation.administration.Item.users.Label": "Usuarios",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request Registros",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "Correo Registros",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export Registros",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access Registros",
    "Navigation.audit-logs.Item.audit-financial.Label": "Financiero Auditoría",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login Historial",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print Registros",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Reporte Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Usuario Activity",
    "Navigation.audit-logs.Item.audit.Label": "Auditoría Registro Buscar",
    "Navigation.audit-logs.Label": "Registros de auditoría",
    "Navigation.dashboard.Item.dashboard.Label": "Panel",
    "Navigation.dashboard.Label": "Panel",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "Documentos",
    "Navigation.finance.Item.commissions.Label": "Agente Comisiones",
    "Navigation.finance.Item.credit-debit-notes.Label": "Crédito / Débito Notas",
    "Navigation.finance.Item.finance.Label": "Finanzas Workbench",
    "Navigation.finance.Item.invoices.Label": "Facturas",
    "Navigation.finance.Item.payments.Label": "Pagos a proveedores",
    "Navigation.finance.Item.receipts.Label": "Recibos de clientes",
    "Navigation.finance.Item.vendor-bills.Label": "Facturas de proveedor",
    "Navigation.finance.Label": "Finanzas",
    "Navigation.masters.Item.agents.Label": "Agentes",
    "Navigation.masters.Item.carriers.Label": "Transportistas",
    "Navigation.masters.Item.customers.Label": "Clientes",
    "Navigation.masters.Item.vendors.Label": "Proveedores",
    "Navigation.masters.Label": "Maestros",
    "Navigation.operations.Item.goods-receipt.Label": "Recepción de mercancía",
    "Navigation.operations.Item.pickup.Label": "Recogida",
    "Navigation.operations.Label": "Operaciones",
    "Navigation.portals.Item.agent-portal.Label": "Agente Portal",
    "Navigation.portals.Item.customer-portal.Label": "Cliente Portal",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "Cotizaciones",
    "Navigation.rate-quotation.Item.rate-master.Label": "Tarifa Maestro",
    "Navigation.rate-quotation.Label": "Tarifa & Cotización",
    "Navigation.reports.Item.reports-balance-sheet.Label": "Balance general",
    "Navigation.reports.Item.reports-bank-book.Label": "Libro de banco",
    "Navigation.reports.Item.reports-cash-book.Label": "Libro de caja",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "Ganancia/pérdida cambiaria",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "Revaluación de moneda",
    "Navigation.reports.Item.reports-customer-ledger.Label": "Mayor de cliente",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "Pendiente de clientes",
    "Navigation.reports.Item.reports-general-ledger.Label": "Libro mayor general",
    "Navigation.reports.Item.reports-ledger.Label": "Reporte de mayor",
    "Navigation.reports.Item.reports-op-ageing.Label": "Antigüedad de embarques",
    "Navigation.reports.Item.reports-op-air.Label": "Reporte de carga aérea",
    "Navigation.reports.Item.reports-op-container.Label": "Reporte de contenedores",
    "Navigation.reports.Item.reports-op-courier.Label": "Reporte de courier",
    "Navigation.reports.Item.reports-op-customs.Label": "Reporte de aduana",
    "Navigation.reports.Item.reports-op-direct.Label": "Reporte de embarques directos",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "Reporte de recepción de mercancía",
    "Navigation.reports.Item.reports-op-house.Label": "Reporte de embarques house",
    "Navigation.reports.Item.reports-op-master.Label": "Reporte de embarques master",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "Reporte de facturas pendientes",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "Reporte de documentos pendientes",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "Reporte POD pendiente",
    "Navigation.reports.Item.reports-op-pickup.Label": "Reporte de recogida",
    "Navigation.reports.Item.reports-op-quotation.Label": "Reporte de cotizaciones",
    "Navigation.reports.Item.reports-op-road.Label": "Reporte de carga terrestre",
    "Navigation.reports.Item.reports-op-sea.Label": "Reporte de carga marítima",
    "Navigation.reports.Item.reports-op-unbilled.Label": "Embarques no facturados",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "Reporte de stock de almacén",
    "Navigation.reports.Item.reports-profit-agent.Label": "Rentabilidad de agente",
    "Navigation.reports.Item.reports-profit-branch.Label": "Rentabilidad de sucursal",
    "Navigation.reports.Item.reports-profit-customer.Label": "Rentabilidad de cliente",
    "Navigation.reports.Item.reports-profit-destination.Label": "Rentabilidad de destino",
    "Navigation.reports.Item.reports-profit-loss.Label": "Pérdidas y ganancias",
    "Navigation.reports.Item.reports-profit-route.Label": "Rentabilidad de ruta",
    "Navigation.reports.Item.reports-profit-salesman.Label": "Rentabilidad de vendedor",
    "Navigation.reports.Item.reports-profit-shipment.Label": "Rentabilidad de embarque",
    "Navigation.reports.Item.reports-soa.Label": "Estado de cuenta",
    "Navigation.reports.Item.reports-tax-report.Label": "Reporte de impuestos",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "P&G comercial",
    "Navigation.reports.Item.reports-trial-balance.Label": "Balance de comprobación",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "Mayor de proveedor",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "Pendiente de proveedores",
    "Navigation.reports.Label": "Informes",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "Sucursal Configuración",
    "Navigation.settings.Item.currency-setup.Label": "Tenant Monedas",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "Tenant Idiomas",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering Configuración",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "Tenant Configuración",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "Configuración",
    "Navigation.shipments.Item.customs-jobs.Label": "Trabajos",
    "Navigation.shipments.Item.customs.Label": "Aduana Despacho",
    "Navigation.shipments.Item.direct-shipments.Label": "Embarques directos",
    "Navigation.shipments.Item.house-shipments.Label": "Embarques house",
    "Navigation.shipments.Item.master-shipments.Label": "Embarques master",
    "Navigation.shipments.Label": "Envíos",
  },
  "fr-FR": {
    "Navigation.accounting.Label": "Comptabilité",
    "Navigation.administration.Item.employees.Label": "Employés",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "Notification Historique",
    "Navigation.administration.Item.notification-templates.Label": "Notification Templates",
    "Navigation.administration.Item.permission-matrix.Label": "Permission Matrice",
    "Navigation.administration.Item.roles.Label": "Rôles",
    "Navigation.administration.Item.users.Label": "Utilisateurs",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request Journaux",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "E-mail Journaux",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export Journaux",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access Journaux",
    "Navigation.audit-logs.Item.audit-financial.Label": "Financier Audit",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login Historique",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print Journaux",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Rapport Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Utilisateur Activity",
    "Navigation.audit-logs.Item.audit.Label": "Audit Journal Recherche",
    "Navigation.audit-logs.Label": "Journaux d'audit",
    "Navigation.dashboard.Item.dashboard.Label": "Tableau de bord",
    "Navigation.dashboard.Label": "Tableau de bord",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "Documents",
    "Navigation.finance.Item.commissions.Label": "Agent Commissions",
    "Navigation.finance.Item.credit-debit-notes.Label": "Crédit / Débit Notes",
    "Navigation.finance.Item.finance.Label": "Finance Workbench",
    "Navigation.finance.Item.invoices.Label": "Factures",
    "Navigation.finance.Item.payments.Label": "Paiements fournisseurs",
    "Navigation.finance.Item.receipts.Label": "Encaissements clients",
    "Navigation.finance.Item.vendor-bills.Label": "Factures fournisseurs",
    "Navigation.finance.Label": "Finance",
    "Navigation.masters.Item.agents.Label": "Agents",
    "Navigation.masters.Item.carriers.Label": "Transporteurs",
    "Navigation.masters.Item.customers.Label": "Clients",
    "Navigation.masters.Item.vendors.Label": "Fournisseurs",
    "Navigation.masters.Label": "Référentiels",
    "Navigation.operations.Item.goods-receipt.Label": "Réception marchandises",
    "Navigation.operations.Item.pickup.Label": "Enlèvement",
    "Navigation.operations.Label": "Opérations",
    "Navigation.portals.Item.agent-portal.Label": "Agent Portail",
    "Navigation.portals.Item.customer-portal.Label": "Client Portail",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "Devis",
    "Navigation.rate-quotation.Item.rate-master.Label": "Tarif Master",
    "Navigation.rate-quotation.Label": "Tarif & Devis",
    "Navigation.reports.Item.reports-balance-sheet.Label": "Bilan",
    "Navigation.reports.Item.reports-bank-book.Label": "Livre de banque",
    "Navigation.reports.Item.reports-cash-book.Label": "Livre de caisse",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "Gain/perte de change",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "Réévaluation devise",
    "Navigation.reports.Item.reports-customer-ledger.Label": "Grand livre client",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "Encours clients",
    "Navigation.reports.Item.reports-general-ledger.Label": "Grand livre général",
    "Navigation.reports.Item.reports-ledger.Label": "Rapport grand livre",
    "Navigation.reports.Item.reports-op-ageing.Label": "Âge des expéditions",
    "Navigation.reports.Item.reports-op-air.Label": "Rapport fret aérien",
    "Navigation.reports.Item.reports-op-container.Label": "Rapport conteneurs",
    "Navigation.reports.Item.reports-op-courier.Label": "Rapport courrier",
    "Navigation.reports.Item.reports-op-customs.Label": "Rapport douane",
    "Navigation.reports.Item.reports-op-direct.Label": "Rapport expéditions directes",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "Rapport réception marchandises",
    "Navigation.reports.Item.reports-op-house.Label": "Rapport expéditions house",
    "Navigation.reports.Item.reports-op-master.Label": "Rapport expéditions master",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "Rapport factures en attente",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "Rapport documents en attente",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "Rapport POD en attente",
    "Navigation.reports.Item.reports-op-pickup.Label": "Rapport enlèvement",
    "Navigation.reports.Item.reports-op-quotation.Label": "Rapport des devis",
    "Navigation.reports.Item.reports-op-road.Label": "Rapport fret routier",
    "Navigation.reports.Item.reports-op-sea.Label": "Rapport fret maritime",
    "Navigation.reports.Item.reports-op-unbilled.Label": "Expéditions non facturées",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "Rapport stock entrepôt",
    "Navigation.reports.Item.reports-profit-agent.Label": "Profit agent",
    "Navigation.reports.Item.reports-profit-branch.Label": "Profit agence",
    "Navigation.reports.Item.reports-profit-customer.Label": "Profit client",
    "Navigation.reports.Item.reports-profit-destination.Label": "Profit destination",
    "Navigation.reports.Item.reports-profit-loss.Label": "Compte de résultat",
    "Navigation.reports.Item.reports-profit-route.Label": "Profit route",
    "Navigation.reports.Item.reports-profit-salesman.Label": "Profit commercial",
    "Navigation.reports.Item.reports-profit-shipment.Label": "Profit expédition",
    "Navigation.reports.Item.reports-soa.Label": "Relevé de compte",
    "Navigation.reports.Item.reports-tax-report.Label": "Rapport fiscal",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "P&L commercial",
    "Navigation.reports.Item.reports-trial-balance.Label": "Balance de vérification",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "Grand livre fournisseur",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "Encours fournisseurs",
    "Navigation.reports.Label": "Rapports",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "Agence Paramètres",
    "Navigation.settings.Item.currency-setup.Label": "Tenant Devises",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "Tenant Langues",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering Paramètres",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "Tenant Paramètres",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "Paramètres",
    "Navigation.shipments.Item.customs-jobs.Label": "Dossiers",
    "Navigation.shipments.Item.customs.Label": "Douane Dédouanement",
    "Navigation.shipments.Item.direct-shipments.Label": "Expéditions directes",
    "Navigation.shipments.Item.house-shipments.Label": "Expéditions house",
    "Navigation.shipments.Item.master-shipments.Label": "Expéditions master",
    "Navigation.shipments.Label": "Expéditions",
  },
  "hi-IN": {
    "Navigation.accounting.Label": "लेखा",
    "Navigation.administration.Item.employees.Label": "कर्मचारी",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "सूचना इतिहास",
    "Navigation.administration.Item.notification-templates.Label": "सूचना Templates",
    "Navigation.administration.Item.permission-matrix.Label": "अनुमति मैट्रिक्स",
    "Navigation.administration.Item.roles.Label": "भूमिकाएँ",
    "Navigation.administration.Item.users.Label": "यूज़र",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request लॉग",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "ईमेल लॉग",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export लॉग",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access लॉग",
    "Navigation.audit-logs.Item.audit-financial.Label": "वित्तीय ऑडिट",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login इतिहास",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print लॉग",
    "Navigation.audit-logs.Item.audit-report-access.Label": "रिपोर्ट Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "यूज़र Activity",
    "Navigation.audit-logs.Item.audit.Label": "ऑडिट लॉग खोज",
    "Navigation.audit-logs.Label": "ऑडिट लॉग",
    "Navigation.dashboard.Item.dashboard.Label": "डैशबोर्ड",
    "Navigation.dashboard.Label": "डैशबोर्ड",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "दस्तावेज़",
    "Navigation.finance.Item.commissions.Label": "एजेंट कमीशन",
    "Navigation.finance.Item.credit-debit-notes.Label": "क्रेडिट / डेबिट नोट",
    "Navigation.finance.Item.finance.Label": "वित्त Workbench",
    "Navigation.finance.Item.invoices.Label": "चालान",
    "Navigation.finance.Item.payments.Label": "वेंडर भुगतान",
    "Navigation.finance.Item.receipts.Label": "ग्राहक रसीदें",
    "Navigation.finance.Item.vendor-bills.Label": "वेंडर बिल",
    "Navigation.finance.Label": "वित्त",
    "Navigation.masters.Item.agents.Label": "एजेंट",
    "Navigation.masters.Item.carriers.Label": "कैरियर",
    "Navigation.masters.Item.customers.Label": "ग्राहक",
    "Navigation.masters.Item.vendors.Label": "विक्रेता",
    "Navigation.masters.Label": "मास्टर",
    "Navigation.operations.Item.goods-receipt.Label": "गुड्स रिसीट",
    "Navigation.operations.Item.pickup.Label": "पिकअप",
    "Navigation.operations.Label": "संचालन",
    "Navigation.portals.Item.agent-portal.Label": "एजेंट पोर्टल",
    "Navigation.portals.Item.customer-portal.Label": "ग्राहक पोर्टल",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "कोटेशन",
    "Navigation.rate-quotation.Item.rate-master.Label": "रेट मास्टर",
    "Navigation.rate-quotation.Label": "रेट & कोटेशन",
    "Navigation.reports.Item.reports-balance-sheet.Label": "बैलेंस शीट",
    "Navigation.reports.Item.reports-bank-book.Label": "बैंक बुक",
    "Navigation.reports.Item.reports-cash-book.Label": "कैश बुक",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "मुद्रा लाभ/हानि",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "मुद्रा पुनर्मूल्यांकन",
    "Navigation.reports.Item.reports-customer-ledger.Label": "ग्राहक लेजर",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "ग्राहक बकाया",
    "Navigation.reports.Item.reports-general-ledger.Label": "जनरल लेजर",
    "Navigation.reports.Item.reports-ledger.Label": "लेजर रिपोर्ट",
    "Navigation.reports.Item.reports-op-ageing.Label": "शिपमेंट एजिंग",
    "Navigation.reports.Item.reports-op-air.Label": "एयर फ्रेट रिपोर्ट",
    "Navigation.reports.Item.reports-op-container.Label": "कंटेनर रिपोर्ट",
    "Navigation.reports.Item.reports-op-courier.Label": "कूरियर रिपोर्ट",
    "Navigation.reports.Item.reports-op-customs.Label": "कस्टम्स रिपोर्ट",
    "Navigation.reports.Item.reports-op-direct.Label": "डायरेक्ट शिपमेंट रिपोर्ट",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "गुड्स रिसीट रिपोर्ट",
    "Navigation.reports.Item.reports-op-house.Label": "हाउस शिपमेंट रिपोर्ट",
    "Navigation.reports.Item.reports-op-master.Label": "मास्टर शिपमेंट रिपोर्ट",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "लंबित बिल रिपोर्ट",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "लंबित दस्तावेज़ रिपोर्ट",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "लंबित POD रिपोर्ट",
    "Navigation.reports.Item.reports-op-pickup.Label": "पिकअप रिपोर्ट",
    "Navigation.reports.Item.reports-op-quotation.Label": "कोटेशन रिपोर्ट",
    "Navigation.reports.Item.reports-op-road.Label": "रोड फ्रेट रिपोर्ट",
    "Navigation.reports.Item.reports-op-sea.Label": "सी फ्रेट रिपोर्ट",
    "Navigation.reports.Item.reports-op-unbilled.Label": "अनबिल्ड शिपमेंट",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "वेयरहाउस स्टॉक रिपोर्ट",
    "Navigation.reports.Item.reports-profit-agent.Label": "एजेंट लाभ",
    "Navigation.reports.Item.reports-profit-branch.Label": "शाखा लाभ",
    "Navigation.reports.Item.reports-profit-customer.Label": "ग्राहक लाभ",
    "Navigation.reports.Item.reports-profit-destination.Label": "गंतव्य लाभ",
    "Navigation.reports.Item.reports-profit-loss.Label": "लाभ और हानि",
    "Navigation.reports.Item.reports-profit-route.Label": "रूट लाभ",
    "Navigation.reports.Item.reports-profit-salesman.Label": "सेल्समैन लाभ",
    "Navigation.reports.Item.reports-profit-shipment.Label": "शिपमेंट लाभ",
    "Navigation.reports.Item.reports-soa.Label": "खाता विवरण",
    "Navigation.reports.Item.reports-tax-report.Label": "टैक्स रिपोर्ट",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "ट्रेडिंग पी एंड एल",
    "Navigation.reports.Item.reports-trial-balance.Label": "ट्रायल बैलेंस",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "वेंडर लेजर",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "वेंडर बकाया",
    "Navigation.reports.Label": "रिपोर्ट",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "शाखा सेटिंग्स",
    "Navigation.settings.Item.currency-setup.Label": "टेनेंट मुद्राएँ",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "टेनेंट भाषाएँ",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering सेटिंग्स",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "टेनेंट सेटिंग्स",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "सेटिंग्स",
    "Navigation.shipments.Item.customs-jobs.Label": "जॉब",
    "Navigation.shipments.Item.customs.Label": "कस्टम्स क्लीयरेंस",
    "Navigation.shipments.Item.direct-shipments.Label": "डायरेक्ट शिपमेंट",
    "Navigation.shipments.Item.house-shipments.Label": "हाउस शिपमेंट",
    "Navigation.shipments.Item.master-shipments.Label": "मास्टर शिपमेंट",
    "Navigation.shipments.Label": "शिपमेंट",
  },
  "pt-PT": {
    "Navigation.accounting.Label": "Contabilidade",
    "Navigation.administration.Item.employees.Label": "Funcionários",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "Notificação Histórico",
    "Navigation.administration.Item.notification-templates.Label": "Notificação Templates",
    "Navigation.administration.Item.permission-matrix.Label": "Permissão Matriz",
    "Navigation.administration.Item.roles.Label": "Funções",
    "Navigation.administration.Item.users.Label": "Utilizadores",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request Registos",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "Email Registos",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export Registos",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access Registos",
    "Navigation.audit-logs.Item.audit-financial.Label": "Financeiro Auditoria",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login Histórico",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print Registos",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Relatório Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Utilizador Activity",
    "Navigation.audit-logs.Item.audit.Label": "Auditoria Registo Pesquisar",
    "Navigation.audit-logs.Label": "Registros de auditoria",
    "Navigation.dashboard.Item.dashboard.Label": "Painel",
    "Navigation.dashboard.Label": "Painel",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "Documentos",
    "Navigation.finance.Item.commissions.Label": "Agente Comissões",
    "Navigation.finance.Item.credit-debit-notes.Label": "Crédito / Débito Notas",
    "Navigation.finance.Item.finance.Label": "Finanças Workbench",
    "Navigation.finance.Item.invoices.Label": "Faturas",
    "Navigation.finance.Item.payments.Label": "Pagamentos a fornecedores",
    "Navigation.finance.Item.receipts.Label": "Recibos de clientes",
    "Navigation.finance.Item.vendor-bills.Label": "Faturas de fornecedor",
    "Navigation.finance.Label": "Finanças",
    "Navigation.masters.Item.agents.Label": "Agentes",
    "Navigation.masters.Item.carriers.Label": "Transportadoras",
    "Navigation.masters.Item.customers.Label": "Clientes",
    "Navigation.masters.Item.vendors.Label": "Fornecedores",
    "Navigation.masters.Label": "Cadastros",
    "Navigation.operations.Item.goods-receipt.Label": "Receção de mercadorias",
    "Navigation.operations.Item.pickup.Label": "Recolha",
    "Navigation.operations.Label": "Operações",
    "Navigation.portals.Item.agent-portal.Label": "Agente Portal",
    "Navigation.portals.Item.customer-portal.Label": "Cliente Portal",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "Cotações",
    "Navigation.rate-quotation.Item.rate-master.Label": "Tarifa Mestre",
    "Navigation.rate-quotation.Label": "Tarifa & Cotação",
    "Navigation.reports.Item.reports-balance-sheet.Label": "Balanço",
    "Navigation.reports.Item.reports-bank-book.Label": "Livro de banco",
    "Navigation.reports.Item.reports-cash-book.Label": "Livro de caixa",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "Ganho/perda cambial",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "Reavaliação cambial",
    "Navigation.reports.Item.reports-customer-ledger.Label": "Razão do cliente",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "Pendentes de clientes",
    "Navigation.reports.Item.reports-general-ledger.Label": "Razão geral",
    "Navigation.reports.Item.reports-ledger.Label": "Relatório razão",
    "Navigation.reports.Item.reports-op-ageing.Label": "Antiguidade das remessas",
    "Navigation.reports.Item.reports-op-air.Label": "Relatório de frete aéreo",
    "Navigation.reports.Item.reports-op-container.Label": "Relatório de contentores",
    "Navigation.reports.Item.reports-op-courier.Label": "Relatório de courier",
    "Navigation.reports.Item.reports-op-customs.Label": "Relatório alfandegário",
    "Navigation.reports.Item.reports-op-direct.Label": "Relatório de remessas diretas",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "Relatório de receção de mercadorias",
    "Navigation.reports.Item.reports-op-house.Label": "Relatório de remessas house",
    "Navigation.reports.Item.reports-op-master.Label": "Relatório de remessas master",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "Relatório de contas pendentes",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "Relatório de documentos pendentes",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "Relatório POD pendente",
    "Navigation.reports.Item.reports-op-pickup.Label": "Relatório de recolha",
    "Navigation.reports.Item.reports-op-quotation.Label": "Relatório de cotações",
    "Navigation.reports.Item.reports-op-road.Label": "Relatório de frete rodoviário",
    "Navigation.reports.Item.reports-op-sea.Label": "Relatório de frete marítimo",
    "Navigation.reports.Item.reports-op-unbilled.Label": "Remessas não faturadas",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "Relatório de stock de armazém",
    "Navigation.reports.Item.reports-profit-agent.Label": "Lucro do agente",
    "Navigation.reports.Item.reports-profit-branch.Label": "Lucro da filial",
    "Navigation.reports.Item.reports-profit-customer.Label": "Lucro do cliente",
    "Navigation.reports.Item.reports-profit-destination.Label": "Lucro do destino",
    "Navigation.reports.Item.reports-profit-loss.Label": "Lucros e perdas",
    "Navigation.reports.Item.reports-profit-route.Label": "Lucro da rota",
    "Navigation.reports.Item.reports-profit-salesman.Label": "Lucro do vendedor",
    "Navigation.reports.Item.reports-profit-shipment.Label": "Lucro da remessa",
    "Navigation.reports.Item.reports-soa.Label": "Extrato de conta",
    "Navigation.reports.Item.reports-tax-report.Label": "Relatório fiscal",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "P&L comercial",
    "Navigation.reports.Item.reports-trial-balance.Label": "Balancete",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "Razão do fornecedor",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "Pendentes de fornecedores",
    "Navigation.reports.Label": "Relatórios",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "Filial Configurações",
    "Navigation.settings.Item.currency-setup.Label": "Tenant Moedas",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "Tenant Idiomas",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering Configurações",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "Tenant Configurações",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "Configurações",
    "Navigation.shipments.Item.customs-jobs.Label": "Jobs",
    "Navigation.shipments.Item.customs.Label": "Alfândega Desalfandegamento",
    "Navigation.shipments.Item.direct-shipments.Label": "Remessas diretas",
    "Navigation.shipments.Item.house-shipments.Label": "Remessas house",
    "Navigation.shipments.Item.master-shipments.Label": "Remessas master",
    "Navigation.shipments.Label": "Remessas",
  },
  "ru-RU": {
    "Navigation.accounting.Label": "Бухгалтерия",
    "Navigation.administration.Item.employees.Label": "Сотрудники",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "Уведомление История",
    "Navigation.administration.Item.notification-templates.Label": "Уведомление Templates",
    "Navigation.administration.Item.permission-matrix.Label": "Право Матрица",
    "Navigation.administration.Item.roles.Label": "Роли",
    "Navigation.administration.Item.users.Label": "Пользователи",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request Журналы",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "Email Журналы",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export Журналы",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access Журналы",
    "Navigation.audit-logs.Item.audit-financial.Label": "Финансовый Аудит",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login История",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print Журналы",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Отчет Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Пользователь Activity",
    "Navigation.audit-logs.Item.audit.Label": "Аудит Журнал Поиск",
    "Navigation.audit-logs.Label": "Журналы аудита",
    "Navigation.dashboard.Item.dashboard.Label": "Панель",
    "Navigation.dashboard.Label": "Панель",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "Документы",
    "Navigation.finance.Item.commissions.Label": "Агент Комиссии",
    "Navigation.finance.Item.credit-debit-notes.Label": "Кредит / Дебет Ноты",
    "Navigation.finance.Item.finance.Label": "Финансы Workbench",
    "Navigation.finance.Item.invoices.Label": "Счета",
    "Navigation.finance.Item.payments.Label": "Платежи поставщикам",
    "Navigation.finance.Item.receipts.Label": "Поступления от клиентов",
    "Navigation.finance.Item.vendor-bills.Label": "Счета поставщиков",
    "Navigation.finance.Label": "Финансы",
    "Navigation.masters.Item.agents.Label": "Агенты",
    "Navigation.masters.Item.carriers.Label": "Перевозчики",
    "Navigation.masters.Item.customers.Label": "Клиенты",
    "Navigation.masters.Item.vendors.Label": "Поставщики",
    "Navigation.masters.Label": "Справочники",
    "Navigation.operations.Item.goods-receipt.Label": "Приемка груза",
    "Navigation.operations.Item.pickup.Label": "Забор груза",
    "Navigation.operations.Label": "Операции",
    "Navigation.portals.Item.agent-portal.Label": "Агент Портал",
    "Navigation.portals.Item.customer-portal.Label": "Клиент Портал",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "Предложения",
    "Navigation.rate-quotation.Item.rate-master.Label": "Тариф Мастер",
    "Navigation.rate-quotation.Label": "Тариф & Предложение",
    "Navigation.reports.Item.reports-balance-sheet.Label": "Баланс",
    "Navigation.reports.Item.reports-bank-book.Label": "Банковская книга",
    "Navigation.reports.Item.reports-cash-book.Label": "Кассовая книга",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "Курсовая прибыль/убыток",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "Переоценка валюты",
    "Navigation.reports.Item.reports-customer-ledger.Label": "Клиентская книга",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "Задолженность клиентов",
    "Navigation.reports.Item.reports-general-ledger.Label": "Главная книга",
    "Navigation.reports.Item.reports-ledger.Label": "Отчет по счету",
    "Navigation.reports.Item.reports-op-ageing.Label": "Анализ давности отправок",
    "Navigation.reports.Item.reports-op-air.Label": "Отчет по авиаперевозкам",
    "Navigation.reports.Item.reports-op-container.Label": "Отчет по контейнерам",
    "Navigation.reports.Item.reports-op-courier.Label": "Отчет по курьерским отправкам",
    "Navigation.reports.Item.reports-op-customs.Label": "Таможенный отчет",
    "Navigation.reports.Item.reports-op-direct.Label": "Отчет по прямым отправкам",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "Отчет по приемке груза",
    "Navigation.reports.Item.reports-op-house.Label": "Отчет по house отправкам",
    "Navigation.reports.Item.reports-op-master.Label": "Отчет по master отправкам",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "Отчет по ожидающим счетам",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "Отчет по ожидающим документам",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "Отчет по ожидающим POD",
    "Navigation.reports.Item.reports-op-pickup.Label": "Отчет по забору груза",
    "Navigation.reports.Item.reports-op-quotation.Label": "Отчет по предложениям",
    "Navigation.reports.Item.reports-op-road.Label": "Отчет по автоперевозкам",
    "Navigation.reports.Item.reports-op-sea.Label": "Отчет по морским перевозкам",
    "Navigation.reports.Item.reports-op-unbilled.Label": "Неофактурованные отправки",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "Отчет складских остатков",
    "Navigation.reports.Item.reports-profit-agent.Label": "Прибыль агента",
    "Navigation.reports.Item.reports-profit-branch.Label": "Прибыль филиала",
    "Navigation.reports.Item.reports-profit-customer.Label": "Прибыль клиента",
    "Navigation.reports.Item.reports-profit-destination.Label": "Прибыль направления",
    "Navigation.reports.Item.reports-profit-loss.Label": "Прибыли и убытки",
    "Navigation.reports.Item.reports-profit-route.Label": "Прибыль маршрута",
    "Navigation.reports.Item.reports-profit-salesman.Label": "Прибыль продавца",
    "Navigation.reports.Item.reports-profit-shipment.Label": "Прибыль отправки",
    "Navigation.reports.Item.reports-soa.Label": "Выписка по счету",
    "Navigation.reports.Item.reports-tax-report.Label": "Налоговый отчет",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "Торговые прибыли и убытки",
    "Navigation.reports.Item.reports-trial-balance.Label": "Оборотно-сальдовая ведомость",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "Книга поставщика",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "Задолженность поставщикам",
    "Navigation.reports.Label": "Отчеты",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "Филиал Настройки",
    "Navigation.settings.Item.currency-setup.Label": "Клиент Валюты",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "Клиент Языки",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering Настройки",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "Клиент Настройки",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "Настройки",
    "Navigation.shipments.Item.customs-jobs.Label": "Задания",
    "Navigation.shipments.Item.customs.Label": "Таможня Оформление",
    "Navigation.shipments.Item.direct-shipments.Label": "Прямые отправки",
    "Navigation.shipments.Item.house-shipments.Label": "House отправки",
    "Navigation.shipments.Item.master-shipments.Label": "Master отправки",
    "Navigation.shipments.Label": "Отправки",
  },
  "tr-TR": {
    "Navigation.accounting.Label": "Muhasebe",
    "Navigation.administration.Item.employees.Label": "Çalışanlar",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "Bildirim Geçmiş",
    "Navigation.administration.Item.notification-templates.Label": "Bildirim Templates",
    "Navigation.administration.Item.permission-matrix.Label": "Yetki Matrisi",
    "Navigation.administration.Item.roles.Label": "Roller",
    "Navigation.administration.Item.users.Label": "Kullanıcılar",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request Kayıtlar",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "E-posta Kayıtlar",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export Kayıtlar",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access Kayıtlar",
    "Navigation.audit-logs.Item.audit-financial.Label": "Mali Denetim",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login Geçmiş",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print Kayıtlar",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Rapor Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Kullanıcı Activity",
    "Navigation.audit-logs.Item.audit.Label": "Denetim Kayıt Ara",
    "Navigation.audit-logs.Label": "Denetim kayıtları",
    "Navigation.dashboard.Item.dashboard.Label": "Pano",
    "Navigation.dashboard.Label": "Pano",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "Belgeler",
    "Navigation.finance.Item.commissions.Label": "Acente Komisyonlar",
    "Navigation.finance.Item.credit-debit-notes.Label": "Alacak / Borç Notlar",
    "Navigation.finance.Item.finance.Label": "Finans Workbench",
    "Navigation.finance.Item.invoices.Label": "Faturalar",
    "Navigation.finance.Item.payments.Label": "Tedarikçi ödemeleri",
    "Navigation.finance.Item.receipts.Label": "Müşteri tahsilatları",
    "Navigation.finance.Item.vendor-bills.Label": "Tedarikçi faturaları",
    "Navigation.finance.Label": "Finans",
    "Navigation.masters.Item.agents.Label": "Acenteler",
    "Navigation.masters.Item.carriers.Label": "Taşıyıcılar",
    "Navigation.masters.Item.customers.Label": "Müşteriler",
    "Navigation.masters.Item.vendors.Label": "Tedarikçiler",
    "Navigation.masters.Label": "Ana veriler",
    "Navigation.operations.Item.goods-receipt.Label": "Mal kabul",
    "Navigation.operations.Item.pickup.Label": "Alım",
    "Navigation.operations.Label": "Operasyonlar",
    "Navigation.portals.Item.agent-portal.Label": "Acente Portal",
    "Navigation.portals.Item.customer-portal.Label": "Müşteri Portal",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "Teklifler",
    "Navigation.rate-quotation.Item.rate-master.Label": "Fiyat Ana",
    "Navigation.rate-quotation.Label": "Fiyat & Teklif",
    "Navigation.reports.Item.reports-balance-sheet.Label": "Bilanço",
    "Navigation.reports.Item.reports-bank-book.Label": "Banka defteri",
    "Navigation.reports.Item.reports-cash-book.Label": "Kasa defteri",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "Kur kar/zararı",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "Döviz değerleme",
    "Navigation.reports.Item.reports-customer-ledger.Label": "Müşteri ekstresi",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "Müşteri bakiyesi",
    "Navigation.reports.Item.reports-general-ledger.Label": "Genel muhasebe defteri",
    "Navigation.reports.Item.reports-ledger.Label": "Defter raporu",
    "Navigation.reports.Item.reports-op-ageing.Label": "Sevkiyat yaşlandırma",
    "Navigation.reports.Item.reports-op-air.Label": "Hava kargo raporu",
    "Navigation.reports.Item.reports-op-container.Label": "Konteyner raporu",
    "Navigation.reports.Item.reports-op-courier.Label": "Kurye raporu",
    "Navigation.reports.Item.reports-op-customs.Label": "Gümrük raporu",
    "Navigation.reports.Item.reports-op-direct.Label": "Direkt sevkiyat raporu",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "Mal kabul raporu",
    "Navigation.reports.Item.reports-op-house.Label": "House sevkiyat raporu",
    "Navigation.reports.Item.reports-op-master.Label": "Master sevkiyat raporu",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "Bekleyen fatura raporu",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "Bekleyen belge raporu",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "Bekleyen POD raporu",
    "Navigation.reports.Item.reports-op-pickup.Label": "Alım raporu",
    "Navigation.reports.Item.reports-op-quotation.Label": "Teklif raporu",
    "Navigation.reports.Item.reports-op-road.Label": "Karayolu kargo raporu",
    "Navigation.reports.Item.reports-op-sea.Label": "Deniz kargo raporu",
    "Navigation.reports.Item.reports-op-unbilled.Label": "Faturalanmamış sevkiyat",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "Depo stok raporu",
    "Navigation.reports.Item.reports-profit-agent.Label": "Acente karı",
    "Navigation.reports.Item.reports-profit-branch.Label": "Şube karı",
    "Navigation.reports.Item.reports-profit-customer.Label": "Müşteri karı",
    "Navigation.reports.Item.reports-profit-destination.Label": "Varış yeri karı",
    "Navigation.reports.Item.reports-profit-loss.Label": "Kar zarar",
    "Navigation.reports.Item.reports-profit-route.Label": "Rota karı",
    "Navigation.reports.Item.reports-profit-salesman.Label": "Satışçı karı",
    "Navigation.reports.Item.reports-profit-shipment.Label": "Sevkiyat karı",
    "Navigation.reports.Item.reports-soa.Label": "Hesap ekstresi",
    "Navigation.reports.Item.reports-tax-report.Label": "Vergi raporu",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "Ticari kar zarar",
    "Navigation.reports.Item.reports-trial-balance.Label": "Mizan",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "Tedarikçi ekstresi",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "Tedarikçi bakiyesi",
    "Navigation.reports.Label": "Raporlar",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "Şube Ayarlar",
    "Navigation.settings.Item.currency-setup.Label": "Kiracı Para birimleri",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "Kiracı Diller",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering Ayarlar",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "Kiracı Ayarlar",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "Ayarlar",
    "Navigation.shipments.Item.customs-jobs.Label": "İşler",
    "Navigation.shipments.Item.customs.Label": "Gümrük Gümrükleme",
    "Navigation.shipments.Item.direct-shipments.Label": "Direkt sevkiyatlar",
    "Navigation.shipments.Item.house-shipments.Label": "House sevkiyatlar",
    "Navigation.shipments.Item.master-shipments.Label": "Master sevkiyatlar",
    "Navigation.shipments.Label": "Sevkiyatlar",
  },
  "zh-CN": {
    "Navigation.accounting.Label": "会计",
    "Navigation.administration.Item.employees.Label": "员工",
    "Navigation.administration.Item.my-notifications.Label": "My Notifications",
    "Navigation.administration.Item.notification-history.Label": "通知 历史",
    "Navigation.administration.Item.notification-templates.Label": "通知 Templates",
    "Navigation.administration.Item.permission-matrix.Label": "权限 矩阵",
    "Navigation.administration.Item.roles.Label": "角色",
    "Navigation.administration.Item.users.Label": "用户",
    "Navigation.administration.Label": "Administration",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API Request 日志",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "电子邮件 日志",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Entity Changes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Export 日志",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "File Access 日志",
    "Navigation.audit-logs.Item.audit-financial.Label": "财务 审计",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Login 历史",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Print 日志",
    "Navigation.audit-logs.Item.audit-report-access.Label": "报表 Access",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "用户 Activity",
    "Navigation.audit-logs.Item.audit.Label": "审计 日志 搜索",
    "Navigation.audit-logs.Label": "审计日志",
    "Navigation.dashboard.Item.dashboard.Label": "仪表板",
    "Navigation.dashboard.Label": "仪表板",
    "Navigation.documents.Item.document-management.Label": "Document Management",
    "Navigation.documents.Label": "文档",
    "Navigation.finance.Item.commissions.Label": "代理 佣金",
    "Navigation.finance.Item.credit-debit-notes.Label": "贷项 / 借项 通知单",
    "Navigation.finance.Item.finance.Label": "财务 Workbench",
    "Navigation.finance.Item.invoices.Label": "发票",
    "Navigation.finance.Item.payments.Label": "供应商付款",
    "Navigation.finance.Item.receipts.Label": "客户收款",
    "Navigation.finance.Item.vendor-bills.Label": "供应商账单",
    "Navigation.finance.Label": "财务",
    "Navigation.masters.Item.agents.Label": "代理",
    "Navigation.masters.Item.carriers.Label": "承运人",
    "Navigation.masters.Item.customers.Label": "客户",
    "Navigation.masters.Item.vendors.Label": "供应商",
    "Navigation.masters.Label": "主数据",
    "Navigation.operations.Item.goods-receipt.Label": "收货",
    "Navigation.operations.Item.pickup.Label": "提货",
    "Navigation.operations.Label": "操作",
    "Navigation.portals.Item.agent-portal.Label": "代理 门户",
    "Navigation.portals.Item.customer-portal.Label": "客户 门户",
    "Navigation.portals.Label": "Portals",
    "Navigation.rate-quotation.Item.quotations.Label": "报价",
    "Navigation.rate-quotation.Item.rate-master.Label": "费率 主",
    "Navigation.rate-quotation.Label": "费率 & 报价",
    "Navigation.reports.Item.reports-balance-sheet.Label": "资产负债表",
    "Navigation.reports.Item.reports-bank-book.Label": "银行日记账",
    "Navigation.reports.Item.reports-cash-book.Label": "现金日记账",
    "Navigation.reports.Item.reports-currency-gain-loss.Label": "汇兑损益",
    "Navigation.reports.Item.reports-currency-revaluation.Label": "货币重估",
    "Navigation.reports.Item.reports-customer-ledger.Label": "客户分类账",
    "Navigation.reports.Item.reports-customer-outstanding.Label": "客户未结款",
    "Navigation.reports.Item.reports-general-ledger.Label": "总账",
    "Navigation.reports.Item.reports-ledger.Label": "分类账报表",
    "Navigation.reports.Item.reports-op-ageing.Label": "货运账龄",
    "Navigation.reports.Item.reports-op-air.Label": "空运报表",
    "Navigation.reports.Item.reports-op-container.Label": "集装箱报表",
    "Navigation.reports.Item.reports-op-courier.Label": "快递报表",
    "Navigation.reports.Item.reports-op-customs.Label": "海关报表",
    "Navigation.reports.Item.reports-op-direct.Label": "直运货运报表",
    "Navigation.reports.Item.reports-op-goods-receipt.Label": "收货报表",
    "Navigation.reports.Item.reports-op-house.Label": "分运单货运报表",
    "Navigation.reports.Item.reports-op-master.Label": "主运单货运报表",
    "Navigation.reports.Item.reports-op-pending-bill.Label": "待处理账单报表",
    "Navigation.reports.Item.reports-op-pending-doc.Label": "待处理文档报表",
    "Navigation.reports.Item.reports-op-pending-pod.Label": "待处理POD报表",
    "Navigation.reports.Item.reports-op-pickup.Label": "提货报表",
    "Navigation.reports.Item.reports-op-quotation.Label": "报价报表",
    "Navigation.reports.Item.reports-op-road.Label": "陆运报表",
    "Navigation.reports.Item.reports-op-sea.Label": "海运报表",
    "Navigation.reports.Item.reports-op-unbilled.Label": "未开票货运",
    "Navigation.reports.Item.reports-op-warehouse-stock.Label": "仓库库存报表",
    "Navigation.reports.Item.reports-profit-agent.Label": "代理利润",
    "Navigation.reports.Item.reports-profit-branch.Label": "分支利润",
    "Navigation.reports.Item.reports-profit-customer.Label": "客户利润",
    "Navigation.reports.Item.reports-profit-destination.Label": "目的地利润",
    "Navigation.reports.Item.reports-profit-loss.Label": "损益表",
    "Navigation.reports.Item.reports-profit-route.Label": "路线利润",
    "Navigation.reports.Item.reports-profit-salesman.Label": "销售员利润",
    "Navigation.reports.Item.reports-profit-shipment.Label": "货运利润",
    "Navigation.reports.Item.reports-soa.Label": "对账单",
    "Navigation.reports.Item.reports-tax-report.Label": "税务报表",
    "Navigation.reports.Item.reports-trading-profit-loss.Label": "交易损益",
    "Navigation.reports.Item.reports-trial-balance.Label": "试算表",
    "Navigation.reports.Item.reports-vendor-ledger.Label": "供应商分类账",
    "Navigation.reports.Item.reports-vendor-outstanding.Label": "供应商未结款",
    "Navigation.reports.Label": "报表",
    "Navigation.settings.Item.approval-workflows.Label": "Approval Workflows",
    "Navigation.settings.Item.branch-settings.Label": "分支机构 设置",
    "Navigation.settings.Item.currency-setup.Label": "租户 币种",
    "Navigation.settings.Item.label-templates.Label": "Label Templates",
    "Navigation.settings.Item.language-setup.Label": "租户 语言",
    "Navigation.settings.Item.numbering-settings.Label": "Numbering 设置",
    "Navigation.settings.Item.print-templates.Label": "Print Templates",
    "Navigation.settings.Item.tenant-settings.Label": "租户 设置",
    "Navigation.settings.Item.translations.Label": "Translations",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Available Goods",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Damaged Goods",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Returned Goods",
    "Navigation.settings.Item.warehouse-stock.Label": "Warehouse Stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stock Transactions",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stock Transfer",
    "Navigation.settings.Label": "设置",
    "Navigation.shipments.Item.customs-jobs.Label": "作业",
    "Navigation.shipments.Item.customs.Label": "海关 清关",
    "Navigation.shipments.Item.direct-shipments.Label": "直运货运",
    "Navigation.shipments.Item.house-shipments.Label": "分运单货运",
    "Navigation.shipments.Item.master-shipments.Label": "主运单货运",
    "Navigation.shipments.Label": "货运",
  },
};

const administrationMenuOverrides: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Navigation.administration.Label": "الإدارة",
    "Navigation.administration.Item.users.Label": "المستخدمون",
    "Navigation.administration.Item.employees.Label": "الموظفون",
    "Navigation.administration.Item.roles.Label": "الأدوار",
    "Navigation.administration.Item.permission-matrix.Label": "مصفوفة الصلاحيات",
    "Navigation.administration.Item.notification-templates.Label": "قوالب الإشعارات",
    "Navigation.administration.Item.notification-history.Label": "سجل الإشعارات",
    "Navigation.administration.Item.my-notifications.Label": "إشعاراتي"
  },
  "hi-IN": {
    "Navigation.administration.Label": "प्रशासन",
    "Navigation.administration.Item.users.Label": "उपयोगकर्ता",
    "Navigation.administration.Item.employees.Label": "कर्मचारी",
    "Navigation.administration.Item.roles.Label": "भूमिकाएँ",
    "Navigation.administration.Item.permission-matrix.Label": "अनुमति मैट्रिक्स",
    "Navigation.administration.Item.notification-templates.Label": "सूचना टेम्पलेट",
    "Navigation.administration.Item.notification-history.Label": "सूचना इतिहास",
    "Navigation.administration.Item.my-notifications.Label": "मेरी सूचनाएँ"
  },
  "fr-FR": {
    "Navigation.administration.Label": "Administration",
    "Navigation.administration.Item.users.Label": "Utilisateurs",
    "Navigation.administration.Item.employees.Label": "Employés",
    "Navigation.administration.Item.roles.Label": "Rôles",
    "Navigation.administration.Item.permission-matrix.Label": "Matrice des autorisations",
    "Navigation.administration.Item.notification-templates.Label": "Modèles de notification",
    "Navigation.administration.Item.notification-history.Label": "Historique des notifications",
    "Navigation.administration.Item.my-notifications.Label": "Mes notifications"
  },
  "es-ES": {
    "Navigation.administration.Label": "Administración",
    "Navigation.administration.Item.users.Label": "Usuarios",
    "Navigation.administration.Item.employees.Label": "Empleados",
    "Navigation.administration.Item.roles.Label": "Roles",
    "Navigation.administration.Item.permission-matrix.Label": "Matriz de permisos",
    "Navigation.administration.Item.notification-templates.Label": "Plantillas de notificación",
    "Navigation.administration.Item.notification-history.Label": "Historial de notificaciones",
    "Navigation.administration.Item.my-notifications.Label": "Mis notificaciones"
  },
  "zh-CN": {
    "Navigation.administration.Label": "系统管理",
    "Navigation.administration.Item.users.Label": "用户",
    "Navigation.administration.Item.employees.Label": "员工",
    "Navigation.administration.Item.roles.Label": "角色",
    "Navigation.administration.Item.permission-matrix.Label": "权限矩阵",
    "Navigation.administration.Item.notification-templates.Label": "通知模板",
    "Navigation.administration.Item.notification-history.Label": "通知历史",
    "Navigation.administration.Item.my-notifications.Label": "我的通知"
  },
  "tr-TR": {
    "Navigation.administration.Label": "Yönetim",
    "Navigation.administration.Item.users.Label": "Kullanıcılar",
    "Navigation.administration.Item.employees.Label": "Çalışanlar",
    "Navigation.administration.Item.roles.Label": "Roller",
    "Navigation.administration.Item.permission-matrix.Label": "Yetki Matrisi",
    "Navigation.administration.Item.notification-templates.Label": "Bildirim Şablonları",
    "Navigation.administration.Item.notification-history.Label": "Bildirim Geçmişi",
    "Navigation.administration.Item.my-notifications.Label": "Bildirimlerim"
  },
  "pt-PT": {
    "Navigation.administration.Label": "Administração",
    "Navigation.administration.Item.users.Label": "Utilizadores",
    "Navigation.administration.Item.employees.Label": "Colaboradores",
    "Navigation.administration.Item.roles.Label": "Funções",
    "Navigation.administration.Item.permission-matrix.Label": "Matriz de permissões",
    "Navigation.administration.Item.notification-templates.Label": "Modelos de notificação",
    "Navigation.administration.Item.notification-history.Label": "Histórico de notificações",
    "Navigation.administration.Item.my-notifications.Label": "As minhas notificações"
  },
  "ru-RU": {
    "Navigation.administration.Label": "Администрирование",
    "Navigation.administration.Item.users.Label": "Пользователи",
    "Navigation.administration.Item.employees.Label": "Сотрудники",
    "Navigation.administration.Item.roles.Label": "Роли",
    "Navigation.administration.Item.permission-matrix.Label": "Матрица разрешений",
    "Navigation.administration.Item.notification-templates.Label": "Шаблоны уведомлений",
    "Navigation.administration.Item.notification-history.Label": "История уведомлений",
    "Navigation.administration.Item.my-notifications.Label": "Мои уведомления"
  }
};

const settingsMenuOverrides: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Navigation.settings.Label": "الإعدادات",
    "Navigation.settings.Item.tenant-settings.Label": "إعدادات المستأجر",
    "Navigation.settings.Item.branch-settings.Label": "إعدادات الفرع",
    "Navigation.settings.Item.currency-setup.Label": "عملات المستأجر",
    "Navigation.settings.Item.language-setup.Label": "لغات المستأجر",
    "Navigation.settings.Item.translations.Label": "الترجمات",
    "Navigation.settings.Item.warehouse-stock.Label": "مخزون المستودع",
    "Navigation.settings.Item.warehouse-transfer.Label": "تحويل المخزون",
    "Navigation.settings.Item.warehouse-transactions.Label": "حركات المخزون",
    "Navigation.settings.Item.warehouse-available-goods.Label": "البضائع المتاحة",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "البضائع التالفة",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "البضائع المرتجعة",
    "Navigation.settings.Item.numbering-settings.Label": "إعدادات الترقيم",
    "Navigation.settings.Item.print-templates.Label": "قوالب الطباعة",
    "Navigation.settings.Item.label-templates.Label": "قوالب الملصقات",
    "Navigation.settings.Item.approval-workflows.Label": "سير الموافقات"
  },
  "hi-IN": {
    "Navigation.settings.Label": "सेटिंग्स",
    "Navigation.settings.Item.tenant-settings.Label": "टेनेंट सेटिंग्स",
    "Navigation.settings.Item.branch-settings.Label": "शाखा सेटिंग्स",
    "Navigation.settings.Item.currency-setup.Label": "टेनेंट मुद्राएं",
    "Navigation.settings.Item.language-setup.Label": "टेनेंट भाषाएं",
    "Navigation.settings.Item.translations.Label": "अनुवाद",
    "Navigation.settings.Item.warehouse-stock.Label": "वेयरहाउस स्टॉक",
    "Navigation.settings.Item.warehouse-transfer.Label": "स्टॉक ट्रांसफर",
    "Navigation.settings.Item.warehouse-transactions.Label": "स्टॉक लेनदेन",
    "Navigation.settings.Item.warehouse-available-goods.Label": "उपलब्ध माल",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "क्षतिग्रस्त माल",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "वापस आया माल",
    "Navigation.settings.Item.numbering-settings.Label": "नंबरिंग सेटिंग्स",
    "Navigation.settings.Item.print-templates.Label": "प्रिंट टेम्पलेट",
    "Navigation.settings.Item.label-templates.Label": "लेबल टेम्पलेट",
    "Navigation.settings.Item.approval-workflows.Label": "अनुमोदन वर्कफ़्लो"
  },
  "fr-FR": {
    "Navigation.settings.Label": "Paramètres",
    "Navigation.settings.Item.tenant-settings.Label": "Paramètres du tenant",
    "Navigation.settings.Item.branch-settings.Label": "Paramètres agence",
    "Navigation.settings.Item.currency-setup.Label": "Devises du tenant",
    "Navigation.settings.Item.language-setup.Label": "Langues du tenant",
    "Navigation.settings.Item.translations.Label": "Traductions",
    "Navigation.settings.Item.warehouse-stock.Label": "Stock entrepôt",
    "Navigation.settings.Item.warehouse-transfer.Label": "Transfert de stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Mouvements de stock",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Marchandises disponibles",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Marchandises endommagées",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Marchandises retournées",
    "Navigation.settings.Item.numbering-settings.Label": "Paramètres de numérotation",
    "Navigation.settings.Item.print-templates.Label": "Modèles d'impression",
    "Navigation.settings.Item.label-templates.Label": "Modèles d'étiquette",
    "Navigation.settings.Item.approval-workflows.Label": "Workflows d'approbation"
  },
  "es-ES": {
    "Navigation.settings.Label": "Configuración",
    "Navigation.settings.Item.tenant-settings.Label": "Configuración del tenant",
    "Navigation.settings.Item.branch-settings.Label": "Configuración de sucursal",
    "Navigation.settings.Item.currency-setup.Label": "Monedas del tenant",
    "Navigation.settings.Item.language-setup.Label": "Idiomas del tenant",
    "Navigation.settings.Item.translations.Label": "Traducciones",
    "Navigation.settings.Item.warehouse-stock.Label": "Stock de almacén",
    "Navigation.settings.Item.warehouse-transfer.Label": "Transferencia de stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Movimientos de stock",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Mercancía disponible",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Mercancía dañada",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Mercancía devuelta",
    "Navigation.settings.Item.numbering-settings.Label": "Configuración de numeración",
    "Navigation.settings.Item.print-templates.Label": "Plantillas de impresión",
    "Navigation.settings.Item.label-templates.Label": "Plantillas de etiqueta",
    "Navigation.settings.Item.approval-workflows.Label": "Flujos de aprobación"
  },
  "zh-CN": {
    "Navigation.settings.Label": "设置",
    "Navigation.settings.Item.tenant-settings.Label": "租户设置",
    "Navigation.settings.Item.branch-settings.Label": "分支机构设置",
    "Navigation.settings.Item.currency-setup.Label": "租户币种",
    "Navigation.settings.Item.language-setup.Label": "租户语言",
    "Navigation.settings.Item.translations.Label": "翻译",
    "Navigation.settings.Item.warehouse-stock.Label": "仓库库存",
    "Navigation.settings.Item.warehouse-transfer.Label": "库存调拨",
    "Navigation.settings.Item.warehouse-transactions.Label": "库存流水",
    "Navigation.settings.Item.warehouse-available-goods.Label": "可用货物",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "破损货物",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "退回货物",
    "Navigation.settings.Item.numbering-settings.Label": "编号设置",
    "Navigation.settings.Item.print-templates.Label": "打印模板",
    "Navigation.settings.Item.label-templates.Label": "标签模板",
    "Navigation.settings.Item.approval-workflows.Label": "审批流程"
  },
  "tr-TR": {
    "Navigation.settings.Label": "Ayarlar",
    "Navigation.settings.Item.tenant-settings.Label": "Kiracı ayarları",
    "Navigation.settings.Item.branch-settings.Label": "Şube ayarları",
    "Navigation.settings.Item.currency-setup.Label": "Kiracı para birimleri",
    "Navigation.settings.Item.language-setup.Label": "Kiracı dilleri",
    "Navigation.settings.Item.translations.Label": "Çeviriler",
    "Navigation.settings.Item.warehouse-stock.Label": "Depo stoku",
    "Navigation.settings.Item.warehouse-transfer.Label": "Stok transferi",
    "Navigation.settings.Item.warehouse-transactions.Label": "Stok hareketleri",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Mevcut mallar",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Hasarlı mallar",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "İade mallar",
    "Navigation.settings.Item.numbering-settings.Label": "Numaralandırma ayarları",
    "Navigation.settings.Item.print-templates.Label": "Yazdırma şablonları",
    "Navigation.settings.Item.label-templates.Label": "Etiket şablonları",
    "Navigation.settings.Item.approval-workflows.Label": "Onay iş akışları"
  },
  "pt-PT": {
    "Navigation.settings.Label": "Configurações",
    "Navigation.settings.Item.tenant-settings.Label": "Definições do tenant",
    "Navigation.settings.Item.branch-settings.Label": "Definições da filial",
    "Navigation.settings.Item.currency-setup.Label": "Moedas do tenant",
    "Navigation.settings.Item.language-setup.Label": "Idiomas do tenant",
    "Navigation.settings.Item.translations.Label": "Traduções",
    "Navigation.settings.Item.warehouse-stock.Label": "Stock de armazém",
    "Navigation.settings.Item.warehouse-transfer.Label": "Transferência de stock",
    "Navigation.settings.Item.warehouse-transactions.Label": "Movimentos de stock",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Mercadorias disponíveis",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Mercadorias danificadas",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Mercadorias devolvidas",
    "Navigation.settings.Item.numbering-settings.Label": "Definições de numeração",
    "Navigation.settings.Item.print-templates.Label": "Modelos de impressão",
    "Navigation.settings.Item.label-templates.Label": "Modelos de etiqueta",
    "Navigation.settings.Item.approval-workflows.Label": "Fluxos de aprovação"
  },
  "ru-RU": {
    "Navigation.settings.Label": "Настройки",
    "Navigation.settings.Item.tenant-settings.Label": "Настройки арендатора",
    "Navigation.settings.Item.branch-settings.Label": "Настройки филиала",
    "Navigation.settings.Item.currency-setup.Label": "Валюты арендатора",
    "Navigation.settings.Item.language-setup.Label": "Языки арендатора",
    "Navigation.settings.Item.translations.Label": "Переводы",
    "Navigation.settings.Item.warehouse-stock.Label": "Складской запас",
    "Navigation.settings.Item.warehouse-transfer.Label": "Перемещение запасов",
    "Navigation.settings.Item.warehouse-transactions.Label": "Складские операции",
    "Navigation.settings.Item.warehouse-available-goods.Label": "Доступные грузы",
    "Navigation.settings.Item.warehouse-damaged-goods.Label": "Поврежденные грузы",
    "Navigation.settings.Item.warehouse-returned-goods.Label": "Возвращенные грузы",
    "Navigation.settings.Item.numbering-settings.Label": "Настройки нумерации",
    "Navigation.settings.Item.print-templates.Label": "Печатные шаблоны",
    "Navigation.settings.Item.label-templates.Label": "Шаблоны этикеток",
    "Navigation.settings.Item.approval-workflows.Label": "Маршруты согласования"
  }
};

for (const [cultureCode, translations] of Object.entries(settingsMenuOverrides)) {
  menuLocalizationFallbacks[cultureCode] = {
    ...menuLocalizationFallbacks[cultureCode],
    ...translations
  };
}

for (const [culture, values] of Object.entries(administrationMenuOverrides)) {
  Object.assign(menuLocalizationFallbacks[culture] ?? (menuLocalizationFallbacks[culture] = {}), values);
}

const auditMenuOverrides: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Navigation.audit-logs.Label": "سجلات التدقيق",
    "Navigation.audit-logs.Item.audit.Label": "بحث سجل التدقيق",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "نشاط المستخدم",
    "Navigation.audit-logs.Item.audit-login-history.Label": "سجل تسجيل الدخول",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "تغييرات الكيان",
    "Navigation.audit-logs.Item.audit-financial.Label": "التدقيق المالي",
    "Navigation.audit-logs.Item.audit-report-access.Label": "وصول التقارير",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "سجلات التصدير",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "سجلات الطباعة",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "سجلات البريد الإلكتروني",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "سجلات الوصول إلى الملفات",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "سجلات طلبات API"
  },
  "hi-IN": {
    "Navigation.audit-logs.Label": "ऑडिट लॉग",
    "Navigation.audit-logs.Item.audit.Label": "ऑडिट लॉग खोज",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "उपयोगकर्ता गतिविधि",
    "Navigation.audit-logs.Item.audit-login-history.Label": "लॉगिन इतिहास",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "इकाई परिवर्तन",
    "Navigation.audit-logs.Item.audit-financial.Label": "वित्तीय ऑडिट",
    "Navigation.audit-logs.Item.audit-report-access.Label": "रिपोर्ट एक्सेस",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "निर्यात लॉग",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "प्रिंट लॉग",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "ईमेल लॉग",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "फ़ाइल एक्सेस लॉग",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API अनुरोध लॉग"
  },
  "fr-FR": {
    "Navigation.audit-logs.Label": "Journaux d'audit",
    "Navigation.audit-logs.Item.audit.Label": "Recherche d'audit",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Activité utilisateur",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Historique de connexion",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Modifications d'entité",
    "Navigation.audit-logs.Item.audit-financial.Label": "Audit financier",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Accès aux rapports",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Journaux d'export",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Journaux d'impression",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "Journaux e-mail",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "Accès aux fichiers",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "Requêtes API"
  },
  "es-ES": {
    "Navigation.audit-logs.Label": "Registros de auditoría",
    "Navigation.audit-logs.Item.audit.Label": "Búsqueda de auditoría",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Actividad de usuario",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Historial de inicio",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Cambios de entidad",
    "Navigation.audit-logs.Item.audit-financial.Label": "Auditoría financiera",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Acceso a informes",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Registros de exportación",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Registros de impresión",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "Registros de correo",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "Acceso a archivos",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "Solicitudes API"
  },
  "zh-CN": {
    "Navigation.audit-logs.Label": "审计日志",
    "Navigation.audit-logs.Item.audit.Label": "审计日志查询",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "用户活动",
    "Navigation.audit-logs.Item.audit-login-history.Label": "登录历史",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "实体变更",
    "Navigation.audit-logs.Item.audit-financial.Label": "财务审计",
    "Navigation.audit-logs.Item.audit-report-access.Label": "报表访问",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "导出日志",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "打印日志",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "电子邮件日志",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "文件访问日志",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API 请求日志"
  },
  "tr-TR": {
    "Navigation.audit-logs.Label": "Denetim kayıtları",
    "Navigation.audit-logs.Item.audit.Label": "Denetim kaydı arama",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Kullanıcı etkinliği",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Giriş geçmişi",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Varlık değişiklikleri",
    "Navigation.audit-logs.Item.audit-financial.Label": "Mali denetim",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Rapor erişimi",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Dışa aktarma kayıtları",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Yazdırma kayıtları",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "E-posta kayıtları",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "Dosya erişim kayıtları",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API istek kayıtları"
  },
  "pt-PT": {
    "Navigation.audit-logs.Label": "Registos de auditoria",
    "Navigation.audit-logs.Item.audit.Label": "Pesquisa de auditoria",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Atividade do utilizador",
    "Navigation.audit-logs.Item.audit-login-history.Label": "Histórico de início de sessão",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Alterações da entidade",
    "Navigation.audit-logs.Item.audit-financial.Label": "Auditoria financeira",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Acesso a relatórios",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Registos de exportação",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Registos de impressão",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "Registos de e-mail",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "Acesso a ficheiros",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "Pedidos API"
  },
  "ru-RU": {
    "Navigation.audit-logs.Label": "Журналы аудита",
    "Navigation.audit-logs.Item.audit.Label": "Поиск журнала аудита",
    "Navigation.audit-logs.Item.audit-user-activity.Label": "Активность пользователя",
    "Navigation.audit-logs.Item.audit-login-history.Label": "История входов",
    "Navigation.audit-logs.Item.audit-entity-changes.Label": "Изменения сущности",
    "Navigation.audit-logs.Item.audit-financial.Label": "Финансовый аудит",
    "Navigation.audit-logs.Item.audit-report-access.Label": "Доступ к отчётам",
    "Navigation.audit-logs.Item.audit-export-logs.Label": "Журналы экспорта",
    "Navigation.audit-logs.Item.audit-print-logs.Label": "Журналы печати",
    "Navigation.audit-logs.Item.audit-email-logs.Label": "Журналы электронной почты",
    "Navigation.audit-logs.Item.audit-file-logs.Label": "Доступ к файлам",
    "Navigation.audit-logs.Item.audit-api-request-logs.Label": "API-запросы"
  }
};

for (const [culture, values] of Object.entries(auditMenuOverrides)) {
  Object.assign(menuLocalizationFallbacks[culture] ?? (menuLocalizationFallbacks[culture] = {}), values);
}
