export const uiLocalizationFallbacks: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Common.Home": "الرئيسية",
    "Page.Title.MasterData": "البيانات الرئيسية",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "مساحة عمل واحدة لإعداد بيانات المستأجر والبيانات التجارية والتشغيلية والمحاسبية.",
    "MasterData.SetupModules": "وحدات الإعداد",
    "MasterData.SetupModulesDescription": "اختر بيانات رئيسية لإدارة الأكواد والقيم الافتراضية والربط وقيم الإعداد النشطة.",
    "MasterData.SearchPlaceholder": "البحث في البيانات الرئيسية...",
    "MasterData.EmptyTitle": "لم يتم العثور على شاشات بيانات رئيسية",
    "MasterData.EmptySearchDescription": "جرّب مصطلح بحث مختلف.",
    "MasterData.EmptyPermissionDescription": "دورك الحالي لا يملك صلاحية الوصول إلى شاشات البيانات الرئيسية.",
    "MasterData.Badge": "رئيسي",
    "MasterData.OpenSetup": "فتح الإعداد",
    "MasterData.Item.currencies.Label": "العملات",
    "MasterData.Item.languages.Label": "اللغات",
    "MasterData.Item.customers.Label": "العملاء",
    "MasterData.Item.vendors.Label": "الموردون",
    "MasterData.Item.agents.Label": "الوكلاء",
    "MasterData.Item.carriers.Label": "الناقلون",
    "MasterData.Item.countries.Label": "الدول",
    "MasterData.Item.package-types.Label": "أنواع الطرود",
    "MasterData.Item.shipping-ports.Label": "موانئ الشحن",
    "MasterData.Item.job-types.Label": "أنواع الوظائف",
    "MasterData.Item.warehouses.Label": "المستودعات",
    "MasterData.Item.charge-heads.Label": "بنود الرسوم",
    "MasterData.Item.taxes.Label": "إعداد الضرائب",
    "MasterData.Item.currencies.Description": "إعداد العملات والأسعار وإعادة التقييم.",
    "MasterData.Item.languages.Description": "إعداد اللغات وتفضيلات المستأجر والترجمات.",
    "MasterData.Item.customers.Description": "سجلات العملاء وملف الائتمان.",
    "MasterData.Item.vendors.Description": "إعداد الموردين مع العملة وملف الفوترة.",
    "MasterData.Item.agents.Description": "إعداد وكلاء الوجهة والعمولات.",
    "MasterData.Item.carriers.Description": "إعداد شركات الطيران والخطوط والنقل البري والبريد السريع.",
    "MasterData.Item.countries.Description": "رموز الدول ورموز ISO ورموز الاتصال بالجوال.",
    "MasterData.Item.package-types.Description": "إعداد كود الطرد واسم الطرد.",
    "MasterData.Item.shipping-ports.Description": "إعداد موانئ الشحن لتخطيط المنشأ والوجهة.",
    "MasterData.Item.job-types.Description": "الأكواد المختصرة لأنواع الوظائف المستخدمة في ترقيم الوظائف.",
    "MasterData.Item.warehouses.Description": "بيانات المستودعات والمواقع ورؤية المخزون.",
    "MasterData.Item.charge-heads.Description": "ربط بنود الرسوم بحسابات الأستاذ.",
    "MasterData.Item.taxes.Description": "قواعد ضريبة GST/VAT والتكامل مع دفتر الأستاذ."
  },
  "hi-IN": {
    "Common.Home": "होम",
    "Page.Title.MasterData": "मास्टर डेटा",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "टेनेंट, वाणिज्यिक, परिचालन और लेखा सेटअप मास्टर्स के लिए एक ही कार्यक्षेत्र।",
    "MasterData.SetupModules": "सेटअप मॉड्यूल",
    "MasterData.SetupModulesDescription": "कोड, डिफ़ॉल्ट, मैपिंग और सक्रिय सेटअप मान बनाए रखने के लिए मास्टर चुनें।",
    "MasterData.SearchPlaceholder": "मास्टर डेटा खोजें...",
    "MasterData.EmptyTitle": "कोई मास्टर स्क्रीन नहीं मिली",
    "MasterData.EmptySearchDescription": "कोई दूसरा खोज शब्द आज़माएं।",
    "MasterData.EmptyPermissionDescription": "आपकी वर्तमान भूमिका को मास्टर डेटा स्क्रीन तक पहुंच नहीं है।",
    "MasterData.Badge": "मास्टर",
    "MasterData.OpenSetup": "सेटअप खोलें",
    "MasterData.Item.currencies.Label": "मुद्राएं",
    "MasterData.Item.languages.Label": "भाषाएं",
    "MasterData.Item.customers.Label": "ग्राहक",
    "MasterData.Item.vendors.Label": "विक्रेता",
    "MasterData.Item.agents.Label": "एजेंट",
    "MasterData.Item.carriers.Label": "कैरियर",
    "MasterData.Item.countries.Label": "देश",
    "MasterData.Item.package-types.Label": "पैकेज प्रकार",
    "MasterData.Item.shipping-ports.Label": "शिपिंग पोर्ट",
    "MasterData.Item.job-types.Label": "जॉब प्रकार",
    "MasterData.Item.warehouses.Label": "गोदाम",
    "MasterData.Item.charge-heads.Label": "चार्ज हेड",
    "MasterData.Item.taxes.Label": "कर सेटअप",
    "MasterData.Item.currencies.Description": "मुद्रा सेटअप, दरें और पुनर्मूल्यांकन।",
    "MasterData.Item.languages.Description": "भाषा सेटअप, टेनेंट प्राथमिकता और अनुवाद।",
    "MasterData.Item.customers.Description": "ग्राहक मास्टर रिकॉर्ड और क्रेडिट प्रोफाइल।",
    "MasterData.Item.vendors.Description": "मुद्रा और बिलिंग प्रोफाइल सहित विक्रेता सेटअप।",
    "MasterData.Item.agents.Description": "गंतव्य और कमीशन एजेंट सेटअप।",
    "MasterData.Item.carriers.Description": "एयरलाइन, लाइन, रोड और कूरियर कैरियर सेटअप।",
    "MasterData.Item.countries.Description": "देश कोड, ISO कोड और मोबाइल डायलिंग कोड।",
    "MasterData.Item.package-types.Description": "पैकेज कोड और पैकेज नाम मास्टर सेटअप।",
    "MasterData.Item.shipping-ports.Description": "मूल/गंतव्य योजना के लिए शिपिंग पोर्ट मास्टर सेटअप।",
    "MasterData.Item.job-types.Description": "जॉब नंबरिंग के लिए उपयोग होने वाले जॉब प्रकार शॉर्ट कोड।",
    "MasterData.Item.warehouses.Description": "गोदाम मास्टर, लोकेशन और स्टॉक दृश्यता।",
    "MasterData.Item.charge-heads.Description": "चार्ज हेड से लेजर खाते की मैपिंग।",
    "MasterData.Item.taxes.Description": "GST/VAT कर नियम और लेजर इंटीग्रेशन।"
  },
  "fr-FR": {
    "Common.Home": "Accueil",
    "Page.Title.MasterData": "Référentiels",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "Un espace unique pour les référentiels locataire, commerciaux, opérationnels et comptables.",
    "MasterData.SetupModules": "Modules de configuration",
    "MasterData.SetupModulesDescription": "Choisissez un référentiel pour gérer les codes, valeurs par défaut, correspondances et paramètres actifs.",
    "MasterData.SearchPlaceholder": "Rechercher dans les référentiels...",
    "MasterData.EmptyTitle": "Aucun écran de référentiel trouvé",
    "MasterData.EmptySearchDescription": "Essayez un autre terme de recherche.",
    "MasterData.EmptyPermissionDescription": "Votre rôle actuel n’a pas accès aux écrans de référentiels.",
    "MasterData.Badge": "Référentiel",
    "MasterData.OpenSetup": "Ouvrir la configuration",
    "MasterData.Item.currencies.Label": "Devises",
    "MasterData.Item.languages.Label": "Langues",
    "MasterData.Item.customers.Label": "Clients",
    "MasterData.Item.vendors.Label": "Fournisseurs",
    "MasterData.Item.agents.Label": "Agents",
    "MasterData.Item.carriers.Label": "Transporteurs",
    "MasterData.Item.countries.Label": "Pays",
    "MasterData.Item.package-types.Label": "Types de colis",
    "MasterData.Item.shipping-ports.Label": "Ports d’expédition",
    "MasterData.Item.job-types.Label": "Types de dossier",
    "MasterData.Item.warehouses.Label": "Entrepôts",
    "MasterData.Item.charge-heads.Label": "Rubriques de frais",
    "MasterData.Item.taxes.Label": "Configuration des taxes",
    "MasterData.Item.currencies.Description": "Configuration des devises, taux et réévaluation.",
    "MasterData.Item.languages.Description": "Configuration des langues, préférence locataire et traductions.",
    "MasterData.Item.customers.Description": "Fiches clients et profil de crédit.",
    "MasterData.Item.vendors.Description": "Configuration fournisseur avec devise et profil de facturation.",
    "MasterData.Item.agents.Description": "Configuration des agents destination et commission.",
    "MasterData.Item.carriers.Description": "Configuration des transporteurs aérien, maritime, routier et courrier.",
    "MasterData.Item.countries.Description": "Codes pays, codes ISO et indicatifs mobiles.",
    "MasterData.Item.package-types.Description": "Configuration du code et du nom de colis.",
    "MasterData.Item.shipping-ports.Description": "Configuration des ports pour la planification origine/destination.",
    "MasterData.Item.job-types.Description": "Codes courts de type de dossier utilisés pour la numérotation.",
    "MasterData.Item.warehouses.Description": "Référentiel entrepôt, emplacements et visibilité du stock.",
    "MasterData.Item.charge-heads.Description": "Correspondance des rubriques de frais avec les comptes comptables.",
    "MasterData.Item.taxes.Description": "Règles GST/TVA et intégration comptable."
  },
  "es-ES": {
    "Common.Home": "Inicio",
    "Page.Title.MasterData": "Datos maestros",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "Un único espacio para maestros de configuración de tenant, comercial, operaciones y contabilidad.",
    "MasterData.SetupModules": "Módulos de configuración",
    "MasterData.SetupModulesDescription": "Elija un maestro para mantener códigos, valores predeterminados, asignaciones y configuración activa.",
    "MasterData.SearchPlaceholder": "Buscar datos maestros...",
    "MasterData.EmptyTitle": "No se encontraron pantallas de datos maestros",
    "MasterData.EmptySearchDescription": "Pruebe con otro término de búsqueda.",
    "MasterData.EmptyPermissionDescription": "Su rol actual no tiene acceso a las pantallas de datos maestros.",
    "MasterData.Badge": "Maestro",
    "MasterData.OpenSetup": "Abrir configuración",
    "MasterData.Item.currencies.Label": "Monedas",
    "MasterData.Item.languages.Label": "Idiomas",
    "MasterData.Item.customers.Label": "Clientes",
    "MasterData.Item.vendors.Label": "Proveedores",
    "MasterData.Item.agents.Label": "Agentes",
    "MasterData.Item.carriers.Label": "Transportistas",
    "MasterData.Item.countries.Label": "Países",
    "MasterData.Item.package-types.Label": "Tipos de paquete",
    "MasterData.Item.shipping-ports.Label": "Puertos de envío",
    "MasterData.Item.job-types.Label": "Tipos de trabajo",
    "MasterData.Item.warehouses.Label": "Almacenes",
    "MasterData.Item.charge-heads.Label": "Conceptos de cargo",
    "MasterData.Item.taxes.Label": "Configuración de impuestos",
    "MasterData.Item.currencies.Description": "Configuración de monedas, tasas y revaluación.",
    "MasterData.Item.languages.Description": "Configuración de idiomas, preferencia del tenant y traducciones.",
    "MasterData.Item.customers.Description": "Registros maestros de clientes y perfil de crédito.",
    "MasterData.Item.vendors.Description": "Configuración de proveedores con moneda y perfil de facturación.",
    "MasterData.Item.agents.Description": "Configuración de agentes de destino y comisión.",
    "MasterData.Item.carriers.Description": "Configuración de aerolíneas, líneas, transporte por carretera y courier.",
    "MasterData.Item.countries.Description": "Códigos de país, códigos ISO y prefijos móviles.",
    "MasterData.Item.package-types.Description": "Configuración de código y nombre de paquete.",
    "MasterData.Item.shipping-ports.Description": "Configuración de puertos para planificación origen/destino.",
    "MasterData.Item.job-types.Description": "Códigos cortos de tipo de trabajo usados para numeración.",
    "MasterData.Item.warehouses.Description": "Maestro de almacenes, ubicaciones y visibilidad de stock.",
    "MasterData.Item.charge-heads.Description": "Asignación de conceptos de cargo a cuentas contables.",
    "MasterData.Item.taxes.Description": "Reglas GST/IVA e integración contable."
  },
  "zh-CN": {
    "Common.Home": "首页",
    "Page.Title.MasterData": "主数据",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "用于租户、商务、运营和会计设置主数据的统一工作区。",
    "MasterData.SetupModules": "设置模块",
    "MasterData.SetupModulesDescription": "选择主数据以维护代码、默认值、映射和启用的设置值。",
    "MasterData.SearchPlaceholder": "搜索主数据...",
    "MasterData.EmptyTitle": "未找到主数据页面",
    "MasterData.EmptySearchDescription": "请尝试其他搜索词。",
    "MasterData.EmptyPermissionDescription": "您当前的角色无权访问主数据页面。",
    "MasterData.Badge": "主数据",
    "MasterData.OpenSetup": "打开设置",
    "MasterData.Item.currencies.Label": "币种",
    "MasterData.Item.languages.Label": "语言",
    "MasterData.Item.customers.Label": "客户",
    "MasterData.Item.vendors.Label": "供应商",
    "MasterData.Item.agents.Label": "代理",
    "MasterData.Item.carriers.Label": "承运人",
    "MasterData.Item.countries.Label": "国家",
    "MasterData.Item.package-types.Label": "包装类型",
    "MasterData.Item.shipping-ports.Label": "装运港口",
    "MasterData.Item.job-types.Label": "作业类型",
    "MasterData.Item.warehouses.Label": "仓库",
    "MasterData.Item.charge-heads.Label": "费用项目",
    "MasterData.Item.taxes.Label": "税务设置",
    "MasterData.Item.currencies.Description": "币种设置、汇率和重估。",
    "MasterData.Item.languages.Description": "语言设置、租户偏好和翻译。",
    "MasterData.Item.customers.Description": "客户主记录和信用资料。",
    "MasterData.Item.vendors.Description": "供应商设置，包括币种和账单资料。",
    "MasterData.Item.agents.Description": "目的地和佣金代理设置。",
    "MasterData.Item.carriers.Description": "航空、航线、公路和快递承运人设置。",
    "MasterData.Item.countries.Description": "国家代码、ISO 代码和手机区号。",
    "MasterData.Item.package-types.Description": "包装代码和包装名称设置。",
    "MasterData.Item.shipping-ports.Description": "用于起运地/目的地计划的装运港口设置。",
    "MasterData.Item.job-types.Description": "用于作业编号的作业类型短代码。",
    "MasterData.Item.warehouses.Description": "仓库主数据、库位和库存可视性。",
    "MasterData.Item.charge-heads.Description": "费用项目到账户科目的映射。",
    "MasterData.Item.taxes.Description": "GST/VAT 税务规则和会计集成。"
  },
  "tr-TR": {
    "Common.Home": "Ana sayfa",
    "Page.Title.MasterData": "Ana veriler",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "Kiracı, ticari, operasyonel ve muhasebe kurulum ana verileri için tek çalışma alanı.",
    "MasterData.SetupModules": "Kurulum modülleri",
    "MasterData.SetupModulesDescription": "Kodları, varsayılanları, eşleştirmeleri ve aktif kurulum değerlerini yönetmek için bir ana veri seçin.",
    "MasterData.SearchPlaceholder": "Ana verilerde ara...",
    "MasterData.EmptyTitle": "Ana veri ekranı bulunamadı",
    "MasterData.EmptySearchDescription": "Farklı bir arama terimi deneyin.",
    "MasterData.EmptyPermissionDescription": "Mevcut rolünüz ana veri ekranlarına erişemez.",
    "MasterData.Badge": "Ana veri",
    "MasterData.OpenSetup": "Kurulumu aç",
    "MasterData.Item.currencies.Label": "Para birimleri",
    "MasterData.Item.languages.Label": "Diller",
    "MasterData.Item.customers.Label": "Müşteriler",
    "MasterData.Item.vendors.Label": "Tedarikçiler",
    "MasterData.Item.agents.Label": "Acenteler",
    "MasterData.Item.carriers.Label": "Taşıyıcılar",
    "MasterData.Item.countries.Label": "Ülkeler",
    "MasterData.Item.package-types.Label": "Paket türleri",
    "MasterData.Item.shipping-ports.Label": "Sevkiyat limanları",
    "MasterData.Item.job-types.Label": "İş türleri",
    "MasterData.Item.warehouses.Label": "Depolar",
    "MasterData.Item.charge-heads.Label": "Masraf başlıkları",
    "MasterData.Item.taxes.Label": "Vergi ayarları",
    "MasterData.Item.currencies.Description": "Para birimi ayarları, kurlar ve değerleme.",
    "MasterData.Item.languages.Description": "Dil ayarları, kiracı tercihi ve çeviriler.",
    "MasterData.Item.customers.Description": "Müşteri ana kayıtları ve kredi profili.",
    "MasterData.Item.vendors.Description": "Para birimi ve faturalama profili ile tedarikçi ayarı.",
    "MasterData.Item.agents.Description": "Varış ve komisyon acentesi ayarı.",
    "MasterData.Item.carriers.Description": "Havayolu, hat, kara ve kurye taşıyıcı ayarı.",
    "MasterData.Item.countries.Description": "Ülke kodları, ISO kodları ve mobil arama kodları.",
    "MasterData.Item.package-types.Description": "Paket kodu ve paket adı ana ayarı.",
    "MasterData.Item.shipping-ports.Description": "Çıkış/varış planlaması için sevkiyat limanı ayarı.",
    "MasterData.Item.job-types.Description": "İş numaralandırmasında kullanılan iş türü kısa kodları.",
    "MasterData.Item.warehouses.Description": "Depo ana verisi, lokasyonlar ve stok görünürlüğü.",
    "MasterData.Item.charge-heads.Description": "Masraf başlıklarının defter hesaplarıyla eşleştirilmesi.",
    "MasterData.Item.taxes.Description": "GST/KDV vergi kuralları ve muhasebe entegrasyonu."
  },
  "pt-PT": {
    "Common.Home": "Início",
    "Page.Title.MasterData": "Dados mestre",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "Um único espaço para cadastros de tenant, comerciais, operacionais e contabilísticos.",
    "MasterData.SetupModules": "Módulos de configuração",
    "MasterData.SetupModulesDescription": "Escolha um cadastro para manter códigos, padrões, mapeamentos e valores ativos.",
    "MasterData.SearchPlaceholder": "Pesquisar dados mestre...",
    "MasterData.EmptyTitle": "Nenhum ecrã de dados mestre encontrado",
    "MasterData.EmptySearchDescription": "Tente outro termo de pesquisa.",
    "MasterData.EmptyPermissionDescription": "A sua função atual não tem acesso aos ecrãs de dados mestre.",
    "MasterData.Badge": "Cadastro",
    "MasterData.OpenSetup": "Abrir configuração",
    "MasterData.Item.currencies.Label": "Moedas",
    "MasterData.Item.languages.Label": "Idiomas",
    "MasterData.Item.customers.Label": "Clientes",
    "MasterData.Item.vendors.Label": "Fornecedores",
    "MasterData.Item.agents.Label": "Agentes",
    "MasterData.Item.carriers.Label": "Transportadoras",
    "MasterData.Item.countries.Label": "Países",
    "MasterData.Item.package-types.Label": "Tipos de embalagem",
    "MasterData.Item.shipping-ports.Label": "Portos de expedição",
    "MasterData.Item.job-types.Label": "Tipos de serviço",
    "MasterData.Item.warehouses.Label": "Armazéns",
    "MasterData.Item.charge-heads.Label": "Rubricas de cobrança",
    "MasterData.Item.taxes.Label": "Configuração fiscal",
    "MasterData.Item.currencies.Description": "Configuração de moedas, taxas e reavaliação.",
    "MasterData.Item.languages.Description": "Configuração de idiomas, preferência do tenant e traduções.",
    "MasterData.Item.customers.Description": "Registos de clientes e perfil de crédito.",
    "MasterData.Item.vendors.Description": "Configuração de fornecedores com moeda e perfil de faturação.",
    "MasterData.Item.agents.Description": "Configuração de agentes de destino e comissão.",
    "MasterData.Item.carriers.Description": "Configuração de transportadoras aéreas, marítimas, rodoviárias e courier.",
    "MasterData.Item.countries.Description": "Códigos de país, códigos ISO e indicativos móveis.",
    "MasterData.Item.package-types.Description": "Configuração de código e nome de embalagem.",
    "MasterData.Item.shipping-ports.Description": "Configuração de portos para planeamento origem/destino.",
    "MasterData.Item.job-types.Description": "Códigos curtos de tipo de serviço usados na numeração.",
    "MasterData.Item.warehouses.Description": "Cadastro de armazéns, localizações e visibilidade de stock.",
    "MasterData.Item.charge-heads.Description": "Mapeamento de rubricas de cobrança para contas razão.",
    "MasterData.Item.taxes.Description": "Regras GST/IVA e integração contabilística."
  },
  "ru-RU": {
    "Common.Home": "Главная",
    "Page.Title.MasterData": "Справочники",
    "Page.Description.ASingleWorkspaceForTenantCommercialOperationalAndAccountingSetupMasters": "Единая рабочая область для справочников арендатора, коммерции, операций и учета.",
    "MasterData.SetupModules": "Модули настройки",
    "MasterData.SetupModulesDescription": "Выберите справочник для ведения кодов, значений по умолчанию, сопоставлений и активных настроек.",
    "MasterData.SearchPlaceholder": "Поиск справочников...",
    "MasterData.EmptyTitle": "Экраны справочников не найдены",
    "MasterData.EmptySearchDescription": "Попробуйте другой поисковый запрос.",
    "MasterData.EmptyPermissionDescription": "У вашей текущей роли нет доступа к экранам справочников.",
    "MasterData.Badge": "Справочник",
    "MasterData.OpenSetup": "Открыть настройку",
    "MasterData.Item.currencies.Label": "Валюты",
    "MasterData.Item.languages.Label": "Языки",
    "MasterData.Item.customers.Label": "Клиенты",
    "MasterData.Item.vendors.Label": "Поставщики",
    "MasterData.Item.agents.Label": "Агенты",
    "MasterData.Item.carriers.Label": "Перевозчики",
    "MasterData.Item.countries.Label": "Страны",
    "MasterData.Item.package-types.Label": "Типы упаковки",
    "MasterData.Item.shipping-ports.Label": "Порты отгрузки",
    "MasterData.Item.job-types.Label": "Типы заданий",
    "MasterData.Item.warehouses.Label": "Склады",
    "MasterData.Item.charge-heads.Label": "Статьи начислений",
    "MasterData.Item.taxes.Label": "Настройка налогов",
    "MasterData.Item.currencies.Description": "Настройка валют, курсов и переоценки.",
    "MasterData.Item.languages.Description": "Настройка языков, предпочтений арендатора и переводов.",
    "MasterData.Item.customers.Description": "Карточки клиентов и кредитный профиль.",
    "MasterData.Item.vendors.Description": "Настройка поставщиков с валютой и платежным профилем.",
    "MasterData.Item.agents.Description": "Настройка агентов назначения и комиссий.",
    "MasterData.Item.carriers.Description": "Настройка авиа, линий, автоперевозчиков и курьерских служб.",
    "MasterData.Item.countries.Description": "Коды стран, ISO-коды и мобильные коды набора.",
    "MasterData.Item.package-types.Description": "Настройка кода и названия упаковки.",
    "MasterData.Item.shipping-ports.Description": "Настройка портов для планирования отправления/назначения.",
    "MasterData.Item.job-types.Description": "Краткие коды типов заданий для нумерации.",
    "MasterData.Item.warehouses.Description": "Справочник складов, мест хранения и видимость запасов.",
    "MasterData.Item.charge-heads.Description": "Сопоставление статей начислений со счетами учета.",
    "MasterData.Item.taxes.Description": "Правила GST/НДС и интеграция с учетом."
  }
};
