export const branchLocalizationCatalogs: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Branch": "الفرع",
    "Branches": "الفروع",
    "Create Branch": "إنشاء فرع",
    "Create a new branch within current tenant scope.": "إنشاء فرع جديد ضمن نطاق المستأجر الحالي.",
    "Edit Branch": "تعديل الفرع",
    "Update branch profile and status.": "تحديث ملف الفرع وحالته.",
    "Manage operational branches and branch-level setup.": "إدارة الفروع التشغيلية وإعدادات مستوى الفرع.",
    "New Branch": "فرع جديد",
    "Branch created": "تم إنشاء الفرع",
    "Branch updated": "تم تحديث الفرع",
    "Branch deleted": "تم حذف الفرع",
    "Delete branch?": "حذف الفرع؟",
    "Branch Code": "رمز الفرع",
    "Branch Name": "اسم الفرع",
    "Contact Person": "الشخص المسؤول",
    "Country": "الدولة",
    "City": "المدينة",
    "Address": "العنوان",
    "Default Warehouse Id (GUID)": "معرف المستودع الافتراضي (GUID)",
    "Branch Settings": "إعدادات الفرع",
    "Working schedule and branch-specific preferences.": "جدول العمل وتفضيلات الفرع.",
    "Local Time Zone": "المنطقة الزمنية المحلية",
    "Working Days": "أيام العمل",
    "Opening Time": "وقت الفتح",
    "Closing Time": "وقت الإغلاق",
    "Branch settings updated": "تم تحديث إعدادات الفرع",
    "Loading branch...": "جاري تحميل الفرع...",
    "Tenant ID": "معرف المستأجر",
    "Configuration JSON": "إعدادات JSON",
    "Save Branch": "حفظ الفرع",
    "Save Settings": "حفظ الإعدادات"
  },
  "hi-IN": {
    "Branch": "शाखा",
    "Branches": "शाखाएँ",
    "Create Branch": "शाखा बनाएँ",
    "Create a new branch within current tenant scope.": "वर्तमान टेनेंट के अंतर्गत नई शाखा बनाएँ.",
    "Edit Branch": "शाखा संपादित करें",
    "Update branch profile and status.": "शाखा प्रोफ़ाइल और स्थिति अपडेट करें.",
    "Manage operational branches and branch-level setup.": "ऑपरेशनल शाखाएँ और शाखा-स्तर सेटअप प्रबंधित करें.",
    "New Branch": "नई शाखा",
    "Branch created": "शाखा बनाई गई",
    "Branch updated": "शाखा अपडेट की गई",
    "Branch deleted": "शाखा हटाई गई",
    "Delete branch?": "शाखा हटाएँ?",
    "Branch Code": "शाखा कोड",
    "Branch Name": "शाखा नाम",
    "Contact Person": "संपर्क व्यक्ति",
    "Country": "देश",
    "City": "शहर",
    "Address": "पता",
    "Default Warehouse Id (GUID)": "डिफ़ॉल्ट वेयरहाउस आईडी (GUID)",
    "Branch Settings": "शाखा सेटिंग्स",
    "Working schedule and branch-specific preferences.": "कार्य समय-सारणी और शाखा-विशिष्ट प्राथमिकताएँ.",
    "Local Time Zone": "स्थानीय समय क्षेत्र",
    "Working Days": "कार्य दिवस",
    "Opening Time": "खुलने का समय",
    "Closing Time": "बंद होने का समय",
    "Branch settings updated": "शाखा सेटिंग्स अपडेट की गईं",
    "Loading branch...": "शाखा लोड हो रही है...",
    "Tenant ID": "टेनेंट आईडी",
    "Configuration JSON": "कॉन्फ़िगरेशन JSON",
    "Save Branch": "शाखा सहेजें",
    "Save Settings": "सेटिंग्स सहेजें"
  },
  "fr-FR": {
    "Branch": "Agence",
    "Branches": "Agences",
    "Create Branch": "Créer une agence",
    "Create a new branch within current tenant scope.": "Créer une nouvelle agence dans le périmètre du tenant actuel.",
    "Edit Branch": "Modifier l'agence",
    "Update branch profile and status.": "Mettre à jour le profil et le statut de l'agence.",
    "Manage operational branches and branch-level setup.": "Gérer les agences opérationnelles et les paramètres par agence.",
    "New Branch": "Nouvelle agence",
    "Branch created": "Agence créée",
    "Branch updated": "Agence mise à jour",
    "Branch deleted": "Agence supprimée",
    "Delete branch?": "Supprimer l'agence ?",
    "Branch Code": "Code agence",
    "Branch Name": "Nom de l'agence",
    "Contact Person": "Contact principal",
    "Country": "Pays",
    "City": "Ville",
    "Address": "Adresse",
    "Default Warehouse Id (GUID)": "ID entrepôt par défaut (GUID)",
    "Branch Settings": "Paramètres de l'agence",
    "Working schedule and branch-specific preferences.": "Horaires de travail et préférences propres à l'agence.",
    "Local Time Zone": "Fuseau horaire local",
    "Working Days": "Jours ouvrés",
    "Opening Time": "Heure d'ouverture",
    "Closing Time": "Heure de fermeture",
    "Branch settings updated": "Paramètres de l'agence mis à jour",
    "Loading branch...": "Chargement de l'agence...",
    "Tenant ID": "ID tenant",
    "Configuration JSON": "Configuration JSON",
    "Save Branch": "Enregistrer l'agence",
    "Save Settings": "Enregistrer les paramètres"
  },
  "es-ES": {
    "Branch": "Sucursal",
    "Branches": "Sucursales",
    "Create Branch": "Crear sucursal",
    "Create a new branch within current tenant scope.": "Crear una nueva sucursal dentro del tenant actual.",
    "Edit Branch": "Editar sucursal",
    "Update branch profile and status.": "Actualizar el perfil y el estado de la sucursal.",
    "Manage operational branches and branch-level setup.": "Gestionar sucursales operativas y configuración por sucursal.",
    "New Branch": "Nueva sucursal",
    "Branch created": "Sucursal creada",
    "Branch updated": "Sucursal actualizada",
    "Branch deleted": "Sucursal eliminada",
    "Delete branch?": "¿Eliminar sucursal?",
    "Branch Code": "Código de sucursal",
    "Branch Name": "Nombre de sucursal",
    "Contact Person": "Persona de contacto",
    "Country": "País",
    "City": "Ciudad",
    "Address": "Dirección",
    "Default Warehouse Id (GUID)": "ID de almacén predeterminado (GUID)",
    "Branch Settings": "Configuración de sucursal",
    "Working schedule and branch-specific preferences.": "Horario laboral y preferencias específicas de la sucursal.",
    "Local Time Zone": "Zona horaria local",
    "Working Days": "Días laborables",
    "Opening Time": "Hora de apertura",
    "Closing Time": "Hora de cierre",
    "Branch settings updated": "Configuración de sucursal actualizada",
    "Loading branch...": "Cargando sucursal...",
    "Tenant ID": "ID de tenant",
    "Configuration JSON": "Configuración JSON",
    "Save Branch": "Guardar sucursal",
    "Save Settings": "Guardar configuración"
  },
  "zh-CN": {
    "Branch": "分支机构",
    "Branches": "分支机构",
    "Create Branch": "新建分支机构",
    "Create a new branch within current tenant scope.": "在当前租户范围内创建新的分支机构。",
    "Edit Branch": "编辑分支机构",
    "Update branch profile and status.": "更新分支机构资料和状态。",
    "Manage operational branches and branch-level setup.": "管理运营分支机构及分支级设置。",
    "New Branch": "新分支机构",
    "Branch created": "分支机构已创建",
    "Branch updated": "分支机构已更新",
    "Branch deleted": "分支机构已删除",
    "Delete branch?": "删除分支机构？",
    "Branch Code": "分支代码",
    "Branch Name": "分支名称",
    "Contact Person": "联系人",
    "Country": "国家",
    "City": "城市",
    "Address": "地址",
    "Default Warehouse Id (GUID)": "默认仓库 ID (GUID)",
    "Branch Settings": "分支设置",
    "Working schedule and branch-specific preferences.": "工作时间表和分支专属偏好设置。",
    "Local Time Zone": "本地时区",
    "Working Days": "工作日",
    "Opening Time": "营业开始时间",
    "Closing Time": "营业结束时间",
    "Branch settings updated": "分支设置已更新",
    "Loading branch...": "正在加载分支机构...",
    "Tenant ID": "租户 ID",
    "Configuration JSON": "JSON 配置",
    "Save Branch": "保存分支机构",
    "Save Settings": "保存设置"
  },
  "tr-TR": {
    "Branch": "Şube",
    "Branches": "Şubeler",
    "Create Branch": "Şube Oluştur",
    "Create a new branch within current tenant scope.": "Geçerli kiracı kapsamında yeni bir şube oluşturun.",
    "Edit Branch": "Şubeyi Düzenle",
    "Update branch profile and status.": "Şube profilini ve durumunu güncelleyin.",
    "Manage operational branches and branch-level setup.": "Operasyonel şubeleri ve şube düzeyi ayarları yönetin.",
    "New Branch": "Yeni Şube",
    "Branch created": "Şube oluşturuldu",
    "Branch updated": "Şube güncellendi",
    "Branch deleted": "Şube silindi",
    "Delete branch?": "Şube silinsin mi?",
    "Branch Code": "Şube Kodu",
    "Branch Name": "Şube Adı",
    "Contact Person": "İlgili Kişi",
    "Country": "Ülke",
    "City": "Şehir",
    "Address": "Adres",
    "Default Warehouse Id (GUID)": "Varsayılan Depo Kimliği (GUID)",
    "Branch Settings": "Şube Ayarları",
    "Working schedule and branch-specific preferences.": "Çalışma programı ve şubeye özel tercihler.",
    "Local Time Zone": "Yerel Saat Dilimi",
    "Working Days": "Çalışma Günleri",
    "Opening Time": "Açılış Saati",
    "Closing Time": "Kapanış Saati",
    "Branch settings updated": "Şube ayarları güncellendi",
    "Loading branch...": "Şube yükleniyor...",
    "Tenant ID": "Kiracı ID",
    "Configuration JSON": "JSON Yapılandırması",
    "Save Branch": "Şubeyi Kaydet",
    "Save Settings": "Ayarları Kaydet"
  },
  "pt-PT": {
    "Branch": "Filial",
    "Branches": "Filiais",
    "Create Branch": "Criar filial",
    "Create a new branch within current tenant scope.": "Criar uma nova filial no âmbito do tenant atual.",
    "Edit Branch": "Editar filial",
    "Update branch profile and status.": "Atualizar o perfil e o estado da filial.",
    "Manage operational branches and branch-level setup.": "Gerir filiais operacionais e configurações ao nível da filial.",
    "New Branch": "Nova filial",
    "Branch created": "Filial criada",
    "Branch updated": "Filial atualizada",
    "Branch deleted": "Filial eliminada",
    "Delete branch?": "Eliminar filial?",
    "Branch Code": "Código da filial",
    "Branch Name": "Nome da filial",
    "Contact Person": "Pessoa de contacto",
    "Country": "País",
    "City": "Cidade",
    "Address": "Morada",
    "Default Warehouse Id (GUID)": "ID do armazém predefinido (GUID)",
    "Branch Settings": "Definições da filial",
    "Working schedule and branch-specific preferences.": "Horário de trabalho e preferências específicas da filial.",
    "Local Time Zone": "Fuso horário local",
    "Working Days": "Dias úteis",
    "Opening Time": "Hora de abertura",
    "Closing Time": "Hora de fecho",
    "Branch settings updated": "Definições da filial atualizadas",
    "Loading branch...": "A carregar filial...",
    "Tenant ID": "ID do tenant",
    "Configuration JSON": "Configuração JSON",
    "Save Branch": "Guardar filial",
    "Save Settings": "Guardar definições"
  },
  "ru-RU": {
    "Branch": "Филиал",
    "Branches": "Филиалы",
    "Create Branch": "Создать филиал",
    "Create a new branch within current tenant scope.": "Создать новый филиал в рамках текущего тенанта.",
    "Edit Branch": "Редактировать филиал",
    "Update branch profile and status.": "Обновить профиль и статус филиала.",
    "Manage operational branches and branch-level setup.": "Управление операционными филиалами и настройками филиала.",
    "New Branch": "Новый филиал",
    "Branch created": "Филиал создан",
    "Branch updated": "Филиал обновлен",
    "Branch deleted": "Филиал удален",
    "Delete branch?": "Удалить филиал?",
    "Branch Code": "Код филиала",
    "Branch Name": "Название филиала",
    "Contact Person": "Контактное лицо",
    "Country": "Страна",
    "City": "Город",
    "Address": "Адрес",
    "Default Warehouse Id (GUID)": "ID склада по умолчанию (GUID)",
    "Branch Settings": "Настройки филиала",
    "Working schedule and branch-specific preferences.": "Рабочий график и настройки, относящиеся к филиалу.",
    "Local Time Zone": "Местный часовой пояс",
    "Working Days": "Рабочие дни",
    "Opening Time": "Время открытия",
    "Closing Time": "Время закрытия",
    "Branch settings updated": "Настройки филиала обновлены",
    "Loading branch...": "Загрузка филиала...",
    "Tenant ID": "ID тенанта",
    "Configuration JSON": "Конфигурация JSON",
    "Save Branch": "Сохранить филиал",
    "Save Settings": "Сохранить настройки"
  }
};
