export const branchBankLocalizationCatalogs: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Currency Bank Details": "تفاصيل البنك حسب العملة",
    "Configure separate bank details for any currency used by this branch.": "قم بإعداد تفاصيل بنك منفصلة لأي عملة يستخدمها هذا الفرع.",
    "Bank Details": "تفاصيل البنك",
    "Add Bank Details": "إضافة تفاصيل البنك",
    "Edit Bank Details": "تعديل تفاصيل البنك",
    "Save Bank Details": "حفظ تفاصيل البنك",
    "Beneficiary Name": "اسم المستفيد",
    "Bank Name": "اسم البنك",
    "Swift Code": "رمز سويفت",
    "Account No": "رقم الحساب",
    "IBAN": "رقم الآيبان",
    "No active currencies are available.": "لا توجد عملات نشطة متاحة."
  },
  "hi-IN": {
    "Currency Bank Details": "मुद्रा बैंक विवरण",
    "Configure separate bank details for any currency used by this branch.": "इस शाखा द्वारा उपयोग की जाने वाली किसी भी मुद्रा के लिए अलग बैंक विवरण सेट करें।",
    "Bank Details": "बैंक विवरण",
    "Add Bank Details": "बैंक विवरण जोड़ें",
    "Edit Bank Details": "बैंक विवरण संपादित करें",
    "Save Bank Details": "बैंक विवरण सहेजें",
    "Beneficiary Name": "लाभार्थी का नाम",
    "Bank Name": "बैंक का नाम",
    "Swift Code": "स्विफ्ट कोड",
    "Account No": "खाता संख्या",
    "IBAN": "आईबीएएन",
    "No active currencies are available.": "कोई सक्रिय मुद्रा उपलब्ध नहीं है।"
  },
  "fr-FR": {
    "Currency Bank Details": "Coordonnées bancaires par devise",
    "Configure separate bank details for any currency used by this branch.": "Configurez des coordonnées bancaires distinctes pour toute devise utilisée par cette agence.",
    "Bank Details": "Coordonnées bancaires",
    "Add Bank Details": "Ajouter les coordonnées bancaires",
    "Edit Bank Details": "Modifier les coordonnées bancaires",
    "Save Bank Details": "Enregistrer les coordonnées bancaires",
    "Beneficiary Name": "Nom du bénéficiaire",
    "Bank Name": "Nom de la banque",
    "Swift Code": "Code SWIFT",
    "Account No": "Numéro de compte",
    "IBAN": "IBAN",
    "No active currencies are available.": "Aucune devise active n'est disponible."
  },
  "es-ES": {
    "Currency Bank Details": "Datos bancarios por moneda",
    "Configure separate bank details for any currency used by this branch.": "Configure datos bancarios independientes para cualquier moneda utilizada por esta sucursal.",
    "Bank Details": "Datos bancarios",
    "Add Bank Details": "Agregar datos bancarios",
    "Edit Bank Details": "Editar datos bancarios",
    "Save Bank Details": "Guardar datos bancarios",
    "Beneficiary Name": "Nombre del beneficiario",
    "Bank Name": "Nombre del banco",
    "Swift Code": "Código SWIFT",
    "Account No": "Número de cuenta",
    "IBAN": "IBAN",
    "No active currencies are available.": "No hay monedas activas disponibles."
  },
  "zh-CN": {
    "Currency Bank Details": "各币种银行信息",
    "Configure separate bank details for any currency used by this branch.": "为此分支机构使用的任何币种配置独立的银行信息。",
    "Bank Details": "银行信息",
    "Add Bank Details": "添加银行信息",
    "Edit Bank Details": "编辑银行信息",
    "Save Bank Details": "保存银行信息",
    "Beneficiary Name": "收款人名称",
    "Bank Name": "银行名称",
    "Swift Code": "SWIFT 代码",
    "Account No": "账号",
    "IBAN": "IBAN",
    "No active currencies are available.": "没有可用的有效币种。"
  },
  "tr-TR": {
    "Currency Bank Details": "Para Birimi Banka Bilgileri",
    "Configure separate bank details for any currency used by this branch.": "Bu şubenin kullandığı herhangi bir para birimi için ayrı banka bilgileri yapılandırın.",
    "Bank Details": "Banka Bilgileri",
    "Add Bank Details": "Banka Bilgisi Ekle",
    "Edit Bank Details": "Banka Bilgilerini Düzenle",
    "Save Bank Details": "Banka Bilgilerini Kaydet",
    "Beneficiary Name": "Lehtar Adı",
    "Bank Name": "Banka Adı",
    "Swift Code": "SWIFT Kodu",
    "Account No": "Hesap No",
    "IBAN": "IBAN",
    "No active currencies are available.": "Aktif para birimi bulunmuyor."
  },
  "pt-PT": {
    "Currency Bank Details": "Dados bancários por moeda",
    "Configure separate bank details for any currency used by this branch.": "Configure dados bancários separados para qualquer moeda utilizada nesta filial.",
    "Bank Details": "Dados bancários",
    "Add Bank Details": "Adicionar dados bancários",
    "Edit Bank Details": "Editar dados bancários",
    "Save Bank Details": "Guardar dados bancários",
    "Beneficiary Name": "Nome do beneficiário",
    "Bank Name": "Nome do banco",
    "Swift Code": "Código SWIFT",
    "Account No": "Número da conta",
    "IBAN": "IBAN",
    "No active currencies are available.": "Não existem moedas ativas disponíveis."
  },
  "ru-RU": {
    "Currency Bank Details": "Банковские реквизиты по валютам",
    "Configure separate bank details for any currency used by this branch.": "Настройте отдельные банковские реквизиты для любой валюты, используемой в этом филиале.",
    "Bank Details": "Банковские реквизиты",
    "Add Bank Details": "Добавить банковские реквизиты",
    "Edit Bank Details": "Изменить банковские реквизиты",
    "Save Bank Details": "Сохранить банковские реквизиты",
    "Beneficiary Name": "Наименование получателя",
    "Bank Name": "Наименование банка",
    "Swift Code": "Код SWIFT",
    "Account No": "Номер счета",
    "IBAN": "IBAN",
    "No active currencies are available.": "Нет доступных активных валют."
  }
};
