export const settingsLocalizationCatalogs: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Approval Workflow Designer": "مصمم سير الموافقات",
    "Approval Workflows": "سير الموافقات",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "إنشاء مسارات موافقة حسب الدور والمبلغ مع قواعد اختيارية للملاحظات وسبب الرفض.",
    "Configure single-level and multi-level approval flows with role and amount rules.": "إعداد سير موافقة من مستوى واحد أو عدة مستويات حسب الدور والمبلغ.",
    "Approval Levels": "مستويات الموافقة",
    "Approval Mode": "وضع الموافقة",
    "Single-Level Approval": "موافقة مستوى واحد",
    "Multi-Level Approval": "موافقة متعددة المستويات",
    "Workflow Name": "اسم سير الموافقة",
    "Active workflow": "سير موافقة نشط",
    "Remarks required": "الملاحظات مطلوبة",
    "Rejection reason required": "سبب الرفض مطلوب",
    "All approvers": "كل المعتمدين",
    "Add Level": "إضافة مستوى",
    "Save Workflow": "حفظ سير الموافقة",
    "New Workflow": "سير موافقة جديد",
    "Delete approval workflow?": "حذف سير الموافقة؟",
    "Remarks Req.": "الملاحظات مطلوبة",
    "Numbering Settings": "إعدادات الترقيم",
    "Configure tenant and branch document numbering formats and reset rules.": "إعداد صيغ ترقيم مستندات المستأجر والفرع وقواعد إعادة التعيين.",
    "Module (e.g. Invoice)": "الوحدة (مثال: فاتورة)",
    "Format Preview": "معاينة الصيغة",
    "Digit Length": "عدد الخانات",
    "Next No.": "الرقم التالي",
    "Next Number": "الرقم التالي",
    "All Branches": "كل الفروع",
    "Add Format": "إضافة صيغة",
    "Update Format": "تحديث الصيغة",
    "Cancel Edit": "إلغاء التعديل",
    "Save All Changes": "حفظ كل التغييرات",
    "Remove numbering format?": "إزالة صيغة الترقيم؟",
    "Print Templates": "قوالب الطباعة",
    "Print Template Designer": "مصمم قالب الطباعة",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "إدارة تخطيطات طباعة تحمل الهوية مع متغيرات ديناميكية ودعم متعدد اللغات.",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "تصميم قوالب طباعة حسب اللغة مع متغيرات وهوية ودعم الباركود وQR.",
    "New Print Template": "قالب طباعة جديد",
    "Delete print template?": "حذف قالب الطباعة؟",
    "Template Code": "رمز القالب",
    "Template Name": "اسم القالب",
    "Header Template": "قالب الرأس",
    "Body Template": "قالب المحتوى",
    "Footer Template": "قالب التذييل",
    "Page Size": "حجم الصفحة",
    "Orientation": "الاتجاه",
    "Portrait": "عمودي",
    "Landscape": "أفقي",
    "Letter": "Letter",
    "Legal": "Legal",
    "Custom": "مخصص",
    "Tenant Logo": "شعار المستأجر",
    "TENANT LOGO": "شعار المستأجر",
    "Save Template": "حفظ القالب",
    "Placeholders": "المتغيرات",
    "Label Templates": "قوالب الملصقات",
    "Label Template Designer": "مصمم قالب الملصق",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "ملصقات شحن حسب الوجهة مع باركود وQR ومحتوى حسب اللغة.",
    "Design barcode/QR-ready label templates with destination and language variants.": "تصميم قوالب ملصقات جاهزة للباركود وQR حسب الوجهة واللغة.",
    "New Label Template": "قالب ملصق جديد",
    "Delete label template?": "حذف قالب الملصق؟",
    "Destination Code": "رمز الوجهة",
    "Label Width (mm)": "عرض الملصق (مم)",
    "Label Height (mm)": "ارتفاع الملصق (مم)",
    "Label Preview": "معاينة الملصق",
    "Default Template": "القالب الافتراضي",
    "e.g. DXB, LHR, SIN": "مثال: DXB، LHR، SIN",
    "Tenant context is required to design approval workflows.": "سياق المستأجر مطلوب لتصميم سير الموافقات.",
    "Tenant context is required to manage approval workflows.": "سياق المستأجر مطلوب لإدارة سير الموافقات.",
    "Tenant context is required to manage numbering settings.": "سياق المستأجر مطلوب لإدارة إعدادات الترقيم.",
    "Tenant context is required to design print templates.": "سياق المستأجر مطلوب لتصميم قوالب الطباعة.",
    "Tenant context is required to manage print templates.": "سياق المستأجر مطلوب لإدارة قوالب الطباعة.",
    "Tenant context is required to design label templates.": "سياق المستأجر مطلوب لتصميم قوالب الملصقات.",
    "Tenant context is required to manage label templates.": "سياق المستأجر مطلوب لإدارة قوالب الملصقات.",
    "Invoice, VendorBill, Payment...": "فاتورة، فاتورة مورد، دفعة..."
    ,"SingleLevel": "مستوى واحد"
    ,"MultiLevel": "متعدد المستويات"
    ,"Never": "أبداً"
    ,"Yearly": "سنوي"
    ,"Monthly": "شهري"
    ,"Daily": "يومي"
  },
  "hi-IN": {
    "Approval Workflow Designer": "अनुमोदन वर्कफ़्लो डिज़ाइनर",
    "Approval Workflows": "अनुमोदन वर्कफ़्लो",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "भूमिका और राशि आधारित अनुमोदन प्रक्रिया बनाएं, वैकल्पिक टिप्पणी और अस्वीकृति नियमों सहित।",
    "Configure single-level and multi-level approval flows with role and amount rules.": "भूमिका और राशि नियमों के साथ एकल और बहु-स्तरीय अनुमोदन प्रवाह सेट करें।",
    "Approval Levels": "अनुमोदन स्तर",
    "Approval Mode": "अनुमोदन मोड",
    "Single-Level Approval": "एकल-स्तरीय अनुमोदन",
    "Multi-Level Approval": "बहु-स्तरीय अनुमोदन",
    "Workflow Name": "वर्कफ़्लो नाम",
    "Active workflow": "सक्रिय वर्कफ़्लो",
    "Remarks required": "टिप्पणी आवश्यक",
    "Rejection reason required": "अस्वीकृति कारण आवश्यक",
    "All approvers": "सभी अनुमोदक",
    "Add Level": "स्तर जोड़ें",
    "Save Workflow": "वर्कफ़्लो सहेजें",
    "New Workflow": "नया वर्कफ़्लो",
    "Delete approval workflow?": "अनुमोदन वर्कफ़्लो हटाएं?",
    "Remarks Req.": "टिप्पणी आवश्यक",
    "Numbering Settings": "नंबरिंग सेटिंग्स",
    "Configure tenant and branch document numbering formats and reset rules.": "टेनेंट और शाखा दस्तावेज़ नंबरिंग प्रारूप और रीसेट नियम सेट करें।",
    "Module (e.g. Invoice)": "मॉड्यूल (जैसे इनवॉइस)",
    "Format Preview": "प्रारूप पूर्वावलोकन",
    "Digit Length": "अंकों की लंबाई",
    "Next No.": "अगला नं.",
    "Next Number": "अगला नंबर",
    "All Branches": "सभी शाखाएं",
    "Add Format": "प्रारूप जोड़ें",
    "Update Format": "प्रारूप अपडेट करें",
    "Cancel Edit": "संपादन रद्द करें",
    "Save All Changes": "सभी बदलाव सहेजें",
    "Remove numbering format?": "नंबरिंग प्रारूप हटाएं?",
    "Print Templates": "प्रिंट टेम्पलेट",
    "Print Template Designer": "प्रिंट टेम्पलेट डिज़ाइनर",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "डायनामिक प्लेसहोल्डर और बहुभाषी समर्थन वाले ब्रांडेड प्रिंट लेआउट बनाए रखें।",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "प्लेसहोल्डर, ब्रांडिंग और बारकोड/QR समर्थन के साथ भाषा-आधारित प्रिंट टेम्पलेट डिज़ाइन करें।",
    "New Print Template": "नया प्रिंट टेम्पलेट",
    "Delete print template?": "प्रिंट टेम्पलेट हटाएं?",
    "Template Code": "टेम्पलेट कोड",
    "Template Name": "टेम्पलेट नाम",
    "Header Template": "हेडर टेम्पलेट",
    "Body Template": "बॉडी टेम्पलेट",
    "Footer Template": "फुटर टेम्पलेट",
    "Page Size": "पेज आकार",
    "Orientation": "ओरिएंटेशन",
    "Portrait": "पोर्ट्रेट",
    "Landscape": "लैंडस्केप",
    "Letter": "लेटर",
    "Legal": "लीगल",
    "Custom": "कस्टम",
    "Tenant Logo": "टेनेंट लोगो",
    "TENANT LOGO": "टेनेंट लोगो",
    "Save Template": "टेम्पलेट सहेजें",
    "Placeholders": "प्लेसहोल्डर",
    "Label Templates": "लेबल टेम्पलेट",
    "Label Template Designer": "लेबल टेम्पलेट डिज़ाइनर",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "गंतव्य-विशिष्ट शिपमेंट लेबल, बारकोड/QR और भाषा-विशिष्ट सामग्री के साथ।",
    "Design barcode/QR-ready label templates with destination and language variants.": "गंतव्य और भाषा विकल्पों के साथ बारकोड/QR तैयार लेबल टेम्पलेट डिज़ाइन करें।",
    "New Label Template": "नया लेबल टेम्पलेट",
    "Delete label template?": "लेबल टेम्पलेट हटाएं?",
    "Destination Code": "गंतव्य कोड",
    "Label Width (mm)": "लेबल चौड़ाई (मिमी)",
    "Label Height (mm)": "लेबल ऊंचाई (मिमी)",
    "Label Preview": "लेबल पूर्वावलोकन",
    "Default Template": "डिफ़ॉल्ट टेम्पलेट",
    "e.g. DXB, LHR, SIN": "जैसे DXB, LHR, SIN",
    "Tenant context is required to design approval workflows.": "अनुमोदन वर्कफ़्लो डिज़ाइन करने के लिए टेनेंट संदर्भ आवश्यक है।",
    "Tenant context is required to manage approval workflows.": "अनुमोदन वर्कफ़्लो प्रबंधित करने के लिए टेनेंट संदर्भ आवश्यक है।",
    "Tenant context is required to manage numbering settings.": "नंबरिंग सेटिंग्स प्रबंधित करने के लिए टेनेंट संदर्भ आवश्यक है।",
    "Tenant context is required to design print templates.": "प्रिंट टेम्पलेट डिज़ाइन करने के लिए टेनेंट संदर्भ आवश्यक है।",
    "Tenant context is required to manage print templates.": "प्रिंट टेम्पलेट प्रबंधित करने के लिए टेनेंट संदर्भ आवश्यक है।",
    "Tenant context is required to design label templates.": "लेबल टेम्पलेट डिज़ाइन करने के लिए टेनेंट संदर्भ आवश्यक है।",
    "Tenant context is required to manage label templates.": "लेबल टेम्पलेट प्रबंधित करने के लिए टेनेंट संदर्भ आवश्यक है।",
    "Invoice, VendorBill, Payment...": "इनवॉइस, विक्रेता बिल, भुगतान..."
    ,"SingleLevel": "एकल स्तर"
    ,"MultiLevel": "बहु स्तर"
    ,"Never": "कभी नहीं"
    ,"Yearly": "वार्षिक"
    ,"Monthly": "मासिक"
    ,"Daily": "दैनिक"
  },
  "fr-FR": {
    "Approval Workflow Designer": "Concepteur de workflow d'approbation",
    "Approval Workflows": "Workflows d'approbation",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "Créer des circuits d'approbation par rôle et montant avec règles de remarque/rejet optionnelles.",
    "Configure single-level and multi-level approval flows with role and amount rules.": "Configurer des circuits d'approbation à un ou plusieurs niveaux avec règles de rôle et de montant.",
    "Approval Levels": "Niveaux d'approbation",
    "Approval Mode": "Mode d'approbation",
    "Single-Level Approval": "Approbation à un niveau",
    "Multi-Level Approval": "Approbation multi-niveaux",
    "Workflow Name": "Nom du workflow",
    "Active workflow": "Workflow actif",
    "Remarks required": "Remarques obligatoires",
    "Rejection reason required": "Motif de rejet obligatoire",
    "All approvers": "Tous les approbateurs",
    "Add Level": "Ajouter un niveau",
    "Save Workflow": "Enregistrer le workflow",
    "New Workflow": "Nouveau workflow",
    "Delete approval workflow?": "Supprimer le workflow d'approbation ?",
    "Remarks Req.": "Remarques req.",
    "Numbering Settings": "Paramètres de numérotation",
    "Configure tenant and branch document numbering formats and reset rules.": "Configurer les formats de numérotation des documents par tenant/agence et les règles de réinitialisation.",
    "Module (e.g. Invoice)": "Module (ex. facture)",
    "Format Preview": "Aperçu du format",
    "Digit Length": "Longueur numérique",
    "Next No.": "N° suivant",
    "Next Number": "Numéro suivant",
    "All Branches": "Toutes les agences",
    "Add Format": "Ajouter un format",
    "Update Format": "Mettre à jour le format",
    "Cancel Edit": "Annuler la modification",
    "Save All Changes": "Enregistrer toutes les modifications",
    "Remove numbering format?": "Supprimer le format de numérotation ?",
    "Print Templates": "Modèles d'impression",
    "Print Template Designer": "Concepteur de modèle d'impression",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "Gérer des mises en page d'impression avec identité, champs dynamiques et support multilingue.",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "Concevoir des modèles d'impression par langue avec champs dynamiques, identité et support code-barres/QR.",
    "New Print Template": "Nouveau modèle d'impression",
    "Delete print template?": "Supprimer le modèle d'impression ?",
    "Template Code": "Code du modèle",
    "Template Name": "Nom du modèle",
    "Header Template": "Modèle d'en-tête",
    "Body Template": "Modèle de corps",
    "Footer Template": "Modèle de pied",
    "Page Size": "Format de page",
    "Orientation": "Orientation",
    "Portrait": "Portrait",
    "Landscape": "Paysage",
    "Letter": "Lettre",
    "Legal": "Legal",
    "Custom": "Personnalisé",
    "Tenant Logo": "Logo du tenant",
    "TENANT LOGO": "LOGO DU TENANT",
    "Save Template": "Enregistrer le modèle",
    "Placeholders": "Champs dynamiques",
    "Label Templates": "Modèles d'étiquette",
    "Label Template Designer": "Concepteur de modèle d'étiquette",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "Étiquettes d'expédition par destination avec code-barres/QR et contenu par langue.",
    "Design barcode/QR-ready label templates with destination and language variants.": "Concevoir des modèles d'étiquette prêts pour code-barres/QR par destination et langue.",
    "New Label Template": "Nouveau modèle d'étiquette",
    "Delete label template?": "Supprimer le modèle d'étiquette ?",
    "Destination Code": "Code destination",
    "Label Width (mm)": "Largeur étiquette (mm)",
    "Label Height (mm)": "Hauteur étiquette (mm)",
    "Label Preview": "Aperçu de l'étiquette",
    "Default Template": "Modèle par défaut",
    "e.g. DXB, LHR, SIN": "ex. DXB, LHR, SIN",
    "Tenant context is required to design approval workflows.": "Le contexte tenant est requis pour concevoir les workflows d'approbation.",
    "Tenant context is required to manage approval workflows.": "Le contexte tenant est requis pour gérer les workflows d'approbation.",
    "Tenant context is required to manage numbering settings.": "Le contexte tenant est requis pour gérer les paramètres de numérotation.",
    "Tenant context is required to design print templates.": "Le contexte tenant est requis pour concevoir les modèles d'impression.",
    "Tenant context is required to manage print templates.": "Le contexte tenant est requis pour gérer les modèles d'impression.",
    "Tenant context is required to design label templates.": "Le contexte tenant est requis pour concevoir les modèles d'étiquette.",
    "Tenant context is required to manage label templates.": "Le contexte tenant est requis pour gérer les modèles d'étiquette.",
    "Invoice, VendorBill, Payment...": "Facture, facture fournisseur, paiement..."
    ,"SingleLevel": "Un niveau"
    ,"MultiLevel": "Multi-niveaux"
    ,"Never": "Jamais"
    ,"Yearly": "Annuel"
    ,"Monthly": "Mensuel"
    ,"Daily": "Quotidien"
  },
  "es-ES": {
    "Approval Workflow Designer": "Diseñador de flujo de aprobación",
    "Approval Workflows": "Flujos de aprobación",
    "Numbering Settings": "Configuración de numeración",
    "Print Templates": "Plantillas de impresión",
    "Print Template Designer": "Diseñador de plantilla de impresión",
    "Label Templates": "Plantillas de etiqueta",
    "Label Template Designer": "Diseñador de plantilla de etiqueta",
    "Workflow Name": "Nombre del flujo",
    "Approval Levels": "Niveles de aprobación",
    "Approval Mode": "Modo de aprobación",
    "Single-Level Approval": "Aprobación de un nivel",
    "Multi-Level Approval": "Aprobación multinivel",
    "Remarks required": "Observaciones obligatorias",
    "Rejection reason required": "Motivo de rechazo obligatorio",
    "All approvers": "Todos los aprobadores",
    "Add Level": "Añadir nivel",
    "Save Workflow": "Guardar flujo",
    "New Workflow": "Nuevo flujo",
    "Delete approval workflow?": "¿Eliminar flujo de aprobación?",
    "Format Preview": "Vista previa del formato",
    "Digit Length": "Longitud de dígitos",
    "Next No.": "N.º siguiente",
    "Next Number": "Número siguiente",
    "All Branches": "Todas las sucursales",
    "Add Format": "Añadir formato",
    "Update Format": "Actualizar formato",
    "Cancel Edit": "Cancelar edición",
    "Save All Changes": "Guardar todos los cambios",
    "Remove numbering format?": "¿Eliminar formato de numeración?",
    "New Print Template": "Nueva plantilla de impresión",
    "Delete print template?": "¿Eliminar plantilla de impresión?",
    "Template Code": "Código de plantilla",
    "Template Name": "Nombre de plantilla",
    "Header Template": "Plantilla de encabezado",
    "Body Template": "Plantilla del cuerpo",
    "Footer Template": "Plantilla de pie",
    "Page Size": "Tamaño de página",
    "Orientation": "Orientación",
    "Portrait": "Vertical",
    "Landscape": "Horizontal",
    "Custom": "Personalizado",
    "Tenant Logo": "Logo del tenant",
    "TENANT LOGO": "LOGO DEL TENANT",
    "Save Template": "Guardar plantilla",
    "Placeholders": "Marcadores",
    "New Label Template": "Nueva plantilla de etiqueta",
    "Delete label template?": "¿Eliminar plantilla de etiqueta?",
    "Destination Code": "Código de destino",
    "Label Width (mm)": "Ancho de etiqueta (mm)",
    "Label Height (mm)": "Alto de etiqueta (mm)",
    "Label Preview": "Vista previa de etiqueta",
    "Default Template": "Plantilla predeterminada",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "Cree procesos de aprobación por rol e importe con reglas opcionales de observaciones y rechazo.",
    "Configure single-level and multi-level approval flows with role and amount rules.": "Configure aprobaciones de uno o varios niveles con reglas de rol e importe.",
    "Configure tenant and branch document numbering formats and reset rules.": "Configure formatos de numeración de documentos por tenant y sucursal y reglas de reinicio.",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "Mantenga diseños de impresión de marca con marcadores dinámicos y soporte multilingüe.",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "Diseñe plantillas por idioma con marcadores, marca y soporte de código de barras/QR.",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "Etiquetas de envío por destino con código de barras/QR y contenido por idioma.",
    "Design barcode/QR-ready label templates with destination and language variants.": "Diseñe plantillas de etiqueta listas para código de barras/QR por destino e idioma.",
    "e.g. DXB, LHR, SIN": "p. ej. DXB, LHR, SIN",
    "Tenant context is required to design approval workflows.": "Se requiere contexto de tenant para diseñar flujos de aprobación.",
    "Tenant context is required to manage approval workflows.": "Se requiere contexto de tenant para gestionar flujos de aprobación.",
    "Tenant context is required to manage numbering settings.": "Se requiere contexto de tenant para gestionar la numeración.",
    "Tenant context is required to design print templates.": "Se requiere contexto de tenant para diseñar plantillas de impresión.",
    "Tenant context is required to manage print templates.": "Se requiere contexto de tenant para gestionar plantillas de impresión.",
    "Tenant context is required to design label templates.": "Se requiere contexto de tenant para diseñar plantillas de etiqueta.",
    "Tenant context is required to manage label templates.": "Se requiere contexto de tenant para gestionar plantillas de etiqueta.",
    "Invoice, VendorBill, Payment...": "Factura, factura de proveedor, pago..."
    ,"SingleLevel": "Un nivel"
    ,"MultiLevel": "Multinivel"
    ,"Never": "Nunca"
    ,"Yearly": "Anual"
    ,"Monthly": "Mensual"
    ,"Daily": "Diario"
  },
  "zh-CN": {
    "Approval Workflow Designer": "审批流程设计器",
    "Approval Workflows": "审批流程",
    "Numbering Settings": "编号设置",
    "Print Templates": "打印模板",
    "Print Template Designer": "打印模板设计器",
    "Label Templates": "标签模板",
    "Label Template Designer": "标签模板设计器",
    "Workflow Name": "流程名称",
    "Approval Levels": "审批级别",
    "Approval Mode": "审批模式",
    "Single-Level Approval": "单级审批",
    "Multi-Level Approval": "多级审批",
    "Remarks required": "需要备注",
    "Rejection reason required": "需要拒绝原因",
    "All approvers": "所有审批人",
    "Add Level": "添加级别",
    "Save Workflow": "保存流程",
    "New Workflow": "新建流程",
    "Delete approval workflow?": "删除审批流程？",
    "Format Preview": "格式预览",
    "Digit Length": "位数",
    "Next No.": "下一个编号",
    "Next Number": "下一个号码",
    "All Branches": "所有分支机构",
    "Add Format": "添加格式",
    "Update Format": "更新格式",
    "Cancel Edit": "取消编辑",
    "Save All Changes": "保存所有更改",
    "Remove numbering format?": "移除编号格式？",
    "New Print Template": "新建打印模板",
    "Delete print template?": "删除打印模板？",
    "Template Code": "模板代码",
    "Template Name": "模板名称",
    "Header Template": "页眉模板",
    "Body Template": "正文模板",
    "Footer Template": "页脚模板",
    "Page Size": "页面尺寸",
    "Orientation": "方向",
    "Portrait": "纵向",
    "Landscape": "横向",
    "Custom": "自定义",
    "Tenant Logo": "租户标志",
    "TENANT LOGO": "租户标志",
    "Save Template": "保存模板",
    "Placeholders": "占位符",
    "New Label Template": "新建标签模板",
    "Delete label template?": "删除标签模板？",
    "Destination Code": "目的地代码",
    "Label Width (mm)": "标签宽度 (mm)",
    "Label Height (mm)": "标签高度 (mm)",
    "Label Preview": "标签预览",
    "Default Template": "默认模板",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "构建基于角色和金额的审批流程，并支持可选备注和拒绝规则。",
    "Configure single-level and multi-level approval flows with role and amount rules.": "配置基于角色和金额规则的单级和多级审批流程。",
    "Configure tenant and branch document numbering formats and reset rules.": "配置租户和分支机构的单据编号格式及重置规则。",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "维护带品牌、动态占位符和多语言支持的打印布局。",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "设计支持语言、占位符、品牌和条码/二维码的打印模板。",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "按目的地生成带条码/二维码和语言内容的货运标签。",
    "Design barcode/QR-ready label templates with destination and language variants.": "设计按目的地和语言区分的条码/二维码标签模板。",
    "e.g. DXB, LHR, SIN": "例如 DXB、LHR、SIN",
    "Tenant context is required to design approval workflows.": "设计审批流程需要租户上下文。",
    "Tenant context is required to manage approval workflows.": "管理审批流程需要租户上下文。",
    "Tenant context is required to manage numbering settings.": "管理编号设置需要租户上下文。",
    "Tenant context is required to design print templates.": "设计打印模板需要租户上下文。",
    "Tenant context is required to manage print templates.": "管理打印模板需要租户上下文。",
    "Tenant context is required to design label templates.": "设计标签模板需要租户上下文。",
    "Tenant context is required to manage label templates.": "管理标签模板需要租户上下文。",
    "Invoice, VendorBill, Payment...": "发票、供应商账单、付款..."
    ,"SingleLevel": "单级"
    ,"MultiLevel": "多级"
    ,"Never": "从不"
    ,"Yearly": "每年"
    ,"Monthly": "每月"
    ,"Daily": "每日"
  },
  "tr-TR": {
    "Approval Workflow Designer": "Onay iş akışı tasarımcısı",
    "Approval Workflows": "Onay iş akışları",
    "Numbering Settings": "Numaralandırma ayarları",
    "Print Templates": "Yazdırma şablonları",
    "Print Template Designer": "Yazdırma şablonu tasarımcısı",
    "Label Templates": "Etiket şablonları",
    "Label Template Designer": "Etiket şablonu tasarımcısı",
    "Workflow Name": "İş akışı adı",
    "Approval Levels": "Onay seviyeleri",
    "Approval Mode": "Onay modu",
    "Single-Level Approval": "Tek seviyeli onay",
    "Multi-Level Approval": "Çok seviyeli onay",
    "Remarks required": "Açıklama zorunlu",
    "Rejection reason required": "Ret nedeni zorunlu",
    "All approvers": "Tüm onaylayanlar",
    "Add Level": "Seviye ekle",
    "Save Workflow": "İş akışını kaydet",
    "New Workflow": "Yeni iş akışı",
    "Delete approval workflow?": "Onay iş akışı silinsin mi?",
    "Format Preview": "Format önizleme",
    "Digit Length": "Hane uzunluğu",
    "Next No.": "Sonraki no",
    "Next Number": "Sonraki numara",
    "All Branches": "Tüm şubeler",
    "Add Format": "Format ekle",
    "Update Format": "Formatı güncelle",
    "Cancel Edit": "Düzenlemeyi iptal et",
    "Save All Changes": "Tüm değişiklikleri kaydet",
    "Remove numbering format?": "Numaralandırma formatı kaldırılsın mı?",
    "New Print Template": "Yeni yazdırma şablonu",
    "Delete print template?": "Yazdırma şablonu silinsin mi?",
    "Template Code": "Şablon kodu",
    "Template Name": "Şablon adı",
    "Header Template": "Üst bilgi şablonu",
    "Body Template": "Gövde şablonu",
    "Footer Template": "Alt bilgi şablonu",
    "Page Size": "Sayfa boyutu",
    "Orientation": "Yön",
    "Portrait": "Dikey",
    "Landscape": "Yatay",
    "Custom": "Özel",
    "Tenant Logo": "Kiracı logosu",
    "TENANT LOGO": "KİRACI LOGOSU",
    "Save Template": "Şablonu kaydet",
    "Placeholders": "Yer tutucular",
    "New Label Template": "Yeni etiket şablonu",
    "Delete label template?": "Etiket şablonu silinsin mi?",
    "Destination Code": "Varış kodu",
    "Label Width (mm)": "Etiket genişliği (mm)",
    "Label Height (mm)": "Etiket yüksekliği (mm)",
    "Label Preview": "Etiket önizleme",
    "Default Template": "Varsayılan şablon",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "Rol ve tutar bazlı onay süreçlerini isteğe bağlı açıklama/ret kurallarıyla oluşturun.",
    "Configure single-level and multi-level approval flows with role and amount rules.": "Rol ve tutar kurallarıyla tek ve çok seviyeli onay akışlarını yapılandırın.",
    "Configure tenant and branch document numbering formats and reset rules.": "Kiracı ve şube belge numaralandırma formatlarını ve sıfırlama kurallarını yapılandırın.",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "Dinamik yer tutucular ve çok dilli destek içeren markalı yazdırma düzenlerini yönetin.",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "Yer tutucular, marka öğeleri ve barkod/QR desteğiyle dile duyarlı yazdırma şablonları tasarlayın.",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "Barkod/QR ve dile özel içerikle varış noktasına özel sevkiyat etiketleri.",
    "Design barcode/QR-ready label templates with destination and language variants.": "Varış noktası ve dil varyantlarıyla barkod/QR hazır etiket şablonları tasarlayın.",
    "e.g. DXB, LHR, SIN": "örn. DXB, LHR, SIN",
    "Tenant context is required to design approval workflows.": "Onay iş akışlarını tasarlamak için kiracı bağlamı gereklidir.",
    "Tenant context is required to manage approval workflows.": "Onay iş akışlarını yönetmek için kiracı bağlamı gereklidir.",
    "Tenant context is required to manage numbering settings.": "Numaralandırma ayarlarını yönetmek için kiracı bağlamı gereklidir.",
    "Tenant context is required to design print templates.": "Yazdırma şablonlarını tasarlamak için kiracı bağlamı gereklidir.",
    "Tenant context is required to manage print templates.": "Yazdırma şablonlarını yönetmek için kiracı bağlamı gereklidir.",
    "Tenant context is required to design label templates.": "Etiket şablonlarını tasarlamak için kiracı bağlamı gereklidir.",
    "Tenant context is required to manage label templates.": "Etiket şablonlarını yönetmek için kiracı bağlamı gereklidir.",
    "Invoice, VendorBill, Payment...": "Fatura, tedarikçi faturası, ödeme..."
    ,"SingleLevel": "Tek seviye"
    ,"MultiLevel": "Çok seviye"
    ,"Never": "Asla"
    ,"Yearly": "Yıllık"
    ,"Monthly": "Aylık"
    ,"Daily": "Günlük"
  },
  "pt-PT": {
    "Approval Workflow Designer": "Designer de fluxo de aprovação",
    "Approval Workflows": "Fluxos de aprovação",
    "Numbering Settings": "Definições de numeração",
    "Print Templates": "Modelos de impressão",
    "Print Template Designer": "Designer de modelo de impressão",
    "Label Templates": "Modelos de etiqueta",
    "Label Template Designer": "Designer de modelo de etiqueta",
    "Workflow Name": "Nome do fluxo",
    "Approval Levels": "Níveis de aprovação",
    "Approval Mode": "Modo de aprovação",
    "Single-Level Approval": "Aprovação de nível único",
    "Multi-Level Approval": "Aprovação multinível",
    "Remarks required": "Observações obrigatórias",
    "Rejection reason required": "Motivo de rejeição obrigatório",
    "All approvers": "Todos os aprovadores",
    "Add Level": "Adicionar nível",
    "Save Workflow": "Guardar fluxo",
    "New Workflow": "Novo fluxo",
    "Delete approval workflow?": "Eliminar fluxo de aprovação?",
    "Format Preview": "Pré-visualização do formato",
    "Digit Length": "Comprimento dos dígitos",
    "Next No.": "Próximo n.º",
    "Next Number": "Próximo número",
    "All Branches": "Todas as filiais",
    "Add Format": "Adicionar formato",
    "Update Format": "Atualizar formato",
    "Cancel Edit": "Cancelar edição",
    "Save All Changes": "Guardar todas as alterações",
    "Remove numbering format?": "Remover formato de numeração?",
    "New Print Template": "Novo modelo de impressão",
    "Delete print template?": "Eliminar modelo de impressão?",
    "Template Code": "Código do modelo",
    "Template Name": "Nome do modelo",
    "Header Template": "Modelo de cabeçalho",
    "Body Template": "Modelo do corpo",
    "Footer Template": "Modelo de rodapé",
    "Page Size": "Tamanho da página",
    "Orientation": "Orientação",
    "Portrait": "Vertical",
    "Landscape": "Horizontal",
    "Custom": "Personalizado",
    "Tenant Logo": "Logótipo do tenant",
    "TENANT LOGO": "LOGÓTIPO DO TENANT",
    "Save Template": "Guardar modelo",
    "Placeholders": "Marcadores",
    "New Label Template": "Novo modelo de etiqueta",
    "Delete label template?": "Eliminar modelo de etiqueta?",
    "Destination Code": "Código de destino",
    "Label Width (mm)": "Largura da etiqueta (mm)",
    "Label Height (mm)": "Altura da etiqueta (mm)",
    "Label Preview": "Pré-visualização da etiqueta",
    "Default Template": "Modelo predefinido",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "Criar circuitos de aprovação por função e valor com regras opcionais de observações/rejeição.",
    "Configure single-level and multi-level approval flows with role and amount rules.": "Configurar fluxos de aprovação de nível único e multinível com regras de função e valor.",
    "Configure tenant and branch document numbering formats and reset rules.": "Configurar formatos de numeração de documentos do tenant e filial e regras de reposição.",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "Manter layouts de impressão com marca, marcadores dinâmicos e suporte multilingue.",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "Desenhar modelos de impressão por idioma com marcadores, marca e suporte de código de barras/QR.",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "Etiquetas de envio por destino com código de barras/QR e conteúdo por idioma.",
    "Design barcode/QR-ready label templates with destination and language variants.": "Desenhar modelos de etiqueta prontos para código de barras/QR por destino e idioma.",
    "e.g. DXB, LHR, SIN": "ex. DXB, LHR, SIN",
    "Tenant context is required to design approval workflows.": "É necessário contexto do tenant para desenhar fluxos de aprovação.",
    "Tenant context is required to manage approval workflows.": "É necessário contexto do tenant para gerir fluxos de aprovação.",
    "Tenant context is required to manage numbering settings.": "É necessário contexto do tenant para gerir definições de numeração.",
    "Tenant context is required to design print templates.": "É necessário contexto do tenant para desenhar modelos de impressão.",
    "Tenant context is required to manage print templates.": "É necessário contexto do tenant para gerir modelos de impressão.",
    "Tenant context is required to design label templates.": "É necessário contexto do tenant para desenhar modelos de etiqueta.",
    "Tenant context is required to manage label templates.": "É necessário contexto do tenant para gerir modelos de etiqueta.",
    "Invoice, VendorBill, Payment...": "Fatura, conta de fornecedor, pagamento..."
    ,"SingleLevel": "Nível único"
    ,"MultiLevel": "Multinível"
    ,"Never": "Nunca"
    ,"Yearly": "Anual"
    ,"Monthly": "Mensal"
    ,"Daily": "Diário"
  },
  "ru-RU": {
    "Approval Workflow Designer": "Конструктор маршрута согласования",
    "Approval Workflows": "Маршруты согласования",
    "Numbering Settings": "Настройки нумерации",
    "Print Templates": "Печатные шаблоны",
    "Print Template Designer": "Конструктор печатного шаблона",
    "Label Templates": "Шаблоны этикеток",
    "Label Template Designer": "Конструктор шаблона этикетки",
    "Workflow Name": "Название маршрута",
    "Approval Levels": "Уровни согласования",
    "Approval Mode": "Режим согласования",
    "Single-Level Approval": "Одноуровневое согласование",
    "Multi-Level Approval": "Многоуровневое согласование",
    "Remarks required": "Примечания обязательны",
    "Rejection reason required": "Причина отклонения обязательна",
    "All approvers": "Все согласующие",
    "Add Level": "Добавить уровень",
    "Save Workflow": "Сохранить маршрут",
    "New Workflow": "Новый маршрут",
    "Delete approval workflow?": "Удалить маршрут согласования?",
    "Format Preview": "Предпросмотр формата",
    "Digit Length": "Длина номера",
    "Next No.": "След. №",
    "Next Number": "Следующий номер",
    "All Branches": "Все филиалы",
    "Add Format": "Добавить формат",
    "Update Format": "Обновить формат",
    "Cancel Edit": "Отменить редактирование",
    "Save All Changes": "Сохранить все изменения",
    "Remove numbering format?": "Удалить формат нумерации?",
    "New Print Template": "Новый печатный шаблон",
    "Delete print template?": "Удалить печатный шаблон?",
    "Template Code": "Код шаблона",
    "Template Name": "Название шаблона",
    "Header Template": "Шаблон заголовка",
    "Body Template": "Шаблон тела",
    "Footer Template": "Шаблон подвала",
    "Page Size": "Размер страницы",
    "Orientation": "Ориентация",
    "Portrait": "Книжная",
    "Landscape": "Альбомная",
    "Custom": "Пользовательский",
    "Tenant Logo": "Логотип арендатора",
    "TENANT LOGO": "ЛОГОТИП АРЕНДАТОРА",
    "Save Template": "Сохранить шаблон",
    "Placeholders": "Заполнители",
    "New Label Template": "Новый шаблон этикетки",
    "Delete label template?": "Удалить шаблон этикетки?",
    "Destination Code": "Код назначения",
    "Label Width (mm)": "Ширина этикетки (мм)",
    "Label Height (mm)": "Высота этикетки (мм)",
    "Label Preview": "Предпросмотр этикетки",
    "Default Template": "Шаблон по умолчанию",
    "Build role-based and amount-based approval pipelines with optional remarks/rejection rules.": "Создавайте маршруты согласования по ролям и суммам с необязательными правилами примечаний и отклонения.",
    "Configure single-level and multi-level approval flows with role and amount rules.": "Настраивайте одноуровневые и многоуровневые согласования с правилами ролей и сумм.",
    "Configure tenant and branch document numbering formats and reset rules.": "Настройте форматы нумерации документов арендатора и филиала и правила сброса.",
    "Maintain branded print layouts with dynamic placeholders and multilingual support.": "Управляйте фирменными печатными макетами с динамическими заполнителями и многоязычной поддержкой.",
    "Design language-aware print templates with placeholders, branding, and barcode/QR support.": "Создавайте печатные шаблоны по языкам с заполнителями, брендингом и поддержкой штрихкода/QR.",
    "Destination-specific shipment labels with barcode/QR and language-specific content.": "Транспортные этикетки по назначению со штрихкодом/QR и языковым содержимым.",
    "Design barcode/QR-ready label templates with destination and language variants.": "Создавайте шаблоны этикеток со штрихкодом/QR по назначению и языку.",
    "e.g. DXB, LHR, SIN": "например DXB, LHR, SIN",
    "Tenant context is required to design approval workflows.": "Для создания маршрутов согласования требуется контекст арендатора.",
    "Tenant context is required to manage approval workflows.": "Для управления маршрутами согласования требуется контекст арендатора.",
    "Tenant context is required to manage numbering settings.": "Для управления настройками нумерации требуется контекст арендатора.",
    "Tenant context is required to design print templates.": "Для создания печатных шаблонов требуется контекст арендатора.",
    "Tenant context is required to manage print templates.": "Для управления печатными шаблонами требуется контекст арендатора.",
    "Tenant context is required to design label templates.": "Для создания шаблонов этикеток требуется контекст арендатора.",
    "Tenant context is required to manage label templates.": "Для управления шаблонами этикеток требуется контекст арендатора.",
    "Invoice, VendorBill, Payment...": "Счет, счет поставщика, платеж..."
    ,"SingleLevel": "Один уровень"
    ,"MultiLevel": "Многоуровневый"
    ,"Never": "Никогда"
    ,"Yearly": "Ежегодно"
    ,"Monthly": "Ежемесячно"
    ,"Daily": "Ежедневно"
  }
};
