export const tenantLocalizationCatalogs: Record<string, Record<string, string>> = {
  "ar-QA": {
    "Tenant": "المستأجر",
    "Tenants": "المستأجرون",
    "Create Tenant": "إنشاء مستأجر",
    "Create a new tenant profile.": "إنشاء ملف مستأجر جديد.",
    "Edit Tenant": "تعديل المستأجر",
    "Update tenant profile and status.": "تحديث ملف المستأجر والحالة.",
    "Manage tenant profiles, activation, and tenant-level setup.": "إدارة ملفات المستأجرين والتفعيل والإعدادات على مستوى المستأجر.",
    "New Tenant": "مستأجر جديد",
    "Tenant created": "تم إنشاء المستأجر",
    "Tenant updated": "تم تحديث المستأجر",
    "Tenant deleted": "تم حذف المستأجر",
    "Delete tenant?": "حذف المستأجر؟",
    "Tenant Code": "رمز المستأجر",
    "Tenant Name": "اسم المستأجر",
    "Legal Name": "الاسم القانوني",
    "Base Currency Id (GUID)": "معرف العملة الأساسية (GUID)",
    "Default Language Id (GUID)": "معرف اللغة الافتراضية (GUID)",
    "Financial Year Start Month": "شهر بداية السنة المالية",
    "Logo URL": "رابط الشعار",
    "Save Tenant": "حفظ المستأجر",
    "Tenant Settings": "إعدادات المستأجر",
    "Portal, security, and localization preferences.": "تفضيلات البوابة والأمان والتوطين.",
    "Time Zone": "المنطقة الزمنية",
    "Date Format": "تنسيق التاريخ",
    "Number Format": "تنسيق الأرقام",
    "Default Theme": "السمة الافتراضية",
    "Enable Customer Portal": "تمكين بوابة العميل",
    "Enable Agent Portal": "تمكين بوابة الوكيل",
    "Require 2FA": "طلب المصادقة الثنائية",
    "Configuration JSON": "إعدادات JSON",
    "Save Settings": "حفظ الإعدادات",
    "Tenant settings updated": "تم تحديث إعدادات المستأجر",
    "Loading tenant...": "جار تحميل المستأجر..."
  },
  "hi-IN": {
    "Tenant": "टेनेंट",
    "Tenants": "टेनेंट",
    "Create Tenant": "टेनेंट बनाएं",
    "Create a new tenant profile.": "नया टेनेंट प्रोफ़ाइल बनाएं।",
    "Edit Tenant": "टेनेंट संपादित करें",
    "Update tenant profile and status.": "टेनेंट प्रोफ़ाइल और स्थिति अपडेट करें।",
    "Manage tenant profiles, activation, and tenant-level setup.": "टेनेंट प्रोफ़ाइल, सक्रियता और टेनेंट-स्तर सेटअप प्रबंधित करें।",
    "New Tenant": "नया टेनेंट",
    "Tenant created": "टेनेंट बनाया गया",
    "Tenant updated": "टेनेंट अपडेट किया गया",
    "Tenant deleted": "टेनेंट हटाया गया",
    "Delete tenant?": "टेनेंट हटाएं?",
    "Tenant Code": "टेनेंट कोड",
    "Tenant Name": "टेनेंट नाम",
    "Legal Name": "कानूनी नाम",
    "Base Currency Id (GUID)": "बेस मुद्रा ID (GUID)",
    "Default Language Id (GUID)": "डिफ़ॉल्ट भाषा ID (GUID)",
    "Financial Year Start Month": "वित्तीय वर्ष प्रारंभ माह",
    "Logo URL": "लोगो URL",
    "Save Tenant": "टेनेंट सहेजें",
    "Tenant Settings": "टेनेंट सेटिंग्स",
    "Portal, security, and localization preferences.": "पोर्टल, सुरक्षा और स्थानीयकरण प्राथमिकताएं।",
    "Time Zone": "समय क्षेत्र",
    "Date Format": "दिनांक प्रारूप",
    "Number Format": "संख्या प्रारूप",
    "Default Theme": "डिफ़ॉल्ट थीम",
    "Enable Customer Portal": "ग्राहक पोर्टल सक्षम करें",
    "Enable Agent Portal": "एजेंट पोर्टल सक्षम करें",
    "Require 2FA": "2FA आवश्यक",
    "Configuration JSON": "कॉन्फ़िगरेशन JSON",
    "Save Settings": "सेटिंग्स सहेजें",
    "Tenant settings updated": "टेनेंट सेटिंग्स अपडेट की गईं",
    "Loading tenant...": "टेनेंट लोड हो रहा है..."
  },
  "fr-FR": {
    "Tenant": "Tenant",
    "Tenants": "Tenants",
    "Create Tenant": "Créer un tenant",
    "Create a new tenant profile.": "Créer un nouveau profil tenant.",
    "Edit Tenant": "Modifier le tenant",
    "Update tenant profile and status.": "Mettre à jour le profil et le statut du tenant.",
    "Manage tenant profiles, activation, and tenant-level setup.": "Gérer les profils tenant, l'activation et les paramètres du tenant.",
    "New Tenant": "Nouveau tenant",
    "Tenant created": "Tenant créé",
    "Tenant updated": "Tenant mis à jour",
    "Tenant deleted": "Tenant supprimé",
    "Delete tenant?": "Supprimer le tenant ?",
    "Tenant Code": "Code tenant",
    "Tenant Name": "Nom du tenant",
    "Legal Name": "Raison sociale",
    "Base Currency Id (GUID)": "ID devise de base (GUID)",
    "Default Language Id (GUID)": "ID langue par défaut (GUID)",
    "Financial Year Start Month": "Mois de début d'exercice",
    "Logo URL": "URL du logo",
    "Save Tenant": "Enregistrer le tenant",
    "Tenant Settings": "Paramètres du tenant",
    "Portal, security, and localization preferences.": "Préférences de portail, sécurité et localisation.",
    "Time Zone": "Fuseau horaire",
    "Date Format": "Format de date",
    "Number Format": "Format numérique",
    "Default Theme": "Thème par défaut",
    "Enable Customer Portal": "Activer le portail client",
    "Enable Agent Portal": "Activer le portail agent",
    "Require 2FA": "Exiger 2FA",
    "Configuration JSON": "Configuration JSON",
    "Save Settings": "Enregistrer les paramètres",
    "Tenant settings updated": "Paramètres tenant mis à jour",
    "Loading tenant...": "Chargement du tenant..."
  },
  "es-ES": {
    "Tenant": "Tenant",
    "Tenants": "Tenants",
    "Create Tenant": "Crear tenant",
    "Create a new tenant profile.": "Crear un nuevo perfil de tenant.",
    "Edit Tenant": "Editar tenant",
    "Update tenant profile and status.": "Actualizar perfil y estado del tenant.",
    "Manage tenant profiles, activation, and tenant-level setup.": "Gestionar perfiles, activación y configuración del tenant.",
    "New Tenant": "Nuevo tenant",
    "Tenant created": "Tenant creado",
    "Tenant updated": "Tenant actualizado",
    "Tenant deleted": "Tenant eliminado",
    "Delete tenant?": "¿Eliminar tenant?",
    "Tenant Code": "Código de tenant",
    "Tenant Name": "Nombre de tenant",
    "Legal Name": "Razón social",
    "Base Currency Id (GUID)": "ID de moneda base (GUID)",
    "Default Language Id (GUID)": "ID de idioma predeterminado (GUID)",
    "Financial Year Start Month": "Mes inicial del ejercicio",
    "Logo URL": "URL del logo",
    "Save Tenant": "Guardar tenant",
    "Tenant Settings": "Configuración del tenant",
    "Portal, security, and localization preferences.": "Preferencias de portal, seguridad y localización.",
    "Time Zone": "Zona horaria",
    "Date Format": "Formato de fecha",
    "Number Format": "Formato numérico",
    "Default Theme": "Tema predeterminado",
    "Enable Customer Portal": "Habilitar portal de cliente",
    "Enable Agent Portal": "Habilitar portal de agente",
    "Require 2FA": "Requerir 2FA",
    "Configuration JSON": "Configuración JSON",
    "Save Settings": "Guardar configuración",
    "Tenant settings updated": "Configuración del tenant actualizada",
    "Loading tenant...": "Cargando tenant..."
  },
  "zh-CN": {
    "Tenant": "租户",
    "Tenants": "租户",
    "Create Tenant": "创建租户",
    "Create a new tenant profile.": "创建新的租户档案。",
    "Edit Tenant": "编辑租户",
    "Update tenant profile and status.": "更新租户档案和状态。",
    "Manage tenant profiles, activation, and tenant-level setup.": "管理租户档案、启用状态和租户级设置。",
    "New Tenant": "新建租户",
    "Tenant created": "租户已创建",
    "Tenant updated": "租户已更新",
    "Tenant deleted": "租户已删除",
    "Delete tenant?": "删除租户？",
    "Tenant Code": "租户代码",
    "Tenant Name": "租户名称",
    "Legal Name": "法定名称",
    "Base Currency Id (GUID)": "基础币种 ID (GUID)",
    "Default Language Id (GUID)": "默认语言 ID (GUID)",
    "Financial Year Start Month": "财年开始月份",
    "Logo URL": "标志 URL",
    "Save Tenant": "保存租户",
    "Tenant Settings": "租户设置",
    "Portal, security, and localization preferences.": "门户、安全和本地化偏好设置。",
    "Time Zone": "时区",
    "Date Format": "日期格式",
    "Number Format": "数字格式",
    "Default Theme": "默认主题",
    "Enable Customer Portal": "启用客户门户",
    "Enable Agent Portal": "启用代理门户",
    "Require 2FA": "要求双因素认证",
    "Configuration JSON": "配置 JSON",
    "Save Settings": "保存设置",
    "Tenant settings updated": "租户设置已更新",
    "Loading tenant...": "正在加载租户..."
  },
  "tr-TR": {
    "Tenant": "Kiracı",
    "Tenants": "Kiracılar",
    "Create Tenant": "Kiracı oluştur",
    "Create a new tenant profile.": "Yeni bir kiracı profili oluşturun.",
    "Edit Tenant": "Kiracıyı düzenle",
    "Update tenant profile and status.": "Kiracı profilini ve durumunu güncelleyin.",
    "Manage tenant profiles, activation, and tenant-level setup.": "Kiracı profillerini, aktivasyonu ve kiracı düzeyi ayarları yönetin.",
    "New Tenant": "Yeni kiracı",
    "Tenant created": "Kiracı oluşturuldu",
    "Tenant updated": "Kiracı güncellendi",
    "Tenant deleted": "Kiracı silindi",
    "Delete tenant?": "Kiracı silinsin mi?",
    "Tenant Code": "Kiracı kodu",
    "Tenant Name": "Kiracı adı",
    "Legal Name": "Yasal ad",
    "Base Currency Id (GUID)": "Temel para birimi ID (GUID)",
    "Default Language Id (GUID)": "Varsayılan dil ID (GUID)",
    "Financial Year Start Month": "Mali yıl başlangıç ayı",
    "Logo URL": "Logo URL",
    "Save Tenant": "Kiracıyı kaydet",
    "Tenant Settings": "Kiracı ayarları",
    "Portal, security, and localization preferences.": "Portal, güvenlik ve yerelleştirme tercihleri.",
    "Time Zone": "Saat dilimi",
    "Date Format": "Tarih formatı",
    "Number Format": "Sayı formatı",
    "Default Theme": "Varsayılan tema",
    "Enable Customer Portal": "Müşteri portalını etkinleştir",
    "Enable Agent Portal": "Acente portalını etkinleştir",
    "Require 2FA": "2FA zorunlu",
    "Configuration JSON": "Yapılandırma JSON",
    "Save Settings": "Ayarları kaydet",
    "Tenant settings updated": "Kiracı ayarları güncellendi",
    "Loading tenant...": "Kiracı yükleniyor..."
  },
  "pt-PT": {
    "Tenant": "Tenant",
    "Tenants": "Tenants",
    "Create Tenant": "Criar tenant",
    "Create a new tenant profile.": "Criar um novo perfil de tenant.",
    "Edit Tenant": "Editar tenant",
    "Update tenant profile and status.": "Atualizar perfil e estado do tenant.",
    "Manage tenant profiles, activation, and tenant-level setup.": "Gerir perfis, ativação e configuração ao nível do tenant.",
    "New Tenant": "Novo tenant",
    "Tenant created": "Tenant criado",
    "Tenant updated": "Tenant atualizado",
    "Tenant deleted": "Tenant eliminado",
    "Delete tenant?": "Eliminar tenant?",
    "Tenant Code": "Código do tenant",
    "Tenant Name": "Nome do tenant",
    "Legal Name": "Nome legal",
    "Base Currency Id (GUID)": "ID da moeda base (GUID)",
    "Default Language Id (GUID)": "ID do idioma predefinido (GUID)",
    "Financial Year Start Month": "Mês inicial do ano fiscal",
    "Logo URL": "URL do logótipo",
    "Save Tenant": "Guardar tenant",
    "Tenant Settings": "Definições do tenant",
    "Portal, security, and localization preferences.": "Preferências de portal, segurança e localização.",
    "Time Zone": "Fuso horário",
    "Date Format": "Formato de data",
    "Number Format": "Formato numérico",
    "Default Theme": "Tema predefinido",
    "Enable Customer Portal": "Ativar portal do cliente",
    "Enable Agent Portal": "Ativar portal do agente",
    "Require 2FA": "Exigir 2FA",
    "Configuration JSON": "Configuração JSON",
    "Save Settings": "Guardar definições",
    "Tenant settings updated": "Definições do tenant atualizadas",
    "Loading tenant...": "A carregar tenant..."
  },
  "ru-RU": {
    "Tenant": "Арендатор",
    "Tenants": "Арендаторы",
    "Create Tenant": "Создать арендатора",
    "Create a new tenant profile.": "Создать новый профиль арендатора.",
    "Edit Tenant": "Редактировать арендатора",
    "Update tenant profile and status.": "Обновить профиль и статус арендатора.",
    "Manage tenant profiles, activation, and tenant-level setup.": "Управление профилями арендаторов, активацией и настройками арендатора.",
    "New Tenant": "Новый арендатор",
    "Tenant created": "Арендатор создан",
    "Tenant updated": "Арендатор обновлен",
    "Tenant deleted": "Арендатор удален",
    "Delete tenant?": "Удалить арендатора?",
    "Tenant Code": "Код арендатора",
    "Tenant Name": "Название арендатора",
    "Legal Name": "Юридическое наименование",
    "Base Currency Id (GUID)": "ID базовой валюты (GUID)",
    "Default Language Id (GUID)": "ID языка по умолчанию (GUID)",
    "Financial Year Start Month": "Месяц начала финансового года",
    "Logo URL": "URL логотипа",
    "Save Tenant": "Сохранить арендатора",
    "Tenant Settings": "Настройки арендатора",
    "Portal, security, and localization preferences.": "Настройки портала, безопасности и локализации.",
    "Time Zone": "Часовой пояс",
    "Date Format": "Формат даты",
    "Number Format": "Формат чисел",
    "Default Theme": "Тема по умолчанию",
    "Enable Customer Portal": "Включить портал клиента",
    "Enable Agent Portal": "Включить портал агента",
    "Require 2FA": "Требовать 2FA",
    "Configuration JSON": "Конфигурация JSON",
    "Save Settings": "Сохранить настройки",
    "Tenant settings updated": "Настройки арендатора обновлены",
    "Loading tenant...": "Загрузка арендатора..."
  }
};
