export const publicDocumentUploadLanguageFallbacks: Record<string, Record<string, string>> = {
  "ar-QA": {
    "DocumentUpload.Loading": "جاري تحميل رابط الرفع...",
    "DocumentUpload.NotFound": "لم يتم العثور على رابط الرفع.",
    "DocumentUpload.Title": "رفع الوسائط والملفات",
    "DocumentUpload.Video": "فيديو",
    "DocumentUpload.CameraVideo": "فيديو بالكاميرا",
    "DocumentUpload.RecordVideo": "تسجيل فيديو",
    "DocumentUpload.Audio": "صوت",
    "DocumentUpload.MicrophoneAudio": "صوت بالميكروفون",
    "DocumentUpload.RecordAudio": "تسجيل صوت",
    "DocumentUpload.File": "ملف",
    "DocumentUpload.ChooseFile": "اختيار ملف",
    "DocumentUpload.FileHelp": "صور وملفات PDF ومستندات وملفات داعمة أخرى.",
    "DocumentUpload.RecordingInProgress": "جاري تسجيل {0}",
    "DocumentUpload.Stop": "إيقاف",
    "DocumentUpload.MicrophoneSignal": "إشارة الميكروفون",
    "DocumentUpload.ReadyToUpload": "{0} جاهز للرفع",
    "DocumentUpload.Recapture": "إعادة الالتقاط",
    "DocumentUpload.Upload": "رفع",
    "DocumentUpload.Uploading": "جاري الرفع",
    "DocumentUpload.UploadComplete": "اكتمل الرفع",
    "DocumentUpload.UploadFailed": "فشل الرفع",
    "DocumentUpload.TryAgain": "يرجى المحاولة مرة أخرى.",
    "DocumentUpload.UploadedItems": "العناصر المرفوعة",
    "DocumentUpload.NoUploads": "لا توجد ملفات مرفوعة بعد.",
    "DocumentUpload.FilesAttached": "تم إرفاق الملفات.",
    "DocumentUpload.VideoType": "فيديو",
    "DocumentUpload.AudioType": "صوت"
  },
  "hi-IN": {
    "DocumentUpload.Loading": "अपलोड लिंक लोड हो रहा है...",
    "DocumentUpload.NotFound": "अपलोड लिंक नहीं मिला.",
    "DocumentUpload.Title": "मीडिया और फाइलें अपलोड करें",
    "DocumentUpload.Video": "वीडियो",
    "DocumentUpload.CameraVideo": "कैमरा वीडियो",
    "DocumentUpload.RecordVideo": "वीडियो रिकॉर्ड करें",
    "DocumentUpload.Audio": "ऑडियो",
    "DocumentUpload.MicrophoneAudio": "माइक्रोफोन ऑडियो",
    "DocumentUpload.RecordAudio": "ऑडियो रिकॉर्ड करें",
    "DocumentUpload.File": "फाइल",
    "DocumentUpload.ChooseFile": "फाइल चुनें",
    "DocumentUpload.FileHelp": "फोटो, PDF, दस्तावेज और अन्य सहायक फाइलें.",
    "DocumentUpload.RecordingInProgress": "{0} रिकॉर्डिंग चल रही है",
    "DocumentUpload.Stop": "रोकें",
    "DocumentUpload.MicrophoneSignal": "माइक्रोफोन सिग्नल",
    "DocumentUpload.ReadyToUpload": "{0} अपलोड के लिए तैयार",
    "DocumentUpload.Recapture": "फिर से कैप्चर करें",
    "DocumentUpload.Upload": "अपलोड",
    "DocumentUpload.Uploading": "अपलोड हो रहा है",
    "DocumentUpload.UploadComplete": "अपलोड पूरा हुआ",
    "DocumentUpload.UploadFailed": "अपलोड विफल",
    "DocumentUpload.TryAgain": "कृपया फिर से प्रयास करें.",
    "DocumentUpload.UploadedItems": "अपलोड किए गए आइटम",
    "DocumentUpload.NoUploads": "अभी कोई अपलोड नहीं.",
    "DocumentUpload.FilesAttached": "फाइलें संलग्न हैं.",
    "DocumentUpload.VideoType": "वीडियो",
    "DocumentUpload.AudioType": "ऑडियो"
  },
  "fr-FR": {
    "DocumentUpload.Loading": "Chargement du lien de téléversement...",
    "DocumentUpload.NotFound": "Lien de téléversement introuvable.",
    "DocumentUpload.Title": "Téléverser des médias et fichiers",
    "DocumentUpload.Video": "Vidéo",
    "DocumentUpload.CameraVideo": "Vidéo caméra",
    "DocumentUpload.RecordVideo": "Enregistrer une vidéo",
    "DocumentUpload.Audio": "Audio",
    "DocumentUpload.MicrophoneAudio": "Audio microphone",
    "DocumentUpload.RecordAudio": "Enregistrer un audio",
    "DocumentUpload.File": "Fichier",
    "DocumentUpload.ChooseFile": "Choisir un fichier",
    "DocumentUpload.FileHelp": "Photos, PDF, documents et autres fichiers justificatifs.",
    "DocumentUpload.RecordingInProgress": "Enregistrement {0} en cours",
    "DocumentUpload.Stop": "Arrêter",
    "DocumentUpload.MicrophoneSignal": "Signal du microphone",
    "DocumentUpload.ReadyToUpload": "{0} prêt à téléverser",
    "DocumentUpload.Recapture": "Reprendre",
    "DocumentUpload.Upload": "Téléverser",
    "DocumentUpload.Uploading": "Téléversement",
    "DocumentUpload.UploadComplete": "Téléversement terminé",
    "DocumentUpload.UploadFailed": "Échec du téléversement",
    "DocumentUpload.TryAgain": "Veuillez réessayer.",
    "DocumentUpload.UploadedItems": "Éléments téléversés",
    "DocumentUpload.NoUploads": "Aucun téléversement pour le moment.",
    "DocumentUpload.FilesAttached": "Les fichiers sont joints.",
    "DocumentUpload.VideoType": "Vidéo",
    "DocumentUpload.AudioType": "Audio"
  },
  "es-ES": {
    "DocumentUpload.Loading": "Cargando enlace de carga...",
    "DocumentUpload.NotFound": "No se encontró el enlace de carga.",
    "DocumentUpload.Title": "Cargar medios y archivos",
    "DocumentUpload.Video": "Video",
    "DocumentUpload.CameraVideo": "Video de cámara",
    "DocumentUpload.RecordVideo": "Grabar video",
    "DocumentUpload.Audio": "Audio",
    "DocumentUpload.MicrophoneAudio": "Audio de micrófono",
    "DocumentUpload.RecordAudio": "Grabar audio",
    "DocumentUpload.File": "Archivo",
    "DocumentUpload.ChooseFile": "Elegir archivo",
    "DocumentUpload.FileHelp": "Fotos, PDF, documentos y otros archivos de soporte.",
    "DocumentUpload.RecordingInProgress": "Grabación de {0} en curso",
    "DocumentUpload.Stop": "Detener",
    "DocumentUpload.MicrophoneSignal": "Señal del micrófono",
    "DocumentUpload.ReadyToUpload": "{0} listo para cargar",
    "DocumentUpload.Recapture": "Volver a capturar",
    "DocumentUpload.Upload": "Cargar",
    "DocumentUpload.Uploading": "Cargando",
    "DocumentUpload.UploadComplete": "Carga completa",
    "DocumentUpload.UploadFailed": "Error al cargar",
    "DocumentUpload.TryAgain": "Inténtelo de nuevo.",
    "DocumentUpload.UploadedItems": "Elementos cargados",
    "DocumentUpload.NoUploads": "Aún no hay cargas.",
    "DocumentUpload.FilesAttached": "Los archivos están adjuntos.",
    "DocumentUpload.VideoType": "Video",
    "DocumentUpload.AudioType": "Audio"
  },
  "zh-CN": {
    "DocumentUpload.Loading": "正在加载上传链接...",
    "DocumentUpload.NotFound": "未找到上传链接。",
    "DocumentUpload.Title": "上传媒体和文件",
    "DocumentUpload.Video": "视频",
    "DocumentUpload.CameraVideo": "摄像头视频",
    "DocumentUpload.RecordVideo": "录制视频",
    "DocumentUpload.Audio": "音频",
    "DocumentUpload.MicrophoneAudio": "麦克风音频",
    "DocumentUpload.RecordAudio": "录制音频",
    "DocumentUpload.File": "文件",
    "DocumentUpload.ChooseFile": "选择文件",
    "DocumentUpload.FileHelp": "照片、PDF、文档和其他支持文件。",
    "DocumentUpload.RecordingInProgress": "{0}正在录制",
    "DocumentUpload.Stop": "停止",
    "DocumentUpload.MicrophoneSignal": "麦克风信号",
    "DocumentUpload.ReadyToUpload": "{0}已准备上传",
    "DocumentUpload.Recapture": "重新采集",
    "DocumentUpload.Upload": "上传",
    "DocumentUpload.Uploading": "正在上传",
    "DocumentUpload.UploadComplete": "上传完成",
    "DocumentUpload.UploadFailed": "上传失败",
    "DocumentUpload.TryAgain": "请重试。",
    "DocumentUpload.UploadedItems": "已上传项目",
    "DocumentUpload.NoUploads": "暂无上传。",
    "DocumentUpload.FilesAttached": "文件已附加。",
    "DocumentUpload.VideoType": "视频",
    "DocumentUpload.AudioType": "音频"
  },
  "tr-TR": {
    "DocumentUpload.Loading": "Yükleme bağlantısı yükleniyor...",
    "DocumentUpload.NotFound": "Yükleme bağlantısı bulunamadı.",
    "DocumentUpload.Title": "Medya ve dosya yükle",
    "DocumentUpload.Video": "Video",
    "DocumentUpload.CameraVideo": "Kamera videosu",
    "DocumentUpload.RecordVideo": "Video kaydet",
    "DocumentUpload.Audio": "Ses",
    "DocumentUpload.MicrophoneAudio": "Mikrofon sesi",
    "DocumentUpload.RecordAudio": "Ses kaydet",
    "DocumentUpload.File": "Dosya",
    "DocumentUpload.ChooseFile": "Dosya seç",
    "DocumentUpload.FileHelp": "Fotoğraflar, PDF'ler, belgeler ve diğer destek dosyaları.",
    "DocumentUpload.RecordingInProgress": "{0} kaydı devam ediyor",
    "DocumentUpload.Stop": "Durdur",
    "DocumentUpload.MicrophoneSignal": "Mikrofon sinyali",
    "DocumentUpload.ReadyToUpload": "{0} yüklemeye hazır",
    "DocumentUpload.Recapture": "Tekrar çek",
    "DocumentUpload.Upload": "Yükle",
    "DocumentUpload.Uploading": "Yükleniyor",
    "DocumentUpload.UploadComplete": "Yükleme tamamlandı",
    "DocumentUpload.UploadFailed": "Yükleme başarısız",
    "DocumentUpload.TryAgain": "Lütfen tekrar deneyin.",
    "DocumentUpload.UploadedItems": "Yüklenen öğeler",
    "DocumentUpload.NoUploads": "Henüz yükleme yok.",
    "DocumentUpload.FilesAttached": "Dosyalar eklendi.",
    "DocumentUpload.VideoType": "Video",
    "DocumentUpload.AudioType": "Ses"
  },
  "pt-PT": {
    "DocumentUpload.Loading": "A carregar ligação de carregamento...",
    "DocumentUpload.NotFound": "Ligação de carregamento não encontrada.",
    "DocumentUpload.Title": "Carregar média e ficheiros",
    "DocumentUpload.Video": "Vídeo",
    "DocumentUpload.CameraVideo": "Vídeo da câmara",
    "DocumentUpload.RecordVideo": "Gravar vídeo",
    "DocumentUpload.Audio": "Áudio",
    "DocumentUpload.MicrophoneAudio": "Áudio do microfone",
    "DocumentUpload.RecordAudio": "Gravar áudio",
    "DocumentUpload.File": "Ficheiro",
    "DocumentUpload.ChooseFile": "Escolher ficheiro",
    "DocumentUpload.FileHelp": "Fotos, PDF, documentos e outros ficheiros de suporte.",
    "DocumentUpload.RecordingInProgress": "Gravação de {0} em curso",
    "DocumentUpload.Stop": "Parar",
    "DocumentUpload.MicrophoneSignal": "Sinal do microfone",
    "DocumentUpload.ReadyToUpload": "{0} pronto para carregar",
    "DocumentUpload.Recapture": "Capturar novamente",
    "DocumentUpload.Upload": "Carregar",
    "DocumentUpload.Uploading": "A carregar",
    "DocumentUpload.UploadComplete": "Carregamento concluído",
    "DocumentUpload.UploadFailed": "Falha no carregamento",
    "DocumentUpload.TryAgain": "Tente novamente.",
    "DocumentUpload.UploadedItems": "Itens carregados",
    "DocumentUpload.NoUploads": "Ainda não há carregamentos.",
    "DocumentUpload.FilesAttached": "Os ficheiros foram anexados.",
    "DocumentUpload.VideoType": "Vídeo",
    "DocumentUpload.AudioType": "Áudio"
  },
  "ru-RU": {
    "DocumentUpload.Loading": "Загрузка ссылки для загрузки...",
    "DocumentUpload.NotFound": "Ссылка для загрузки не найдена.",
    "DocumentUpload.Title": "Загрузить медиа и файлы",
    "DocumentUpload.Video": "Видео",
    "DocumentUpload.CameraVideo": "Видео с камеры",
    "DocumentUpload.RecordVideo": "Записать видео",
    "DocumentUpload.Audio": "Аудио",
    "DocumentUpload.MicrophoneAudio": "Аудио с микрофона",
    "DocumentUpload.RecordAudio": "Записать аудио",
    "DocumentUpload.File": "Файл",
    "DocumentUpload.ChooseFile": "Выбрать файл",
    "DocumentUpload.FileHelp": "Фотографии, PDF, документы и другие вспомогательные файлы.",
    "DocumentUpload.RecordingInProgress": "Идет запись {0}",
    "DocumentUpload.Stop": "Остановить",
    "DocumentUpload.MicrophoneSignal": "Сигнал микрофона",
    "DocumentUpload.ReadyToUpload": "{0} готово к загрузке",
    "DocumentUpload.Recapture": "Перезаписать",
    "DocumentUpload.Upload": "Загрузить",
    "DocumentUpload.Uploading": "Загрузка",
    "DocumentUpload.UploadComplete": "Загрузка завершена",
    "DocumentUpload.UploadFailed": "Ошибка загрузки",
    "DocumentUpload.TryAgain": "Повторите попытку.",
    "DocumentUpload.UploadedItems": "Загруженные элементы",
    "DocumentUpload.NoUploads": "Загрузок пока нет.",
    "DocumentUpload.FilesAttached": "Файлы прикреплены.",
    "DocumentUpload.VideoType": "Видео",
    "DocumentUpload.AudioType": "Аудио"
  }
};
