export const quotationRequestLanguageFallbacks: Record<string, Record<string, string>> = {
  "fr-FR": {
    "Login.RequestQuotation": "Demander un devis",
    "Navigation.rate-quotation.Item.quotation-requests.Label": "Demandes de devis",
    "Navigation.rate-quotation.Item.quotation-requests.Description": "Demandes de devis client et pièces jointes téléversées.",
    "QuotationRequest.AppName": "ERP Freight Forwarding",
    "QuotationRequest.Create.Title": "Demande de devis",
    "QuotationRequest.Create.ShipmentDetails": "Détails de l'expédition",
    "QuotationRequest.Create.UploadLink": "Lien de téléversement",
    "QuotationRequest.Create.RequestReady": "La demande {0} est prête.",
    "QuotationRequest.Create.EmptyUploadLink": "Créez une demande pour générer un lien privé de téléversement.",
    "QuotationRequest.Create.CreatedToast": "Demande de devis créée",
    "QuotationRequest.Create.LinkCopiedToast": "Lien copié",
    "QuotationRequest.Create.LinkCopiedDetail": "Partagez-le avec le client pour téléverser des fichiers, vidéos ou audios.",
    "QuotationRequest.Create.Creating": "Création...",
    "QuotationRequest.Create.CreateRequest": "Créer la demande",
    "QuotationRequest.Create.CopyLink": "Copier le lien",
    "QuotationRequest.Create.OpenUpload": "Ouvrir le téléversement",
    "QuotationRequest.Label.CustomerName": "Nom du client",
    "QuotationRequest.Label.Company": "Société",
    "QuotationRequest.Label.Email": "E-mail",
    "QuotationRequest.Label.Phone": "Téléphone",
    "QuotationRequest.Label.Origin": "Origine",
    "QuotationRequest.Label.Destination": "Destination",
    "QuotationRequest.Label.Mode": "Mode",
    "QuotationRequest.Label.ShipmentType": "Type d'expédition",
    "QuotationRequest.Label.CargoDescription": "Description du fret",
    "QuotationRequest.Label.Status": "Statut",
    "QuotationRequest.Placeholder.CustomerName": "Saisir le nom du client",
    "QuotationRequest.Placeholder.Company": "Saisir le nom de la société",
    "QuotationRequest.Placeholder.Email": "Saisir l'adresse e-mail",
    "QuotationRequest.Placeholder.Phone": "Saisir le numéro de téléphone",
    "QuotationRequest.Placeholder.Origin": "Saisir l'origine",
    "QuotationRequest.Placeholder.Destination": "Saisir la destination",
    "QuotationRequest.Placeholder.CargoDescription": "Décrire le fret, le poids, le volume et les consignes de manutention",
    "QuotationRequest.Mode.Air": "Aérien",
    "QuotationRequest.Mode.Sea": "Maritime",
    "QuotationRequest.Mode.Road": "Routier",
    "QuotationRequest.Mode.Courier": "Courrier",
    "QuotationRequest.ShipmentType.General": "Général",
    "QuotationRequest.ShipmentType.Import": "Import",
    "QuotationRequest.ShipmentType.Export": "Export",
    "QuotationRequest.ShipmentType.DoorToDoor": "Porte à porte",
    "QuotationRequest.Upload.Loading": "Chargement de la demande de devis...",
    "QuotationRequest.Upload.NotFound": "Lien de demande de devis introuvable.",
    "QuotationRequest.Upload.RequestNumber": "Demande {0}",
    "QuotationRequest.Upload.Title": "Téléverser les médias de l'expédition",
    "QuotationRequest.Upload.Video": "Vidéo",
    "QuotationRequest.Upload.CameraVideo": "Vidéo caméra",
    "QuotationRequest.Upload.RecordVideo": "Enregistrer une vidéo",
    "QuotationRequest.Upload.Audio": "Audio",
    "QuotationRequest.Upload.MicrophoneAudio": "Audio microphone",
    "QuotationRequest.Upload.RecordAudio": "Enregistrer un audio",
    "QuotationRequest.Upload.File": "Fichier",
    "QuotationRequest.Upload.ChooseFile": "Choisir un fichier",
    "QuotationRequest.Upload.FileHelp": "Photos, PDF, documents et autres fichiers justificatifs.",
    "QuotationRequest.Upload.RecordingInProgress": "Enregistrement {0} en cours",
    "QuotationRequest.Upload.Stop": "Arrêter",
    "QuotationRequest.Upload.MicrophoneSignal": "Signal du microphone",
    "QuotationRequest.Upload.ReadyToUpload": "{0} prêt à téléverser",
    "QuotationRequest.Upload.Recapture": "Reprendre",
    "QuotationRequest.Upload.Upload": "Téléverser",
    "QuotationRequest.Upload.Uploading": "Téléversement",
    "QuotationRequest.Upload.UploadComplete": "Téléversement terminé",
    "QuotationRequest.Upload.UploadedItems": "Éléments téléversés",
    "QuotationRequest.Upload.NoUploads": "Aucun téléversement pour le moment.",
    "QuotationRequest.Upload.FilesAttached": "Les fichiers sont joints à cette demande de devis.",
    "QuotationRequest.List.Title": "Demandes de devis",
    "QuotationRequest.List.Description": "Demandes de devis client reçues via des liens publics de téléversement.",
    "QuotationRequest.List.RequestNo": "N° de demande",
    "QuotationRequest.List.Customer": "Client",
    "QuotationRequest.List.Company": "Société",
    "QuotationRequest.List.Origin": "Origine",
    "QuotationRequest.List.Destination": "Destination",
    "QuotationRequest.List.Mode": "Mode",
    "QuotationRequest.List.Attachments": "Pièces jointes",
    "QuotationRequest.List.Status": "Statut",
    "QuotationRequest.List.Actions": "Actions",
    "QuotationRequest.List.ViewRequest": "Voir la demande",
    "QuotationRequest.List.EditRequest": "Modifier la demande",
    "QuotationRequest.View.Title": "Demande de devis",
    "QuotationRequest.View.TitleWithNumber": "Demande de devis {0}",
    "QuotationRequest.View.Description": "Détails de la demande client et pièces jointes téléversées.",
    "QuotationRequest.View.Back": "Retour",
    "QuotationRequest.View.RequestDetails": "Détails de la demande",
    "QuotationRequest.View.Attachments": "Pièces jointes",
    "QuotationRequest.View.NoAttachments": "Aucune pièce jointe téléversée.",
    "QuotationRequest.View.Download": "Télécharger",
    "QuotationRequest.View.Loading": "Chargement de la demande...",
    "QuotationRequest.View.NotFound": "Demande de devis introuvable.",
    "QuotationRequest.Edit.Title": "Modifier la demande de devis",
    "QuotationRequest.Edit.TitleWithNumber": "Modifier la demande de devis {0}",
    "QuotationRequest.Edit.Description": "Mettre à jour les détails et le statut de la demande client.",
    "QuotationRequest.Edit.UpdateRequest": "Mettre à jour la demande",
    "QuotationRequest.Edit.Updating": "Mise à jour...",
    "QuotationRequest.Edit.UpdatedToast": "Demande de devis mise à jour",
    "QuotationRequest.Status.Open": "Ouvert",
    "QuotationRequest.Status.Submitted": "Soumis",
    "QuotationRequest.Status.Closed": "Fermé",
    "QuotationRequest.Status.Cancelled": "Annulé"
  },
  "es-ES": {
    "Login.RequestQuotation": "Solicitar cotización",
    "Navigation.rate-quotation.Item.quotation-requests.Label": "Solicitudes de cotización",
    "Navigation.rate-quotation.Item.quotation-requests.Description": "Solicitudes de cotización de clientes y adjuntos cargados.",
    "QuotationRequest.AppName": "ERP de Freight Forwarding",
    "QuotationRequest.Create.Title": "Solicitud de cotización",
    "QuotationRequest.Create.ShipmentDetails": "Detalles del envío",
    "QuotationRequest.Create.UploadLink": "Enlace de carga",
    "QuotationRequest.Create.RequestReady": "La solicitud {0} está lista.",
    "QuotationRequest.Create.EmptyUploadLink": "Cree una solicitud para generar un enlace privado de carga.",
    "QuotationRequest.Create.CreatedToast": "Solicitud de cotización creada",
    "QuotationRequest.Create.LinkCopiedToast": "Enlace copiado",
    "QuotationRequest.Create.LinkCopiedDetail": "Compártalo con el cliente para cargar archivos, video o audio.",
    "QuotationRequest.Create.Creating": "Creando...",
    "QuotationRequest.Create.CreateRequest": "Crear solicitud",
    "QuotationRequest.Create.CopyLink": "Copiar enlace",
    "QuotationRequest.Create.OpenUpload": "Abrir carga",
    "QuotationRequest.Label.CustomerName": "Nombre del cliente",
    "QuotationRequest.Label.Company": "Empresa",
    "QuotationRequest.Label.Email": "Correo electrónico",
    "QuotationRequest.Label.Phone": "Teléfono",
    "QuotationRequest.Label.Origin": "Origen",
    "QuotationRequest.Label.Destination": "Destino",
    "QuotationRequest.Label.Mode": "Modo",
    "QuotationRequest.Label.ShipmentType": "Tipo de envío",
    "QuotationRequest.Label.CargoDescription": "Descripción de la carga",
    "QuotationRequest.Label.Status": "Estado",
    "QuotationRequest.Placeholder.CustomerName": "Ingrese el nombre del cliente",
    "QuotationRequest.Placeholder.Company": "Ingrese el nombre de la empresa",
    "QuotationRequest.Placeholder.Email": "Ingrese el correo electrónico",
    "QuotationRequest.Placeholder.Phone": "Ingrese el número de teléfono",
    "QuotationRequest.Placeholder.Origin": "Ingrese el origen",
    "QuotationRequest.Placeholder.Destination": "Ingrese el destino",
    "QuotationRequest.Placeholder.CargoDescription": "Describa la carga, peso, volumen e instrucciones de manipulación",
    "QuotationRequest.Mode.Air": "Aéreo",
    "QuotationRequest.Mode.Sea": "Marítimo",
    "QuotationRequest.Mode.Road": "Terrestre",
    "QuotationRequest.Mode.Courier": "Mensajería",
    "QuotationRequest.ShipmentType.General": "General",
    "QuotationRequest.ShipmentType.Import": "Importación",
    "QuotationRequest.ShipmentType.Export": "Exportación",
    "QuotationRequest.ShipmentType.DoorToDoor": "Puerta a puerta",
    "QuotationRequest.Upload.Loading": "Cargando solicitud de cotización...",
    "QuotationRequest.Upload.NotFound": "No se encontró el enlace de solicitud de cotización.",
    "QuotationRequest.Upload.RequestNumber": "Solicitud {0}",
    "QuotationRequest.Upload.Title": "Cargar medios del envío",
    "QuotationRequest.Upload.Video": "Video",
    "QuotationRequest.Upload.CameraVideo": "Video de cámara",
    "QuotationRequest.Upload.RecordVideo": "Grabar video",
    "QuotationRequest.Upload.Audio": "Audio",
    "QuotationRequest.Upload.MicrophoneAudio": "Audio de micrófono",
    "QuotationRequest.Upload.RecordAudio": "Grabar audio",
    "QuotationRequest.Upload.File": "Archivo",
    "QuotationRequest.Upload.ChooseFile": "Elegir archivo",
    "QuotationRequest.Upload.FileHelp": "Fotos, PDF, documentos y otros archivos de soporte.",
    "QuotationRequest.Upload.RecordingInProgress": "Grabación de {0} en curso",
    "QuotationRequest.Upload.Stop": "Detener",
    "QuotationRequest.Upload.MicrophoneSignal": "Señal del micrófono",
    "QuotationRequest.Upload.ReadyToUpload": "{0} listo para cargar",
    "QuotationRequest.Upload.Recapture": "Volver a capturar",
    "QuotationRequest.Upload.Upload": "Cargar",
    "QuotationRequest.Upload.Uploading": "Cargando",
    "QuotationRequest.Upload.UploadComplete": "Carga completa",
    "QuotationRequest.Upload.UploadedItems": "Elementos cargados",
    "QuotationRequest.Upload.NoUploads": "Aún no hay cargas.",
    "QuotationRequest.Upload.FilesAttached": "Los archivos están adjuntos a esta solicitud de cotización.",
    "QuotationRequest.List.Title": "Solicitudes de cotización",
    "QuotationRequest.List.Description": "Solicitudes de cotización de clientes recibidas desde enlaces públicos de carga.",
    "QuotationRequest.List.RequestNo": "N.º solicitud",
    "QuotationRequest.List.Customer": "Cliente",
    "QuotationRequest.List.Company": "Empresa",
    "QuotationRequest.List.Origin": "Origen",
    "QuotationRequest.List.Destination": "Destino",
    "QuotationRequest.List.Mode": "Modo",
    "QuotationRequest.List.Attachments": "Adjuntos",
    "QuotationRequest.List.Status": "Estado",
    "QuotationRequest.List.Actions": "Acciones",
    "QuotationRequest.List.ViewRequest": "Ver solicitud",
    "QuotationRequest.List.EditRequest": "Editar solicitud",
    "QuotationRequest.View.Title": "Solicitud de cotización",
    "QuotationRequest.View.TitleWithNumber": "Solicitud de cotización {0}",
    "QuotationRequest.View.Description": "Detalles de la solicitud del cliente y adjuntos cargados.",
    "QuotationRequest.View.Back": "Atrás",
    "QuotationRequest.View.RequestDetails": "Detalles de la solicitud",
    "QuotationRequest.View.Attachments": "Adjuntos",
    "QuotationRequest.View.NoAttachments": "No se cargaron adjuntos.",
    "QuotationRequest.View.Download": "Descargar",
    "QuotationRequest.View.Loading": "Cargando solicitud...",
    "QuotationRequest.View.NotFound": "No se encontró la solicitud de cotización.",
    "QuotationRequest.Edit.Title": "Editar solicitud de cotización",
    "QuotationRequest.Edit.TitleWithNumber": "Editar solicitud de cotización {0}",
    "QuotationRequest.Edit.Description": "Actualizar los detalles y el estado de la solicitud del cliente.",
    "QuotationRequest.Edit.UpdateRequest": "Actualizar solicitud",
    "QuotationRequest.Edit.Updating": "Actualizando...",
    "QuotationRequest.Edit.UpdatedToast": "Solicitud de cotización actualizada",
    "QuotationRequest.Status.Open": "Abierto",
    "QuotationRequest.Status.Submitted": "Enviado",
    "QuotationRequest.Status.Closed": "Cerrado",
    "QuotationRequest.Status.Cancelled": "Cancelado"
  },
  "zh-CN": {
    "Login.RequestQuotation": "请求报价",
    "Navigation.rate-quotation.Item.quotation-requests.Label": "报价请求",
    "Navigation.rate-quotation.Item.quotation-requests.Description": "客户报价请求和已上传附件。",
    "QuotationRequest.AppName": "货运代理 ERP",
    "QuotationRequest.Create.Title": "报价请求",
    "QuotationRequest.Create.ShipmentDetails": "货运详情",
    "QuotationRequest.Create.UploadLink": "上传链接",
    "QuotationRequest.Create.RequestReady": "请求 {0} 已准备好。",
    "QuotationRequest.Create.EmptyUploadLink": "创建请求以生成专用上传链接。",
    "QuotationRequest.Create.CreatedToast": "报价请求已创建",
    "QuotationRequest.Create.LinkCopiedToast": "链接已复制",
    "QuotationRequest.Create.LinkCopiedDetail": "将其分享给客户以上传文件、视频或音频。",
    "QuotationRequest.Create.Creating": "正在创建...",
    "QuotationRequest.Create.CreateRequest": "创建请求",
    "QuotationRequest.Create.CopyLink": "复制链接",
    "QuotationRequest.Create.OpenUpload": "打开上传",
    "QuotationRequest.Label.CustomerName": "客户名称",
    "QuotationRequest.Label.Company": "公司",
    "QuotationRequest.Label.Email": "电子邮件",
    "QuotationRequest.Label.Phone": "电话",
    "QuotationRequest.Label.Origin": "起运地",
    "QuotationRequest.Label.Destination": "目的地",
    "QuotationRequest.Label.Mode": "运输方式",
    "QuotationRequest.Label.ShipmentType": "货运类型",
    "QuotationRequest.Label.CargoDescription": "货物描述",
    "QuotationRequest.Label.Status": "状态",
    "QuotationRequest.Placeholder.CustomerName": "输入客户名称",
    "QuotationRequest.Placeholder.Company": "输入公司名称",
    "QuotationRequest.Placeholder.Email": "输入电子邮件地址",
    "QuotationRequest.Placeholder.Phone": "输入电话号码",
    "QuotationRequest.Placeholder.Origin": "输入起运地",
    "QuotationRequest.Placeholder.Destination": "输入目的地",
    "QuotationRequest.Placeholder.CargoDescription": "描述货物、重量、体积和操作说明",
    "QuotationRequest.Mode.Air": "空运",
    "QuotationRequest.Mode.Sea": "海运",
    "QuotationRequest.Mode.Road": "陆运",
    "QuotationRequest.Mode.Courier": "快递",
    "QuotationRequest.ShipmentType.General": "一般",
    "QuotationRequest.ShipmentType.Import": "进口",
    "QuotationRequest.ShipmentType.Export": "出口",
    "QuotationRequest.ShipmentType.DoorToDoor": "门到门",
    "QuotationRequest.Upload.Loading": "正在加载报价请求...",
    "QuotationRequest.Upload.NotFound": "未找到报价请求链接。",
    "QuotationRequest.Upload.RequestNumber": "请求 {0}",
    "QuotationRequest.Upload.Title": "上传货运媒体",
    "QuotationRequest.Upload.Video": "视频",
    "QuotationRequest.Upload.CameraVideo": "相机视频",
    "QuotationRequest.Upload.RecordVideo": "录制视频",
    "QuotationRequest.Upload.Audio": "音频",
    "QuotationRequest.Upload.MicrophoneAudio": "麦克风音频",
    "QuotationRequest.Upload.RecordAudio": "录制音频",
    "QuotationRequest.Upload.File": "文件",
    "QuotationRequest.Upload.ChooseFile": "选择文件",
    "QuotationRequest.Upload.FileHelp": "照片、PDF、文档和其他支持文件。",
    "QuotationRequest.Upload.RecordingInProgress": "{0} 正在录制",
    "QuotationRequest.Upload.Stop": "停止",
    "QuotationRequest.Upload.MicrophoneSignal": "麦克风信号",
    "QuotationRequest.Upload.ReadyToUpload": "{0} 已准备上传",
    "QuotationRequest.Upload.Recapture": "重新采集",
    "QuotationRequest.Upload.Upload": "上传",
    "QuotationRequest.Upload.Uploading": "正在上传",
    "QuotationRequest.Upload.UploadComplete": "上传完成",
    "QuotationRequest.Upload.UploadedItems": "已上传项目",
    "QuotationRequest.Upload.NoUploads": "尚无上传。",
    "QuotationRequest.Upload.FilesAttached": "文件已附加到此报价请求。",
    "QuotationRequest.List.Title": "报价请求",
    "QuotationRequest.List.Description": "通过公共上传链接收到的客户报价请求。",
    "QuotationRequest.List.RequestNo": "请求编号",
    "QuotationRequest.List.Customer": "客户",
    "QuotationRequest.List.Company": "公司",
    "QuotationRequest.List.Origin": "起运地",
    "QuotationRequest.List.Destination": "目的地",
    "QuotationRequest.List.Mode": "方式",
    "QuotationRequest.List.Attachments": "附件",
    "QuotationRequest.List.Status": "状态",
    "QuotationRequest.List.Actions": "操作",
    "QuotationRequest.List.ViewRequest": "查看请求",
    "QuotationRequest.List.EditRequest": "编辑请求",
    "QuotationRequest.View.Title": "报价请求",
    "QuotationRequest.View.TitleWithNumber": "报价请求 {0}",
    "QuotationRequest.View.Description": "客户请求详情和已上传附件。",
    "QuotationRequest.View.Back": "返回",
    "QuotationRequest.View.RequestDetails": "请求详情",
    "QuotationRequest.View.Attachments": "附件",
    "QuotationRequest.View.NoAttachments": "未上传附件。",
    "QuotationRequest.View.Download": "下载",
    "QuotationRequest.View.Loading": "正在加载请求...",
    "QuotationRequest.View.NotFound": "未找到报价请求。",
    "QuotationRequest.Edit.Title": "编辑报价请求",
    "QuotationRequest.Edit.TitleWithNumber": "编辑报价请求 {0}",
    "QuotationRequest.Edit.Description": "更新客户请求详情和状态。",
    "QuotationRequest.Edit.UpdateRequest": "更新请求",
    "QuotationRequest.Edit.Updating": "正在更新...",
    "QuotationRequest.Edit.UpdatedToast": "报价请求已更新",
    "QuotationRequest.Status.Open": "打开",
    "QuotationRequest.Status.Submitted": "已提交",
    "QuotationRequest.Status.Closed": "已关闭",
    "QuotationRequest.Status.Cancelled": "已取消"
  },
  "tr-TR": {
    "Login.RequestQuotation": "Teklif iste",
    "Navigation.rate-quotation.Item.quotation-requests.Label": "Teklif İstekleri",
    "Navigation.rate-quotation.Item.quotation-requests.Description": "Müşteri teklif istekleri ve yüklenen ekler.",
    "QuotationRequest.AppName": "Freight Forwarding ERP",
    "QuotationRequest.Create.Title": "Teklif İsteği",
    "QuotationRequest.Create.ShipmentDetails": "Sevkiyat Detayları",
    "QuotationRequest.Create.UploadLink": "Yükleme Bağlantısı",
    "QuotationRequest.Create.RequestReady": "{0} isteği hazır.",
    "QuotationRequest.Create.EmptyUploadLink": "Özel yükleme bağlantısı oluşturmak için bir istek oluşturun.",
    "QuotationRequest.Create.CreatedToast": "Teklif isteği oluşturuldu",
    "QuotationRequest.Create.LinkCopiedToast": "Bağlantı kopyalandı",
    "QuotationRequest.Create.LinkCopiedDetail": "Dosya, video veya ses yüklemesi için müşteriyle paylaşın.",
    "QuotationRequest.Create.Creating": "Oluşturuluyor...",
    "QuotationRequest.Create.CreateRequest": "İstek Oluştur",
    "QuotationRequest.Create.CopyLink": "Bağlantıyı Kopyala",
    "QuotationRequest.Create.OpenUpload": "Yüklemeyi Aç",
    "QuotationRequest.Label.CustomerName": "Müşteri Adı",
    "QuotationRequest.Label.Company": "Şirket",
    "QuotationRequest.Label.Email": "E-posta",
    "QuotationRequest.Label.Phone": "Telefon",
    "QuotationRequest.Label.Origin": "Çıkış",
    "QuotationRequest.Label.Destination": "Varış",
    "QuotationRequest.Label.Mode": "Mod",
    "QuotationRequest.Label.ShipmentType": "Sevkiyat Türü",
    "QuotationRequest.Label.CargoDescription": "Yük Açıklaması",
    "QuotationRequest.Label.Status": "Durum",
    "QuotationRequest.Placeholder.CustomerName": "Müşteri adını girin",
    "QuotationRequest.Placeholder.Company": "Şirket adını girin",
    "QuotationRequest.Placeholder.Email": "E-posta adresini girin",
    "QuotationRequest.Placeholder.Phone": "Telefon numarasını girin",
    "QuotationRequest.Placeholder.Origin": "Çıkış noktasını girin",
    "QuotationRequest.Placeholder.Destination": "Varış noktasını girin",
    "QuotationRequest.Placeholder.CargoDescription": "Yük, ağırlık, hacim ve elleçleme notlarını açıklayın",
    "QuotationRequest.Mode.Air": "Hava",
    "QuotationRequest.Mode.Sea": "Deniz",
    "QuotationRequest.Mode.Road": "Kara",
    "QuotationRequest.Mode.Courier": "Kurye",
    "QuotationRequest.ShipmentType.General": "Genel",
    "QuotationRequest.ShipmentType.Import": "İthalat",
    "QuotationRequest.ShipmentType.Export": "İhracat",
    "QuotationRequest.ShipmentType.DoorToDoor": "Kapıdan kapıya",
    "QuotationRequest.Upload.Loading": "Teklif isteği yükleniyor...",
    "QuotationRequest.Upload.NotFound": "Teklif isteği bağlantısı bulunamadı.",
    "QuotationRequest.Upload.RequestNumber": "İstek {0}",
    "QuotationRequest.Upload.Title": "Sevkiyat Medyası Yükle",
    "QuotationRequest.Upload.Video": "Video",
    "QuotationRequest.Upload.CameraVideo": "Kamera Videosu",
    "QuotationRequest.Upload.RecordVideo": "Video Kaydet",
    "QuotationRequest.Upload.Audio": "Ses",
    "QuotationRequest.Upload.MicrophoneAudio": "Mikrofon Sesi",
    "QuotationRequest.Upload.RecordAudio": "Ses Kaydet",
    "QuotationRequest.Upload.File": "Dosya",
    "QuotationRequest.Upload.ChooseFile": "Dosya Seç",
    "QuotationRequest.Upload.FileHelp": "Fotoğraflar, PDF'ler, belgeler ve diğer destekleyici dosyalar.",
    "QuotationRequest.Upload.RecordingInProgress": "{0} kaydı devam ediyor",
    "QuotationRequest.Upload.Stop": "Durdur",
    "QuotationRequest.Upload.MicrophoneSignal": "Mikrofon sinyali",
    "QuotationRequest.Upload.ReadyToUpload": "{0} yüklemeye hazır",
    "QuotationRequest.Upload.Recapture": "Yeniden çek",
    "QuotationRequest.Upload.Upload": "Yükle",
    "QuotationRequest.Upload.Uploading": "Yükleniyor",
    "QuotationRequest.Upload.UploadComplete": "Yükleme tamamlandı",
    "QuotationRequest.Upload.UploadedItems": "Yüklenen Öğeler",
    "QuotationRequest.Upload.NoUploads": "Henüz yükleme yok.",
    "QuotationRequest.Upload.FilesAttached": "Dosyalar bu teklif isteğine eklendi.",
    "QuotationRequest.List.Title": "Teklif İstekleri",
    "QuotationRequest.List.Description": "Genel yükleme bağlantılarından alınan müşteri teklif istekleri.",
    "QuotationRequest.List.RequestNo": "İstek No",
    "QuotationRequest.List.Customer": "Müşteri",
    "QuotationRequest.List.Company": "Şirket",
    "QuotationRequest.List.Origin": "Çıkış",
    "QuotationRequest.List.Destination": "Varış",
    "QuotationRequest.List.Mode": "Mod",
    "QuotationRequest.List.Attachments": "Ekler",
    "QuotationRequest.List.Status": "Durum",
    "QuotationRequest.List.Actions": "İşlemler",
    "QuotationRequest.List.ViewRequest": "İsteği Görüntüle",
    "QuotationRequest.List.EditRequest": "İsteği Düzenle",
    "QuotationRequest.View.Title": "Teklif İsteği",
    "QuotationRequest.View.TitleWithNumber": "Teklif İsteği {0}",
    "QuotationRequest.View.Description": "Müşteri isteği detayları ve yüklenen ekler.",
    "QuotationRequest.View.Back": "Geri",
    "QuotationRequest.View.RequestDetails": "İstek Detayları",
    "QuotationRequest.View.Attachments": "Ekler",
    "QuotationRequest.View.NoAttachments": "Ek yüklenmedi.",
    "QuotationRequest.View.Download": "İndir",
    "QuotationRequest.View.Loading": "İstek yükleniyor...",
    "QuotationRequest.View.NotFound": "Teklif isteği bulunamadı.",
    "QuotationRequest.Edit.Title": "Teklif İsteğini Düzenle",
    "QuotationRequest.Edit.TitleWithNumber": "Teklif İsteğini Düzenle {0}",
    "QuotationRequest.Edit.Description": "Müşteri isteği detaylarını ve durumunu güncelleyin.",
    "QuotationRequest.Edit.UpdateRequest": "İsteği Güncelle",
    "QuotationRequest.Edit.Updating": "Güncelleniyor...",
    "QuotationRequest.Edit.UpdatedToast": "Teklif isteği güncellendi",
    "QuotationRequest.Status.Open": "Açık",
    "QuotationRequest.Status.Submitted": "Gönderildi",
    "QuotationRequest.Status.Closed": "Kapalı",
    "QuotationRequest.Status.Cancelled": "İptal edildi"
  },
  "pt-PT": {
    "Login.RequestQuotation": "Solicitar cotação",
    "Navigation.rate-quotation.Item.quotation-requests.Label": "Pedidos de cotação",
    "Navigation.rate-quotation.Item.quotation-requests.Description": "Pedidos de cotação de clientes e anexos carregados.",
    "QuotationRequest.AppName": "ERP de Freight Forwarding",
    "QuotationRequest.Create.Title": "Pedido de cotação",
    "QuotationRequest.Create.ShipmentDetails": "Detalhes da remessa",
    "QuotationRequest.Create.UploadLink": "Ligação de carregamento",
    "QuotationRequest.Create.RequestReady": "O pedido {0} está pronto.",
    "QuotationRequest.Create.EmptyUploadLink": "Crie um pedido para gerar uma ligação privada de carregamento.",
    "QuotationRequest.Create.CreatedToast": "Pedido de cotação criado",
    "QuotationRequest.Create.LinkCopiedToast": "Ligação copiada",
    "QuotationRequest.Create.LinkCopiedDetail": "Partilhe com o cliente para carregar ficheiros, vídeo ou áudio.",
    "QuotationRequest.Create.Creating": "A criar...",
    "QuotationRequest.Create.CreateRequest": "Criar pedido",
    "QuotationRequest.Create.CopyLink": "Copiar ligação",
    "QuotationRequest.Create.OpenUpload": "Abrir carregamento",
    "QuotationRequest.Label.CustomerName": "Nome do cliente",
    "QuotationRequest.Label.Company": "Empresa",
    "QuotationRequest.Label.Email": "E-mail",
    "QuotationRequest.Label.Phone": "Telefone",
    "QuotationRequest.Label.Origin": "Origem",
    "QuotationRequest.Label.Destination": "Destino",
    "QuotationRequest.Label.Mode": "Modo",
    "QuotationRequest.Label.ShipmentType": "Tipo de remessa",
    "QuotationRequest.Label.CargoDescription": "Descrição da carga",
    "QuotationRequest.Label.Status": "Estado",
    "QuotationRequest.Placeholder.CustomerName": "Introduza o nome do cliente",
    "QuotationRequest.Placeholder.Company": "Introduza o nome da empresa",
    "QuotationRequest.Placeholder.Email": "Introduza o endereço de e-mail",
    "QuotationRequest.Placeholder.Phone": "Introduza o número de telefone",
    "QuotationRequest.Placeholder.Origin": "Introduza a origem",
    "QuotationRequest.Placeholder.Destination": "Introduza o destino",
    "QuotationRequest.Placeholder.CargoDescription": "Descreva a carga, peso, volume e instruções de manuseamento",
    "QuotationRequest.Mode.Air": "Aéreo",
    "QuotationRequest.Mode.Sea": "Marítimo",
    "QuotationRequest.Mode.Road": "Rodoviário",
    "QuotationRequest.Mode.Courier": "Courier",
    "QuotationRequest.ShipmentType.General": "Geral",
    "QuotationRequest.ShipmentType.Import": "Importação",
    "QuotationRequest.ShipmentType.Export": "Exportação",
    "QuotationRequest.ShipmentType.DoorToDoor": "Porta a porta",
    "QuotationRequest.Upload.Loading": "A carregar pedido de cotação...",
    "QuotationRequest.Upload.NotFound": "A ligação do pedido de cotação não foi encontrada.",
    "QuotationRequest.Upload.RequestNumber": "Pedido {0}",
    "QuotationRequest.Upload.Title": "Carregar media da remessa",
    "QuotationRequest.Upload.Video": "Vídeo",
    "QuotationRequest.Upload.CameraVideo": "Vídeo da câmara",
    "QuotationRequest.Upload.RecordVideo": "Gravar vídeo",
    "QuotationRequest.Upload.Audio": "Áudio",
    "QuotationRequest.Upload.MicrophoneAudio": "Áudio do microfone",
    "QuotationRequest.Upload.RecordAudio": "Gravar áudio",
    "QuotationRequest.Upload.File": "Ficheiro",
    "QuotationRequest.Upload.ChooseFile": "Escolher ficheiro",
    "QuotationRequest.Upload.FileHelp": "Fotografias, PDFs, documentos e outros ficheiros de suporte.",
    "QuotationRequest.Upload.RecordingInProgress": "Gravação de {0} em curso",
    "QuotationRequest.Upload.Stop": "Parar",
    "QuotationRequest.Upload.MicrophoneSignal": "Sinal do microfone",
    "QuotationRequest.Upload.ReadyToUpload": "{0} pronto para carregar",
    "QuotationRequest.Upload.Recapture": "Repetir captura",
    "QuotationRequest.Upload.Upload": "Carregar",
    "QuotationRequest.Upload.Uploading": "A carregar",
    "QuotationRequest.Upload.UploadComplete": "Carregamento concluído",
    "QuotationRequest.Upload.UploadedItems": "Itens carregados",
    "QuotationRequest.Upload.NoUploads": "Ainda não há carregamentos.",
    "QuotationRequest.Upload.FilesAttached": "Os ficheiros estão anexados a este pedido de cotação.",
    "QuotationRequest.List.Title": "Pedidos de cotação",
    "QuotationRequest.List.Description": "Pedidos de cotação de clientes recebidos através de ligações públicas de carregamento.",
    "QuotationRequest.List.RequestNo": "N.º do pedido",
    "QuotationRequest.List.Customer": "Cliente",
    "QuotationRequest.List.Company": "Empresa",
    "QuotationRequest.List.Origin": "Origem",
    "QuotationRequest.List.Destination": "Destino",
    "QuotationRequest.List.Mode": "Modo",
    "QuotationRequest.List.Attachments": "Anexos",
    "QuotationRequest.List.Status": "Estado",
    "QuotationRequest.List.Actions": "Ações",
    "QuotationRequest.List.ViewRequest": "Ver pedido",
    "QuotationRequest.List.EditRequest": "Editar pedido",
    "QuotationRequest.View.Title": "Pedido de cotação",
    "QuotationRequest.View.TitleWithNumber": "Pedido de cotação {0}",
    "QuotationRequest.View.Description": "Detalhes do pedido do cliente e anexos carregados.",
    "QuotationRequest.View.Back": "Voltar",
    "QuotationRequest.View.RequestDetails": "Detalhes do pedido",
    "QuotationRequest.View.Attachments": "Anexos",
    "QuotationRequest.View.NoAttachments": "Nenhum anexo carregado.",
    "QuotationRequest.View.Download": "Transferir",
    "QuotationRequest.View.Loading": "A carregar pedido...",
    "QuotationRequest.View.NotFound": "Pedido de cotação não encontrado.",
    "QuotationRequest.Edit.Title": "Editar pedido de cotação",
    "QuotationRequest.Edit.TitleWithNumber": "Editar pedido de cotação {0}",
    "QuotationRequest.Edit.Description": "Atualizar detalhes e estado do pedido do cliente.",
    "QuotationRequest.Edit.UpdateRequest": "Atualizar pedido",
    "QuotationRequest.Edit.Updating": "A atualizar...",
    "QuotationRequest.Edit.UpdatedToast": "Pedido de cotação atualizado",
    "QuotationRequest.Status.Open": "Aberto",
    "QuotationRequest.Status.Submitted": "Submetido",
    "QuotationRequest.Status.Closed": "Fechado",
    "QuotationRequest.Status.Cancelled": "Cancelado"
  },
  "ru-RU": {
    "Login.RequestQuotation": "Запросить предложение",
    "Navigation.rate-quotation.Item.quotation-requests.Label": "Запросы предложений",
    "Navigation.rate-quotation.Item.quotation-requests.Description": "Запросы предложений клиентов и загруженные вложения.",
    "QuotationRequest.AppName": "ERP экспедирования",
    "QuotationRequest.Create.Title": "Запрос предложения",
    "QuotationRequest.Create.ShipmentDetails": "Детали отправки",
    "QuotationRequest.Create.UploadLink": "Ссылка для загрузки",
    "QuotationRequest.Create.RequestReady": "Запрос {0} готов.",
    "QuotationRequest.Create.EmptyUploadLink": "Создайте запрос, чтобы получить приватную ссылку для загрузки.",
    "QuotationRequest.Create.CreatedToast": "Запрос предложения создан",
    "QuotationRequest.Create.LinkCopiedToast": "Ссылка скопирована",
    "QuotationRequest.Create.LinkCopiedDetail": "Поделитесь ею с клиентом для загрузки файлов, видео или аудио.",
    "QuotationRequest.Create.Creating": "Создание...",
    "QuotationRequest.Create.CreateRequest": "Создать запрос",
    "QuotationRequest.Create.CopyLink": "Копировать ссылку",
    "QuotationRequest.Create.OpenUpload": "Открыть загрузку",
    "QuotationRequest.Label.CustomerName": "Имя клиента",
    "QuotationRequest.Label.Company": "Компания",
    "QuotationRequest.Label.Email": "Эл. почта",
    "QuotationRequest.Label.Phone": "Телефон",
    "QuotationRequest.Label.Origin": "Пункт отправления",
    "QuotationRequest.Label.Destination": "Пункт назначения",
    "QuotationRequest.Label.Mode": "Способ",
    "QuotationRequest.Label.ShipmentType": "Тип отправки",
    "QuotationRequest.Label.CargoDescription": "Описание груза",
    "QuotationRequest.Label.Status": "Статус",
    "QuotationRequest.Placeholder.CustomerName": "Введите имя клиента",
    "QuotationRequest.Placeholder.Company": "Введите название компании",
    "QuotationRequest.Placeholder.Email": "Введите адрес эл. почты",
    "QuotationRequest.Placeholder.Phone": "Введите номер телефона",
    "QuotationRequest.Placeholder.Origin": "Введите пункт отправления",
    "QuotationRequest.Placeholder.Destination": "Введите пункт назначения",
    "QuotationRequest.Placeholder.CargoDescription": "Опишите груз, вес, объем и инструкции по обработке",
    "QuotationRequest.Mode.Air": "Авиа",
    "QuotationRequest.Mode.Sea": "Море",
    "QuotationRequest.Mode.Road": "Авто",
    "QuotationRequest.Mode.Courier": "Курьер",
    "QuotationRequest.ShipmentType.General": "Общий",
    "QuotationRequest.ShipmentType.Import": "Импорт",
    "QuotationRequest.ShipmentType.Export": "Экспорт",
    "QuotationRequest.ShipmentType.DoorToDoor": "От двери до двери",
    "QuotationRequest.Upload.Loading": "Загрузка запроса предложения...",
    "QuotationRequest.Upload.NotFound": "Ссылка запроса предложения не найдена.",
    "QuotationRequest.Upload.RequestNumber": "Запрос {0}",
    "QuotationRequest.Upload.Title": "Загрузить материалы отправки",
    "QuotationRequest.Upload.Video": "Видео",
    "QuotationRequest.Upload.CameraVideo": "Видео с камеры",
    "QuotationRequest.Upload.RecordVideo": "Записать видео",
    "QuotationRequest.Upload.Audio": "Аудио",
    "QuotationRequest.Upload.MicrophoneAudio": "Аудио с микрофона",
    "QuotationRequest.Upload.RecordAudio": "Записать аудио",
    "QuotationRequest.Upload.File": "Файл",
    "QuotationRequest.Upload.ChooseFile": "Выбрать файл",
    "QuotationRequest.Upload.FileHelp": "Фото, PDF, документы и другие подтверждающие файлы.",
    "QuotationRequest.Upload.RecordingInProgress": "Идет запись {0}",
    "QuotationRequest.Upload.Stop": "Остановить",
    "QuotationRequest.Upload.MicrophoneSignal": "Сигнал микрофона",
    "QuotationRequest.Upload.ReadyToUpload": "{0} готово к загрузке",
    "QuotationRequest.Upload.Recapture": "Записать снова",
    "QuotationRequest.Upload.Upload": "Загрузить",
    "QuotationRequest.Upload.Uploading": "Загрузка",
    "QuotationRequest.Upload.UploadComplete": "Загрузка завершена",
    "QuotationRequest.Upload.UploadedItems": "Загруженные элементы",
    "QuotationRequest.Upload.NoUploads": "Загрузок пока нет.",
    "QuotationRequest.Upload.FilesAttached": "Файлы прикреплены к этому запросу предложения.",
    "QuotationRequest.List.Title": "Запросы предложений",
    "QuotationRequest.List.Description": "Запросы предложений клиентов, полученные через публичные ссылки загрузки.",
    "QuotationRequest.List.RequestNo": "№ запроса",
    "QuotationRequest.List.Customer": "Клиент",
    "QuotationRequest.List.Company": "Компания",
    "QuotationRequest.List.Origin": "Отправление",
    "QuotationRequest.List.Destination": "Назначение",
    "QuotationRequest.List.Mode": "Способ",
    "QuotationRequest.List.Attachments": "Вложения",
    "QuotationRequest.List.Status": "Статус",
    "QuotationRequest.List.Actions": "Действия",
    "QuotationRequest.List.ViewRequest": "Просмотреть запрос",
    "QuotationRequest.List.EditRequest": "Изменить запрос",
    "QuotationRequest.View.Title": "Запрос предложения",
    "QuotationRequest.View.TitleWithNumber": "Запрос предложения {0}",
    "QuotationRequest.View.Description": "Детали запроса клиента и загруженные вложения.",
    "QuotationRequest.View.Back": "Назад",
    "QuotationRequest.View.RequestDetails": "Детали запроса",
    "QuotationRequest.View.Attachments": "Вложения",
    "QuotationRequest.View.NoAttachments": "Вложения не загружены.",
    "QuotationRequest.View.Download": "Скачать",
    "QuotationRequest.View.Loading": "Загрузка запроса...",
    "QuotationRequest.View.NotFound": "Запрос предложения не найден.",
    "QuotationRequest.Edit.Title": "Изменить запрос предложения",
    "QuotationRequest.Edit.TitleWithNumber": "Изменить запрос предложения {0}",
    "QuotationRequest.Edit.Description": "Обновите детали и статус запроса клиента.",
    "QuotationRequest.Edit.UpdateRequest": "Обновить запрос",
    "QuotationRequest.Edit.Updating": "Обновление...",
    "QuotationRequest.Edit.UpdatedToast": "Запрос предложения обновлен",
    "QuotationRequest.Status.Open": "Открыт",
    "QuotationRequest.Status.Submitted": "Отправлен",
    "QuotationRequest.Status.Closed": "Закрыт",
    "QuotationRequest.Status.Cancelled": "Отменен"
  }
};
